### ISSUE TITLE
Tampermonkey can't run scripts (properly?)

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#105]
Greasyork script will soon not work when loading pages completely when using tampermonkey.

**Comment by interfect** [comment]
This sounds like an incompatibility between Tampermonkey and the `android-components` we ship. Have you reported the issue to the Tampermonkey devs? They may need to take the add-on into the new Android Mozilla Firefox dev tools and port it over to the new APIs, or find and report to Mozilla the bug in the API that breaks it. If it works in their dev tools it ought to work in Iceweasel.

**Comment by jesus2099** [comment]
@Rosabis, is it still not working?
With what script on what site?

I use many userscripts everyday on MusicBrainz.org running on Violentmonkey with no issues.

**Comment by ghost** [comment]
> @Rosabis, is it still not working?
> With what script on what site?
> 
> I use many userscripts everyday on MusicBrainz.org running on Violentmonkey with no issues.

Well, except for exporting the script to local from fenix 86+, it can all work normally, and I hope it can support adjusting the light or dark mode according to the browser theme

**Comment by jesus2099** [comment]
On my side I've had [some issues](https://github.com/jesus2099/konami-command/issues?q=is%3Aissue+iceraven+) at the moment with no time to understand why, so I went back using Firefox 68, for the moment.

**Comment by Iey4iej3** [comment]
Both tampermonkey and violentmonkey seem working now.

**Comment by Iey4iej3** [comment]
I propose to cooperate to support FireMonkey. Related post: https://github.com/erosman/support/issues/238

**Comment by crazyn2** [comment]
violentmonkey is too in 1.18.4
