### ISSUE TITLE
[Bug] IceWeasel Crashing with microG since fork-6

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#107]
## Steps to reproduce
Use normally it will crash at least once in 1 hour crossing session

### Device information
Android 10 arm64v8a AOSP with microG services only 
* Android device: 10
* Fenix version: fork 10 latest 

This issue exist since fork 6 for me 
If any microG[microG](https://microg.org)  user can confirm it is crashing for them it would be great .

Log https://github.com/interfect/fenix/files/5144927/fenixfork6.zip

**Comment by interfect** [comment]
Definitely sounds like a bug. Someone will have to dig through the logs. It could be that it's trying to generate a telemetry report to not send and wants to talk to Play Services.

Actually, did you ever have it installed before we ripped out telemetry? It could be you had telemetry on when the settings were removed, and need to clear the app data to get the new default of off.

**Comment by ghost** [comment]
Yes I am using it since second release 
These problems started from fork 6 version

**Comment by interfect** [comment]
I'm not sure you've captured a log of the crash itself happening. I don't see a stack trace or an indication that the app did anything unacceptable, although I do see the crash report dialog opening. Your log spans from 08-29 10:01:54.061 to 08-29 10:11:36.702; do you happen to remember the timestamp you observed a crash at?

In the log I see it... talking to LastPass? And then talking about filesystem and package install permissions, and then opening a download notification I think? And everything seems to be going fine until it talks to `net.ohrz.lawndesk` (which I think is your launcher), and then it starts destroying things and there are some error (`E`) level log messages:

```
08-29 10:11:02.873 I/am_on_start_called(25737): [0,network.novak.iceweasel.App,handleStartActivity]
08-29 10:11:02.888 I/am_on_resume_called(25737): [0,network.novak.iceweasel.App,RESUME_ACTIVITY]
08-29 10:11:02.890 I/am_on_top_resumed_gained_called(25737): [0,network.novak.iceweasel.App,topWhenResuming]
08-29 10:11:03.038 I/sysui_multi_action(1412): [319,33,321,27,322,219,325,61253,757,761,758,9,759,4,806,network.novak.iceweasel,871,network.novak.iceweasel.App,904,net.ohrz.lawndesk,905,0,1320,8,1321,4]
08-29 06:04:21.737 E/AndroidRuntime(6599): Process: network.novak.iceweasel, PID: 6599
08-29 10:11:29.156 I/am_finish_activity(1412): [0,242380657,717,network.novak.iceweasel/.App,app-request]
08-29 06:04:23.468 E/AndroidRuntime(8974): Process: network.novak.iceweasel, PID: 8974
08-29 10:11:29.166 I/am_pause_activity(1412): [0,242380657,network.novak.iceweasel/.App,userLeaving=false]
08-29 10:11:29.168 I/am_on_top_resumed_lost_called(25737): [0,network.novak.iceweasel.App,topStateChangedWhenResumed]
08-29 10:11:29.169 I/am_on_paused_called(25737): [0,network.novak.iceweasel.App,performPause]
08-29 10:11:29.170 I/am_add_to_stopping(1412): [0,242380657,network.novak.iceweasel/.App,finishCurrentActivityLocked]
08-29 06:04:25.828 E/AndroidRuntime(9128): Process: network.novak.iceweasel, PID: 9128
08-29 06:04:41.829 E/AndroidRuntime(9345): Process: network.novak.iceweasel, PID: 9345
08-29 10:11:29.656 I/am_destroy_activity(1412): [0,242380657,717,network.novak.iceweasel/.App,finish-imm:activityIdleInternalLocked]
... (The timestamps go back in time also, which is weird)
08-29 10:01:54.896 W/ActivityTaskManager(1412):   Force finishing activity network.novak.iceweasel/.App
08-29 10:01:55.001 I/ActivityManager(1412): Process network.novak.iceweasel (pid 19474) has died: fore TOP 
```

In the crash reporter it looks like you still have telemetry on (Or maybe you hit report?):
```
08-29 10:09:06.166 I/libglean_ffi(25737): glean_core::upload::directory: File was deleted /data/user/0/network.novak.iceweasel/glean_data/pending_pings/213abd05-e4ad-4055-83cd-0f1fdf4c6b90
08-29 10:09:27.377 D/libglean_ffi(25737): glean_core::ping: Storing ping '5259cce0-5938-41fa-ada0-382157c8e1cd' at '/data/user/0/network.novak.iceweasel/glean_data/deletion_request/5259cce0-5938-41fa-ada0-382157c8e1cd'
08-29 10:09:27.377 I/libglean_ffi(25737): glean_core::upload::directory: Processing ping at: /data/user/0/network.novak.iceweasel/glean_data/deletion_request/5259cce0-5938-41fa-ada0-382157c8e1cd
08-29 10:09:27.941 I/libglean_ffi(25737): glean_core::upload::directory: File was deleted /data/user/0/network.novak.iceweasel/glean_data/deletion_request/5259cce0-5938-41fa-ada0-382157c8e1cd
08-29 10:09:31.265 D/SharedPreferencesImpl(25737): Time required to fsync /data/user/0/network.novak.iceweasel/shared_prefs/fenix_preferences.xml: [<1: 0, <2: 0, <4: 1, <8: 4, <16: 5, <32: 2, <64: 0, <128: 0, <256: 0, <512: 1, <1024: 0, <2048: 1, <4096: 0, <8192: 0, <16384: 0, >=16384: 0]
```

Also, this log is timestamped too old to be from fork-10, and fork-6 had an unrelated (?) crash bug when set as the default browser.

Can you capture a new log with fork-10 installed and maybe with a different launcher set? Unless the message about the launcher is just to indicate you're using it to switch apps. Ideally you would hook it up with USB debugging and `adb logcat` on the PC and copy-paste just the stuff it spits out exactly when it crashes.

**Comment by interfect** [comment]
@cleanerspam Can you confirm the problem persists after clearing the app data, or a complete uninstall and reinstall of the app (to default the telemetry settings back to false)?

**Comment by ghost** [comment]
I will give a new log as soon as it crashes while I am using it of version fork 10

**Comment by ghost** [comment]
@interfect 
I have not faced any crash since browser has been  rebranded .
