### ISSUE TITLE
Add  a home button

### ISSUE THREAD

**Issue by revolutionaryking7** [fork-maintainers/iceraven-browser#112]
### What is the user problem or growth opportunity you want to see solved?
The new tab tray grid layout looks and perform better than fenix... However I see home button is missing in the tab tray..  Is it possible to add to the tab tray? Else there is no option to go to home from tab tray 

### How do you know that this problem exists today? Why is this important?
Currently there is no option to go to homepage from tabs tray... It is possible by clicking new tab button but that requires another click to see the homepage by removing focus on address bar

### Who will benefit from it?
All users 
![Screenshot_20200915-123429343 (1)](https://user-images.githubusercontent.com/58127841/93177282-36611d80-f750-11ea-86d1-caf9bbd29af9.jpg)

**Comment by interfect** [comment]
This is an idea. I might want it in the menu instead of the tab tray, but could go either way.

I think this is being tracked in #53 though.
