### ISSUE TITLE
Add-on requests (not on the list)

### ISSUE THREAD

**Issue by Poopooracoocoo** [fork-maintainers/iceraven-browser#12]
Could you please add the following add-ons? :)
Stylus (open source alternative to Stylish): https://addons.mozilla.org/en-US/android/addon/styl-us/

External Video Player: https://addons.mozilla.org/en-US/android/addon/external-video-player/

Google Search Fixer: https://addons.mozilla.org/en-US/android/addon/google-search-fixer/

Remove Reddit app promos: https://addons.mozilla.org/en-US/firefox/addon/remove-reddit-app-promos/

These are all open source. I don't know if they'll work in Fenix. You don't have to do this but you might like one of these. :) Your fork is awesome! I did of course read your motto :p and I also checked out the list of addons that you want.

**Comment by interfect** [comment]
These are now on the list!
