### ISSUE TITLE
My attempted logo design

### ISSUE THREAD

**Issue by abhijitvalluri** [fork-maintainers/iceraven-browser#133]
I attempted to make a logo with my limited knowledge of inkscape. It was quite challenging but here it is!

![iceraven_logo](https://user-images.githubusercontent.com/17151327/93610257-bf808a80-f9c4-11ea-9f95-488d984d3b9b.png)

It was heavily inspired by this user created Firefox logo: 
[<img src="https://i.redd.it/h6n0qttrfyy41.png" width="300" />](https://www.reddit.com/r/firefox/comments/gkcag5/minimalist_logoicon_reimagining_by_me/)

I used this base [SVG image of a bird silhouette](https://www.svgrepo.com/svg/123268/raven) for the bird. Feel free to use that same SVG for your own design. I can share the SVG I created as well.

I chose a whitish color scheme for the bird, because it is an "ice" raven. So, even though ravens are black, this one is icy in color! 😄 

I tried importing this SVG in Android Studio for creating a launcher icon, however the gradient colors I used in my SVG seem to be incompatible with Android Studio's tools. So, my icon ended up looking very weird and colorless. I had to instead import a PNG version of the above design for it to look decent in Android Studio. If you have suggestions on how to make my design work correctly in AS let me know!

**Comment by bbigam** [comment]
Nice start. May I suggest bringing up the contrast between the raven and the globe? Maybe the raven a little lighter and the globe a little darker? I'm concerned the raven might not stand out clearly at small sizes with the current coloring.

I'd also suggest a slightly sharper beak, slightly downturned at the end, that would be more raveney. :-)

That said, I'd have no idea how to do this myself!

**Comment by abhijitvalluri** [comment]
Those are good suggestions. However I am not very familiar with inkscape and vector image editing tools either to be able to make those changes confidently! 😄 I can share the SVG image I created so that someone more capable can give it a shot!

**Comment by ghost** [comment]
This looks fantastic, well done!

**Comment by revolutionaryking7** [comment]
Both looks really good.... But my preference is 2nd one
Fox inside the globe

**Comment by interfect** [comment]
I had to run the weasel icon through https://github.com/14v/svg-non-stop I think to make Android Studio happy with it. Maybe that would help on the gradient import?

See also: https://stackoverflow.com/questions/57431043/gradient-has-no-stop-info-error-while-importing-svg-file-in-android-studio

**Comment by interfect** [comment]
Here's the image tinified to evaluate its iconitude:

![image](https://user-images.githubusercontent.com/752054/93659024-c5429400-f9f5-11ea-8950-8fc88abbbc6c.png)

I like it. I also think upping the contrast would be good.

It probably looks like real ravens do. Cartoon ravens are pointier. But IDK if we want a pointy app icon; are we making a pointy browser?

**Comment by abhijitvalluri** [comment]
Closing this in preference to the better design from #134. Looks like they are far more talented and capable at design than me.
