### ISSUE TITLE
Option in Settings to make Top Sites icons large

### ISSUE THREAD

**Issue by Zaotar** [fork-maintainers/iceraven-browser#135]
### What is the user problem or growth opportunity you want to see solved?
Now top sites icons are small for me with my big fingers ;)
I've modded Iceraven browser and made icons bigger and more visible. Just change this:
/res/values/dimens.xml:
top_sites_item_size=82.0dip
top_sites_favicon_size72.0dip
Here is result - https://drive.google.com/drive/folders/1bdU_7LrrXGAO1gsx1BBe5NAbiyuU6IEu?usp=sharing
### How do you know that this problem exists today? Why is this important?
In Opera browser for Android such option is Settings exists and I think is usefull and comfortable
### Who will benefit from it?
Users with big fingers and old eyes ;)

**Comment by interfect** [comment]
They are pretty small.

**Comment by deytulsi18** [comment]
hello, I am getting started with open source, please help me getting stated and solve some beggginer issues.
May I work on this issue ?

**Comment by interfect** [comment]
@deytulsi18, you are quite welcome to work on this issue if you would like. I don't think anyone else is working on it at the moment.

In terms of guidance, I think we prefer having configuration options for UI changes (so people can pick what size icons they want), and we prefer changes that are unlikely to create conflicts when Mozilla also makes changes.

**Comment by akliuxingyuan** [comment]
the touchable area is not same as icon, it's a square container which include icon and site's name, and there are four shortcuts in a row, so the space is evenly divided, increasing icon size changes nothing.

you can turn on "Show layout bounds" option in developer settings and test it
<img src="https://github.com/fork-maintainers/iceraven-browser/assets/53224655/92c8ed53-e56f-4abd-80a7-b502d19f5b7c" width=30%>
