### ISSUE TITLE
[Bug]Scrolling a map reloads tab instantly

### ISSUE THREAD

**Issue by kufue** [fork-maintainers/iceraven-browser#137]
## Steps to reproduce
Enter openstreetmap/google/yandex map, zoom a bit, try to drag down with one finger
### Expected behavior
it should just move the map as if i was draging it above the table
### Actual behavior
Reloads the page if a drag is longer than 1mm
### Device information
V8 arm
* Android device: ?
10
* Fenix version: ?
1.0 iceraven

**Comment by interfect** [comment]
I can reproduce this. This is the new pull to refresh feature (#108).

The workaround is to go to "Settings" -> "Customize", scroll down, and in "Gestures" turn off "Pull to refresh".

We turned it on before it was fully baked in Mozilla Firefox because of how cool it is, but it does seem to cause trouble for maps.

**Comment by interfect** [comment]
The question is what do we do: turn it back off (by default)? Or try and fix it properly? Or just leave it?

@abhijitvalluri, what do you think?

**Comment by abhijitvalluri** [comment]
I can't reproduce it with Google maps but I could reproduce the bug with open street maps. It's a bug but to be fair, Mozilla hasn't enabled this feature officially yet so they probably didn't iron out all the issues. Not sure if it's worth fixing if they will fix it upstream.

And for that matter, I can't get pull to refresh to work properly on Google websites at all!

**Comment by jesus2099** [comment]
It is good that we can turn it off, as the reload menu item is easily found and the pull to reload feature caused issues everywhere you need to scroll down: long pages, [forums](https://meta.discourse.org), etc.

**Comment by akliuxingyuan** [comment]
working properly now
