### ISSUE TITLE
[Bug] pull to refresh

### ISSUE THREAD

**Issue by revolutionaryking7** [fork-maintainers/iceraven-browser#140]
## Steps to reproduce
Sign out of github 
Click sign in 
It is triggering pull to refresh instead of sign in

### Expected behavior
Should open signin page

### Actual behavior
Triggering pull to refresh

### Device information

* Android device: ? Rog3 
* Fenix version: ?iceraven latest 
![Screenshot_20200920-094429493](https://user-images.githubusercontent.com/58127841/93694138-e7d3ca80-fb25-11ea-9be6-31edb8ef8e47.jpg)

**Comment by abhijitvalluri** [comment]
Pull to refresh seems to be buggy. I think think affects upstream official Firefox as well.

**Comment by abhijitvalluri** [comment]
I will have to see if it's possible and worth fixing this or wait for Mozilla to fix it.

**Comment by bbigam** [comment]
There are lots of upstream issues about pull to refresh, here's a meta and even it's incomplete: https://github.com/mozilla-mobile/fenix/issues/9766

Seems like pull to refresh has been quite buggy in Fenix all along.

**Comment by revolutionaryking7** [comment]
> Pull to refresh seems to be buggy. I think think affects upstream official Firefox as well.

Probably this is the reason they have kept it hidden... Issue is with fenix only...  Atleast in ice raven we have pull to refresh add on which works fine....

**Comment by interfect** [comment]
See also: #137, which lists the workaround to turn it off.

We probably should make pull to refresh off by default, I think, until we or Mozilla work out all the kinks. Cool people who enjoy bugs can just turn it on, right?

**Comment by akliuxingyuan** [comment]
working properly now
