### ISSUE TITLE
Change download notification color 

### ISSUE THREAD

**Issue by revolutionaryking7** [fork-maintainers/iceraven-browser#141]
### What is the user problem or growth opportunity you want to see solved?
The current color scheme green neither matches firefox color scheme nor system color... So i feel it is better to change to Firefox colors like in below screenshot 

### How do you know that this problem exists today? Why is this important?
The present color green looks odd... It is not system color or Firefox color

### Who will benefit from it?
All users 

![Screenshot_20200920-094804658 (1)](https://user-images.githubusercontent.com/58127841/93694216-a2fc6380-fb26-11ea-849a-31bc379a46c8.jpg)

**Comment by interfect** [comment]
Hm. My notification tray has a lot of green from the system, so I didn't notice that we were sending a color at all. We *should* be sending the same colors as Firefox, because I don't think we tried to change them, but apparently we aren't.
