### ISSUE TITLE
[Bug]Cannot display the options at the bottom of about:config 

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#150]
## Steps to reproduce
1.Enter about:config in address bar
2.Swipe to the bottom of the page
### Expected behavior
Can see all the items
### Actual behavior
The bottom item is blocked by the URL bar at the bottom,see screenshot
![93725946-d8b45180-fbe5-11ea-8903-42514cfddbe1](https://user-images.githubusercontent.com/32984303/93966118-7babcd80-fd96-11ea-8481-ec207482915e.png)

### Device information

* Android device: 
* Fenix version: icecraven 1.0.0

**Comment by interfect** [comment]
I suspect this affects Firefox Nightly as well as us.

Tbe workaround is going to be to set the address bar to the top to see that last setting, and I bet the fix has to be in `android-components` to just make the page taller.

**Comment by ghost** [comment]
> I suspect this affects Firefox Nightly as well as us.
> 
> Tbe workaround is going to be to set the address bar to the top to see that last setting, and I bet the fix has to be in `android-components` to just make the page taller.

I have asked them about it,but they said they have fixed it in the latest firefox nightly,idk.🤔

**Comment by bbigam** [comment]
There is tons of info about this bug here: https://github.com/mozilla-mobile/fenix/issues/13797
But I'm afraid it's rather more technical than I can understand...
It is at least partially fixed in Nightly, and has been for a while now. Not sure why it hasn't trickled down to release, beta, or us.

**Comment by interfect** [comment]
Could be the fix is inside the Gecko piece itself, for which we use the stable version.
