### ISSUE TITLE
Extension menu is too slow and not enough like the SimpleExtManager Chrome extension

### ISSUE THREAD

**Issue by irwan-batra** [fork-maintainers/iceraven-browser#155]
### What is the user problem or growth opportunity you want to see solved?
Very slow extension menu. although i know its hard bcoz ff 'doesnt' reveal its extention manager api. 
### How do you know that this problem exists today? Why is this important?
From starting
### Who will benefit from it?
Evveryone.

**Comment by irwan-batra** [comment]
https://chrome.google.com/webstore/detail/simpleextmanager/kniehgiejgnnpgojkdhhjbgbllnfkfdk
i hv sugested this one. I like its ui annd all feature

**Comment by interfect** [comment]
I don't think we'll be able to take a Chrome extension and use it to manage add-ons in Iceraven.

But are you having a problem with the add-on list being slow to load initially? We might be able to fix that, or at least get it to show you *some* add-ons more quickly. Right now it's doing 5 round trips to the server to download the 5 page add-on list, and only then returning any of them. We could potentially change it to return them a little at a time, or at least make it kick off the process when you first open the app, to try and speed that up.
