### ISSUE TITLE
Version Number with each update 

### ISSUE THREAD

**Issue by dfrost16** [fork-maintainers/iceraven-browser#172]
It would be beneficial if we can get version number after each release it helps to distinguish between previous build and new one and is over-all feasible and maybe remove fork release from name to shorten the name

**Comment by abhijitvalluri** [comment]
Good idea! I will work on this :)

**Comment by interfect** [comment]
Is this about the file names of the APK files? We already have version numbers in the app itself, in the interval version presented to Android, in the tag names, and in the release titles.

**Comment by dfrost16** [comment]
The release page in GitHub.

**Comment by abhijitvalluri** [comment]
Fixed. Latest release (iceraven-1.2.0) has the version number in the name of the apk file.
