### ISSUE TITLE
Integrated Pin/Password

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#173]
### What is the user problem or growth opportunity you want to see solved?
The ability to lock the app behind a password, pin or maybe even biometric for those who use it.
### How do you know that this problem exists today? Why is this important?
Block out the nosy and invasive eyes. 
### Who will benefit from it
Those who would like this feature to be implemented within time.

**Comment by abhijitvalluri** [comment]
This is quite an invasive feature and very niche. Couldn't you instead use a third-party app that can lock other apps, such as [AppLock](https://play.google.com/store/apps/details?id=com.sp.protector.free)?

**Comment by interfect** [comment]
AppLock and similar solutions are all kind of fake, as far as I know; I think they just pop up over whatever app they're supposed to be locking, and can be uninstalled.

Some Android distributions build in a way to lock an app specifically with a PIN or pattern, which I suspect is more robust, but not all of them provide this.

But this would also take a lot of work to implement as a feature we provide in the browser.

**Comment by abhijitvalluri** [comment]
Depends on how much level of security we require. For casual security against a kid or something, perhaps AppLock may be enough. For more robust security, we may need something else. Would be quite complicated to implement. Perhaps worth asking other if this is a feature they need to gauge interest.

**Comment by ghost** [comment]
This is also something that can be done with certain launchers, e.g. Trebuchet, the default launcher for LineageOS. I also think there's a bunch of FOSS apps for this already, not sure if it is actually worth implementing as something inherent to the Iceraven app when there are other (and potentially better) ways to do it.
