### ISSUE TITLE
Request for options to remove "save to collection" and "scan" from Iceraven

### ISSUE THREAD

**Issue by TheJags** [fork-maintainers/iceraven-browser#174]
### What is the user problem or growth opportunity you want to see solved?
(1) There's huge "Save to collection in the middle of the tab list page, and for those who are not using collections, it is of no use.

![Save to collection](https://user-images.githubusercontent.com/47936415/94464463-23346000-01dc-11eb-80c4-d34fd55d9f20.jpg)

(2) "Scan" option shows up every time I try to enter any URL.

![Scan](https://user-images.githubusercontent.com/47936415/94464532-36473000-01dc-11eb-87ae-a14f03908458.jpg)

### How do you know that this problem exists today? Why is this important?
Save to collection is useless for those who are not using collections. So there is no point on having on tab list page. Same thing goes for "scan" option.

I'm just requesting for options to remove both of these under "settings".

### Who will benefit from it?
Everyone that are not using collection or scan option will benefit from this change. Thanks.

**Comment by interfect** [comment]
We might even want Save to Collection to by default be a menu item in the tab tray, rather than a big button.

**Comment by TheJags** [comment]
@interfect Please pardon my ignorance as I'm not a developer but is it possible to have a settings that says disable / remove Collections, Save to collection, Scan etc **everywhere** in the Iceraven :)

I think there would be many users that don't use collections at all. Thanks alot.

**Comment by akliuxingyuan** [comment]
`Save to collection` is gone, for the scan button in the address bar, we can provide a switch menu in `Setting > Search > Address bar preferences`

**Comment by akliuxingyuan** [comment]
fix in https://github.com/fork-maintainers/iceraven-browser/releases/tag/iceraven-2.18.4
