### ISSUE TITLE
Request for dark mode and font size options for Iceraven reader view

### ISSUE THREAD

**Issue by TheJags** [fork-maintainers/iceraven-browser#175]
### What is the user problem or growth opportunity you want to see solved?
Iceraven's reader view is missing options to have dark mode, and adjust font size.

Iceraven reader view:

![Reader_View_Fenix](https://user-images.githubusercontent.com/47936415/94465289-4ca1bb80-01dd-11eb-8a5a-860c9d65c114.png)

### How do you know that this problem exists today? Why is this important?
Firefox Fennec had options to have dark mode, and font size, which are not present in Iceraven.

Firefox Fennec reader view:
![Reader_View_Fennec_1](https://user-images.githubusercontent.com/47936415/94465335-604d2200-01dd-11eb-89c8-996d19e57a85.png)

![Reader_View_Fennec_2](https://user-images.githubusercontent.com/47936415/94465351-66430300-01dd-11eb-9cee-99b364375670.png)

### Who will benefit from it?
Everyone that uses reader view will benefit from these options. Thanks.

**Comment by abhijitvalluri** [comment]
Wow! This behaviour is dumb of Firefox! I did not realize reader view does not have dark mode 🤦. Mozilla really half-baked this version of Firefox. 

We really do need this feature!

**Comment by mackeev** [comment]
Look for reader mode controls in the three-dot menu (while in reader mode)

**Comment by TheJags** [comment]
@mackeev thanks alot.

Here's a screen for anyone looking for reader view:

![Iceraven_Reader_View](https://user-images.githubusercontent.com/47936415/94503748-cf019e00-0224-11eb-8b22-56c6f37e3050.jpg)
