### ISSUE TITLE
Request for Save as PDF

### ISSUE THREAD

**Issue by TheJags** [fork-maintainers/iceraven-browser#176]
### What is the user problem or growth opportunity you want to see solved?
"Save as PDF' is missing from Iceraven, which was available in Firefox Fennec.

**Save as PDF in Firefox Fennec**:

![Save as PDF](https://user-images.githubusercontent.com/47936415/94467033-013cdc80-01e0-11eb-80f7-79594ccfdb8d.png)

### How do you know that this problem exists today? Why is this important?
Save as PDF is extremely useful when reading / saving long articles.

### Who will benefit from it?
Everyone that wants to save a web page will benefit from this. Thanks.

**Comment by interfect** [comment]
It would be good to be able to save a page as a PDF again.

**Comment by L31FY** [comment]
This is an accessibility feature in a way. I sometimes can't read the text but I have an app that can read the PDF to me and I can follow along with if I feel the need. It's not something that most people think of, but I can't be the only one that does this. It also has a purpose to archive things for personal use.

**Comment by cheesits456** [comment]
@L31FY what's the name of the app you use? I have dyslexia and I've been trying to find a text to speech app that's actually understandable - most are so robotic-sounding that it's easier to just read the words than it is to try to figure out what the robot is trying to say :P

**Comment by L31FY** [comment]
> @L31FY what's the name of the app you use? I have dyslexia and I've been trying to find a text to speech app that's actually understandable - most are so robotic-sounding that it's easier to just read the words than it is to try to figure out what the robot is trying to say :P

I've been using @Voice on Android. I find it less robotic.

**Comment by hbarsaiyan** [comment]
> @L31FY what's the name of the app you use? I have dyslexia and I've been trying to find a text to speech app that's actually understandable - most are so robotic-sounding that it's easier to just read the words than it is to try to figure out what the robot is trying to say :P

You can use the Google Go app if you are fine with Google apps. It has a webpage text to speech option.

![unnamed](https://user-images.githubusercontent.com/37732050/95903096-51589900-0db3-11eb-8d49-79603c89ed47.png)

**Comment by cheesits456** [comment]
Oh they _do_ have a text to speech app - My current solution has been copying the text, pasting into google translate, then having it read it in english, but the google translate voice isn't the same as the google assistant voice like i thought it would be - its robotic and tough to understand, just like all the others. Thanks @hbarsaiyan , I'll definitely check that out

**Comment by L31FY** [comment]
I don't know when this was added but an app I have used forever has made this "work" again until this is officially added back. I use Xodo PDF https://play.google.com/store/apps/details?id=com.xodo.pdf.reader and in the share menu from a page I can convert a webpage to PDF now.

**Comment by change-agent** [comment]
Would you be able to provide an update on this, @interfect? This is a major requirement in my daily workflow. Thanks in advance

**Comment by interfect** [comment]
This I think would have to come as a PR from an outside contributor. I'd ideally want it to not require forking android-components and GeckoView, but I suspect the feature isn't there in Mozilla Firefox for us to draft off of *because* something important for it was removed from GeckoView.

Someone needs to:

1. Investigate how it used to work.
2. Work out when and how it was removed.
3. Add back the menu option, the strings, maybe the translations if they can be found, and the actual backend functionality, doing the work to redesign the systems involved to account for whatever changes made the Firefox devs decide the feature wasn't worth the work to retain.

Unfortunately I'm not the right person to do this; despite being de facto project lead, my Android development abilities are quite low; all I can really do is merge stuff and maybe debug crashes. I'd like to see this feature too; if any of y'all who would like it have the time and energy to write it, @ me and I will be happy to review and merge a PR. Especially if you are willing to maintain a forked GeckoView, if one is required.

**Comment by change-agent** [comment]
@interfect Thank you for your prompt reply and all your work. For some reason, it didn't register for me that Mozilla had removed the feature as well, and it sounds like they [aren't in any hurry](https://support.mozilla.org/en-US/questions/1302353?page=3) to re-implement it. I installed Firefox 68 from APKMirror and it seems to be doing the job for my workflow, so I guess I'll stick with that in the meantime.

**Comment by lmfont** [comment]
> This I think would have to come as a PR from an outside contributor. I'd ideally want it to not require forking android-components and GeckoView, but I suspect the feature isn't there in Mozilla Firefox for us to draft off of _because_ something important for it was removed from GeckoView.

I believe that's right. There used to be an API for it, now upstream GeckoView has [an open report](https://bugzilla.mozilla.org/show_bug.cgi?id=1659819) for adding it back. So chances are you'd need to fork GeckoView.

On the other hand, there might be a pretty easy workaround. If you implement support for printing the current page using the Android printing APIs, *most* (though possibly not all) Androids have a "print to PDF" driver, so you'll get PDF printing for free. Results might not be quite as good as the browser handling PDF generation itself, but it would be a good enough workaround for most people I suspect.

Maybe print support would still require changes in GeckoView, I'm not sure.

**Comment by ghost** [comment]
In the meantime, there's a workaround:

1. Install [Print by Bill Farmer](https://f-droid.org/packages/org.billthefarmer.print) on F-Droid

2. Go to any site, and tap the Share icon; select Print by Bill Farmer afterward

3. Once you're in the Print app, tap the print icon at the top right, and now you can print your desired website as PDF

(Just another copy-paste of my same comment from other issues)

**Comment by akliuxingyuan** [comment]
completed in upstream https://github.com/mozilla-mobile/fenix/pull/27257
