### ISSUE TITLE
[Bug] Swipe Down to Refresh is interfering with Google Maps 

### ISSUE THREAD

**Issue by Raul1198** [fork-maintainers/iceraven-browser#177]
## Steps to reproduce
1. Open Google Maps
2. Zoom in to a location 
3. Now Scroll down

### Expected behavior
 Map scrolled down

### Actual behavior
Triggers Refresh

### Device information

* Android device: 10
* Fenix version: iceraven-1.1.0

**Comment by abhijitvalluri** [comment]
Known issue: #137. Current fix is to disable swipe to reload feature. It is still quite buggy.

Edit: Sorry for being so terse. To be clear, I am closing this as we already have an issue open for the same problem! :)
