### ISSUE TITLE
Move "Help" and "What's New" from browser menu into About screen

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#18]
### What is the user problem or growth opportunity you want to see solved?
Hide Help and What's New button once viewed from the 3 dot menu

### How do you know that this problem exists today? Why is this important?
It's not in the correct place it should be in about section of 
settings

### Who will benefit from it?
All the users 
UI will become less cluttered

**Comment by interfect** [comment]
I can see why one might want the menu to be different. But I'm not sure it's a good idea to start rearranging the UI, at least until there's a consistent enough supply of dev hours we can be confident the resulting Git conflicts won't be terminally numerous.

If someone makes a PR for this I can definitely be convinced, but it's not what I'd suggest needs to happen first.
