### ISSUE TITLE
Add-On Request: Bypass Paywalls Clean

### ISSUE THREAD

**Issue by L31FY** [fork-maintainers/iceraven-browser#192]
https://addons.mozilla.org/en-GB/android/addon/bypass-paywalls-clean/ is the add-on page

Tons of people use this to be able to access content and the fact it's not on mobile yet is quite disappointing.

**Comment by interfect** [comment]
This is on the list now too. I wonder why this fork (?) is on AMO when the "real" Bypass Paywalls isn't.
