### ISSUE TITLE
Add-On Request: Fontara extension

### ISSUE THREAD

**Issue by xmha97** [fork-maintainers/iceraven-browser#193]
Hello,
Please add the FontARA extension.
With FontARA Persian(Farsi, Dari, Kurdish) users can change the font on most popular sites such as Facebook, Twitter, etc.
https://addons.mozilla.org/en-US/firefox/addon/fontara-font-changer/

**Comment by ghost** [comment]
You can add your own.

**Comment by ghost** [comment]
Don't make an issue for it.

**Comment by xmha97** [comment]
> 
> 
> You can add your own.

How I can?

**Comment by ghost** [comment]
See here https://github.com/fork-maintainers/iceraven-browser/pull/50#issuecomment-685187265
