### ISSUE TITLE
[Bug] There is a white flash when the tab is brought into the foreground from either settings, extensions or downloads

### ISSUE THREAD

**Issue by jenabaivab** [fork-maintainers/iceraven-browser#194]
## Steps to reproduce

  1.  Open any tab
  2.  Go to settings, extensions, downloads, or any other app via home button
  3.  Switch back to the tab and there is a white flash
  4.  Also occurs when closing tabs from the tray

### Expected behavior

No white flash

### Actual behavior

Bright light flashes for a second

### Device information

* Android device: 10
* Fenix version: 2015766939

**Comment by jenabaivab** [comment]
https://github.com/mozilla-mobile/fenix/issues/15236

You can find the issue I submitted to firefox Devs here. You can see the GIF there. It also happens when I close tabs from the tray since the tab is again getting brought into the foreground

**Comment by mackeev** [comment]
The origin of this issue is the same as in https://github.com/mozilla-mobile/fenix/issues/14801
They assigned it S2, which means they think this is not the most crucial issue (I, for one, beg to differ), which means they will take their time with it.
I doubt it could be resolved any sooner in a fork. But I'd love to be mistaken.

**Comment by jenabaivab** [comment]
@mackeev as much as I hope this can be fixed, FF nightly in general has so many things to be fixed. You can see my issue on there isn't even acknowledged. Whenever I say anything bad about FF development on Reddit, people will always jump me saying that you should report issues you find to get them fixed. Well I did. What now.

**Comment by mackeev** [comment]
Your issue is (probably) fixed in the latest Nightly.
But... they have introduced a new one: white splash while entering Reader View

**Comment by jenabaivab** [comment]
@mackeev you beautiful man! 
Thank you so much for the heads-up. I had uninstalled Firefox and I checked for this based on your comment. It is fixed indeed. Hopefully this gets pushed to ice-raven.

**Comment by jenabaivab** [comment]
@interfect 
This bug has been fixed in the latest nightly. Any way this can be included in the next iceraven update please?
