### ISSUE TITLE
App Icon for launcher activity and status bar

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#197]
![IceRaven 2](https://user-images.githubusercontent.com/26594953/94931663-a4923800-04e5-11eb-8b5f-4d958edf3df4.png)
![IceRaven 1_1](https://user-images.githubusercontent.com/26594953/94931668-a65bfb80-04e5-11eb-8f0f-b2b88eca76d2.png)
The one for status bar is modified a little reduce messiness.

**Comment by ghost** [comment]
SVG for the above two PNGs
https://drive.google.com/drive/folders/1jzpCTgDSmmyq4FEDUIGT3Ds47aPP9Ttz?usp=sharing

**Comment by abhijitvalluri** [comment]
That looks more like some kind of a bear than a raven I feel

**Comment by hbarsaiyan** [comment]
> That looks more like some kind of a bear than a raven I feel

Still better than my first attempt xD

**Comment by abhijitvalluri** [comment]
We may consider this image as part of round two of voting. I am thrilled we are getting a lot of submissions. I thought we will have to stick to some crude drawing done in paint as the logo! 😆

**Comment by Poopooracoocoo** [comment]
This is incredible work! It'd look less like a "bear" if the head were a bit bigger/rounder and perhaps if the beak stood out more in the silhouette by shaving off a bit of the neck.

**Comment by ghost** [comment]
Sure. I will modify it a bit

**Comment by hbarsaiyan** [comment]
![red](https://user-images.githubusercontent.com/37732050/96099837-51f74980-0ef1-11eb-83f0-487b591911b5.png)
![skyblue](https://user-images.githubusercontent.com/37732050/96112870-ecab5480-0f00-11eb-9641-285b7d58157a.png)

This is a logo I created some time ago but since its not of use now i thought of posting here

**Comment by abhijitvalluri** [comment]
Very cool! Was this for a different project or this project?

**Comment by hbarsaiyan** [comment]
> Very cool! Was this for a different project or this project?

This project lol. I think the final poll had started by then so i did not complete it that time. Got some time to complete it today.

**Comment by hbarsaiyan** [comment]
As for the  icon chosen in the poll the svg isn't importing correctly in my designer so i can't edit it unfortunately.
