### ISSUE TITLE
Re-add the fixed-position bottom address bar from Firefox Preview

### ISSUE THREAD

**Issue by ale82to** [fork-maintainers/iceraven-browser#20]
Firefox preview had fixed bottom toolbar is it possible to get an option to get fixed bottom bar again?
thanks.

**Comment by interfect** [comment]
Possibly. Any idea how the fixed bottom bar was implemented, what Mozilla called it internally, or when in the Git history it went away? If it's just a flag we can just flip it, or maybe add a setting that flips it. If it's a bunch of code they took out it's harder to bring back; someone has to write the code.

**Comment by ale82to** [comment]
it was fixed until Firefox preview 5.2 for sure

**Comment by ale82to** [comment]
another bad change they are bringing to nighlty is the ability to have just 8 top sites on honepage if need I can provide latest nighlty apk which allow as many top sites as we like.

**Comment by interfect** [comment]
Really what we have to do is find the commits in https://github.com/mozilla-mobile/fenix/commits/master that make the offending changes, and undo them. It might be easiest to consult or search the list of closed pull requests at https://github.com/mozilla-mobile/fenix/pulls?q=is%3Apr+is%3Aclosed

**Comment by dnebdal** [comment]
It seems to have been `FeatureFlags.dynamicBottomToolbar` back when they were experimenting with it, at least?
See https://github.com/mozilla-mobile/fenix/pull/8233 .

**Comment by abhijitvalluri** [comment]
Isn't this feature currently available in Fenix and our fork? We can choose bottom toolbar and make it either fixed or disappear when scrolling, no? 

I am closing this as the feature seems to exist. If I misunderstood and you are talking about something else please feel free to re-open or comment.
