### ISSUE TITLE
search engine disappeared [webcontent]

### ISSUE THREAD

**Issue by Sforg26** [fork-maintainers/iceraven-browser#203]
Hello, thank you for your work this project is really cool!
 I'm on android 10. I have started using iceraven with the 1.1 version and I set my search engines as usual. Everything works fine and the new versions also solve some bug. 
The only problem for me is that all of the search engines that i save disappeared from the list, but when i try to put them again, the app told me that a search engine with that name already exist.
Now i'm on 1.2.1 version and the problem still persist.
There's anything I can do to solve the issue?
Thanks for your attention
best regards

### Device information

* Android device: ?
* Fenix version: ?

**Comment by ghost** [comment]
Duplicate of https://github.com/fork-maintainers/iceraven-browser/issues/166

**Comment by interfect** [comment]
Yes, this issue is already reported as #166, so I'm going to close this thread in favor of that one. As for a workaround, there's been some suggestion that killing the app and restarting it a few times could eventually make the newly added search engines show up.
