### ISSUE TITLE
Let me close/tag issues on here

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#204]
I am on here enough I could tag and/or close issues that have a duplicate or need a triage, and I could perhaps even try and duplicate the issues as well. Either way, lots of duplicate issues that I would be happy to close and/or test and.or help the person who made the issue without taking up space as an actual issue.

**Comment by interfect** [comment]
Sounds good to me.

@abhijitvalluri I'm going to add @johnhandcockandstuff with "Triage" level access. That ought to allow labeling and manipulating issues.

**Comment by johnhandcockandstuff** [comment]
Doesn't seem that I can yet. In any case, if it's gonna be a hassle don't worry about it.
