### ISSUE TITLE
Reloading tabs 

### ISSUE THREAD

**Issue by dfrost16** [fork-maintainers/iceraven-browser#206]
Tabs keep reloading frequently. 
Can't keep more than 3 tabs open
Idk if it has something to do about addon that I use.
But it should be able to keep atleast 3 tabs

**Comment by em108** [comment]
I had this problem till I found a switch was added under customize: "Suspend tabs to avoid being killed for memory" (enabled by default)
https://github.com/fork-maintainers/iceraven-browser/issues/115

Turn it off and you can load as many tabs as you want without being killed in the background

**Comment by ghost** [comment]
Which addons are you using? Also, try disabling the _suspend tabs to avoid being killed for memory_ option at the bottom of the _Customize_ tab in settings, and see if that changes anything.

**Comment by L31FY** [comment]
I'm having the reloading tabs and I have that setting in question turned off already.

**Comment by vehosah** [comment]
> I'm having the reloading tabs and I have that setting in question turned off already.

I'm also the setting off, but the reload issue is getting worse

**Comment by vehosah** [comment]
> Which addons are you using? Also, try disabling the _suspend tabs to avoid being killed for memory_ option at the bottom of the _Customize_ tab in settings, and see if that changes anything.

I don't have addons and I have this setting off, but the problem is worse

**Comment by akliuxingyuan** [comment]
does it still happen now?
