### ISSUE TITLE
[Bug] Android 10 Text 

### ISSUE THREAD

**Issue by Raul1198** [fork-maintainers/iceraven-browser#207]
## Steps to reproduce
1. Open any website that have a text filed to write into. I'm taking GitHub Issue
2. Type something
3. Try to scrub between the texts

### Expected behavior

While scrubbing between the text there should be magnifying lense which shows the cursors position, like here in the image 
![Screenshot_20201004-214636461](https://user-images.githubusercontent.com/29801315/95020986-efe64b00-068b-11eb-9482-c55734252cd9.jpg)

### Actual behavior

No lense is shown while scrubbing between the text . only the address bar is having the lense 

### Device information

* Android device: 10
* Fenix version: 1.2.1

**Comment by ghost** [comment]
I'm getting the magnifying glass, but I am using AOSP keyboard myself. Which keyboard are you using? Could you test with just the stock android keyboard, if possible?

**Comment by Raul1198** [comment]
> I'm getting the magnifying glass, but I am using AOSP keyboard myself. Which keyboard are you using? Could you test with just the stock android keyboard, if possible?

I tried with Gboard , with AOSP keyboard it is same 
![Screenshot_20201005-080127325](https://user-images.githubusercontent.com/29801315/95034937-02d73a80-06e1-11eb-8ede-e271f7db5024.jpg)

**Comment by ghost** [comment]
I have a feeling it most likely isn't a browser issue, but I could be wrong. Does this feature work on other browsers and/or version of Firefox?

**Comment by Raul1198** [comment]
> I have a feeling it most likely isn't a browser issue, but I could be wrong. Does this feature work on other browsers and/or version of Firefox?

I think this is Firefox issue as I tried with Firefox  Nightly and it was not working. Tried with Kiwi too and it was working
