### ISSUE TITLE
[Bug] Twitter Issues and a Potential Solution

### ISSUE THREAD

**Issue by CharmCityCrab** [fork-maintainers/iceraven-browser#209]
Twitter has not been working, or has been working inconsistently, for some Iceraven users lately.  This is an upstream bug that also effects Firefox.

An example of how this works is that a friend has text messaged me a few Twitter links on my phone, and when my default browser (Iceraven) attempts to load them, it produces an error message instead of displaying the pages.

Anyhow, Mozilla has published a work-around for Firefox that I would imagine probably also works for Iceraven and involves unregistering service workers associated with Twitter ( https://support.mozilla.org/en-US/kb/twitter-isnt-working-firefox and/or https://www.bleepingcomputer.com/news/technology/mozilla-shares-fix-for-twitter-not-working-on-firefox/ for more info on the work-around).

Since this issue is clearly with upstream, Iceraven should pick up the permanent fix when and if it comes through it's normal updates from upstream.  So, it would likely be a waste of developer time to have them focus on a permanent fix to something others are already working on upstream (I have a feeling that a site like Twitter is likely going to be a high priority for them.).

So, why bring it up?

Well, in theory, Iceraven could put out a quick patch that automatically clears service workers for Twitter.  Depending on whether or not the service workers need to reset just once for each install or on a recurring basis to get the work-around to work, the patch could potentially be written to repeat the process periodically if necessary.  It'd be good for end users and a kind of coup to get the issue "fixed" before our fellow Fenix-based browsers.

Then, when upstream patches the bug in a more efficient way, we could adopt that permanent fix and get rid of our potential temporary fix.

Obviously, the temporary fix is only worth doing as a browser update if it can be written easily and a browser update published quickly.  If it's a pain to code, it's not worth the resources since a fix is coming from the outside anyway, and of course because it's just a bridge to when the permanent fix arrives, it wouldn't make since if the next browser update is a week away or something, whereas it would make sense if it was hours or perhaps a day away.

One unknown on my end is the precise nature of service workers and whether or not they are only placed by and work for the website, in which case there should be no qualms about unregistering them, or whether they can sometimes be placed by the browser and/or extensions, in which case we would want to be careful about publishing a hot fix that could mess with what the end user has set up, directly or indirectly, and expects (That scenario would mean we'd probably want to steer clear and just point people towards the self-help fix until a permanent fix comes from upstream).

**Comment by interfect** [comment]
This might require digging into android-components to make work.

**Comment by CharmCityCrab** [comment]
This is fixed in Firefox 81.0.2 for desktop, released August 13 (Basically today, I'm only an hour or so into the 14th).  I can confirm that whatever that fix is works for me on desktop.

I don't see a set of equivalent Firefox for Android release notes on the Mozilla website, and I don't have FFA installed to check for myself, but IR devs may want to watch for the code upstream and consider expediting it even if it means an "out of band" (as Microsoft would call it) release just to do that (That fix seems to be all the latest desktop Firefox release consists of.) rather than merging it routinely a bit later and waiting to get everything that is hoped for in the next release ready to send out all together.

Twitter isn't a big priority for me personally, but it's one of the more popular sites on the Internet in general, so it's one of those "good of the browser" type of things to try to minimize the time it isn't working properly.  Plenty of good workarounds, and patience is always a good workaround, but a casual user giving the browser a tryout for a session isn't going to dig that deeply if Twitter is a key site for them (And for many people, especially casual users, it is).
