### ISSUE TITLE
[Bug] Bitwarden android app not working as intended 

### ISSUE THREAD

**Issue by ajshovon** [fork-maintainers/iceraven-browser#210]
## Steps to reproduce

- Open Iceraven
- Goto any site you have saved password in Bitwarden
- Click bitwarden popup

### Expected behavior

Should Load password for the website user browsing

### Actual behavior

Loads password for `io.github.forkmaintainers.iceraven`

### Device information

* Android device: 10
* Iceraven version: 1.2.1

**Comment by CharmCityCrab** [comment]
Just to make sure we're clear on the nature of the issue:

When it is defaulting to io.github.forkmaintainers.iceraven, is BitWarden loading your personal GitHub password, or an owner/developer/maintainer password of some sort?

Was BitWarden previously working for you on Iceraven?  If so, when did the problems start?  Do you remember anything changing around that time, like upgrading the browser or the extension?

Is there anyone else here reading this using this extension in conjunction with Iceraven who's having the same problem and wants to chime in?  Anyone running them together and *not* experiencing this problem?

Is everyone who is experiencing the problem downloading the program from the default list Iceraven provides?  Is everyone not experiencing the problem creating their own list?  I realize I just stepped a bit ahead and make some assumptions, but if people can add how they are accessing the extension to their responses, that may help the developers figure out what is going on a bit more quickly.

**Comment by ajshovon** [comment]
> Just to make sure we're clear on the nature of the issue:
> 
> When it is defaulting to io.github.forkmaintainers.iceraven, is BitWarden loading your personal GitHub password, or an owner/developer/maintainer password of some sort?
> 
> Was BitWarden previously working for you on Iceraven? If so, when did the problems start? Do you remember anything changing around that time, like upgrading the browser or the extension?
> 
> Is there anyone else here reading this using this extension in conjunction with Iceraven who's having the same problem and wants to chime in? Anyone running them together and _not_ experiencing this problem?
> 
> Is everyone who is experiencing the problem downloading the program from the default list Iceraven provides? Is everyone not experiencing the problem creating their own list? I realize I just stepped a bit ahead and make some assumptions, but if people can add how they are accessing the extension to their responses, that may help the developers figure out what is going on a bit more quickly.

- Bitwarden loads password for `io.github.forkmaintainers.iceraven` url always, as it finds match with github, so loads ids for github

- I have been using Iceraven since rebranding and it never worked with Iceraven. It works on Firefox nightly from play store

**Comment by ghost** [comment]
Can confirm same bug on my install. Using Bitwarden app not extension.

**Comment by CrazyGunman2C4U** [comment]
This is not an issue with Iceraven, but **a security feature of Bitwarden**. When using "insecure browsers", the package name is served instead of the url.

I noticed this problem with the Bitwarden app already in the days of Iceweasel.

In the community forum the following feature request was posted: https://community.bitwarden.com/t/add-iceweasel-to-androids-trusted-browsers-list/13951

After a quick search, I've found the following issue: https://github.com/bitwarden/mobile/issues/392 which led me to https://github.com/bitwarden/mobile/blob/master/src/Android/Autofill/AutofillHelpers.cs

And look at that! "Add support for Iceraven browser"
https://github.com/bitwarden/mobile/issues/1105
https://github.com/bitwarden/mobile/pull/1106
https://github.com/bitwarden/mobile/commit/8f533bc5764a38b25ad5df318ebbabcf338e22d2

**The problem is already solved in the source code.** This "issue" can probably be marked as fixed.

Note: This is unrelated to the extension.

**Comment by ajshovon** [comment]
> This is not an issue with Iceraven, but **a security feature of Bitwarden**. When using "insecure browsers", the package name is served instead of the url.
> 
> I noticed this problem with the Bitwarden app already in the days of Iceweasel.
> 
> In the community forum the following feature request was posted: https://community.bitwarden.com/t/add-iceweasel-to-androids-trusted-browsers-list/13951
> 
> After a quick search, I've found the following issue: [bitwarden/mobile#392](https://github.com/bitwarden/mobile/issues/392) which led me to https://github.com/bitwarden/mobile/blob/master/src/Android/Autofill/AutofillHelpers.cs
> 
> And look at that! "Add support for Iceraven browser"
> [bitwarden/mobile#1105](https://github.com/bitwarden/mobile/issues/1105)
> [bitwarden/mobile#1106](https://github.com/bitwarden/mobile/pull/1106)
> [bitwarden/mobile@8f533bc](https://github.com/bitwarden/mobile/commit/8f533bc5764a38b25ad5df318ebbabcf338e22d2)
> 
> **The problem is already solved in the source code.** This "issue" can probably be marked as fixed.
> 
> Note: This is unrelated to the extension.

Thank you for the information. Closing the issue.
