### ISSUE TITLE
Reverse Swipe Gesture Direction while changing tabs

### ISSUE THREAD

**Issue by jenabaivab** [fork-maintainers/iceraven-browser#213]
### What is the user problem or growth opportunity you want to see solved?
When we reverse the order of tabs in tab tray to new tabs at bottom, the swipe gestures can also change so that we swipe right instead of left for the new tab.

### How do you know that this problem exists today? Why is this important?
The swipe gesture in general is reverse of every other browser which makes using multiple browsers a hassle.

### Who will benefit from it?
Everyone who relies on quick switching of tabs via bottom bar and is already accustomed to other browsers gestures.

**Comment by interfect** [comment]
I'm not quite sure why we would want the left-right direction to change with the up-down direction, but it makes sense we would want it to be configurable.

**Comment by jenabaivab** [comment]
@interfect I apologize for bad wording, I meant to reverse tbe direction, not make it up/down.
For example, in the tab tray, we already have the option of keeping new tabs in the bottom, and older tabs at top. When this option is enabled, we should swipe from right->left to go to the new tab and left->right to go to older tab. This is normal in other browsers like Chrome, Vivaldi, Brave etc.

Currently, even though the tab tray can reverse new tab creation, the swipe still follows the traditional direction i.e. left-> right for new tab which is a little inconsistent if tab tray order is reversed. 

I believe I can't explain it properly. Should I make a GIF to highlight the issue?

**Comment by orbitneon** [comment]
I was only here to post that. I tried my best to adapt that "tab swiping direction" but it's incredibly annoying. I swear even mozilla devs don't use it, they just implemented it to showcase new features of fenix when pathetically making it opposite directional of chromium.

**Comment by akliuxingyuan** [comment]
> When we reverse the order of tabs in tab tray to new tabs at bottom

I think we don't have this feature anymore
