### ISSUE TITLE
[Bug] Bitwarden App Autofill wrong url detection

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#214]
## Steps to reproduce
Open any website for which you saved an password in your Bitwarden app vault.
### Expected behavior
The bitwarden APP autofill only detects the package name of the iceraven browser i.e io.github.forkmaintainers.icerave not currently opened website url detection for perfect match.
### Actual behavior
The actual behavior of autofill must show the currently opened tab url instead of showing app package name matching. Fennec Fdroid newer version detect url autofills without any issues.
### Device information
Realme 5 pro, Derpfest Custom ROM
* Android device: 10
* Fenix version: iceraven-1.2.1 (Build #2015767435)

**Comment by neekless** [comment]
This needs to be fixed on bitwarden's side. Bitwarden has a list of browsers to prevent such behavior including Fennec Fdroid which explains why Fennec Fdroid works.
https://github.com/bitwarden/mobile/blob/8f533bc5764a38b25ad5df318ebbabcf338e22d2/src/Android/Autofill/AutofillHelpers.cs#L89

**Comment by neekless** [comment]
This needs to be fixed by bitwarden, which they did 7 days ago https://github.com/bitwarden/mobile/commit/8f533bc5764a38b25ad5df318ebbabcf338e22d2 but they have not released an update.

**Comment by ghost** [comment]
@neekless 
Thanks for info. I hope upcoming newer release of Bitwarden fixes this issue.

**Comment by interfect** [comment]
Since this is fixed on the Bitwaeden side (pending a release), I am going to close this.
