### ISSUE TITLE
[Bug] App keeps running in background and restarts itself if stopped

### ISSUE THREAD

**Issue by chaoskagami** [fork-maintainers/iceraven-browser#215]
## Steps to reproduce

Run browser. Swipe browser up. Go to settings, 'Force Stop' browser. Go back, go back in the settings page for it, observe that 'Force Stop' has enabled again. Check development settings and observe that the application is still consuming RAM and has begun to run again for some reason.

### Expected behavior

When I kill the application with Force Stop or swiping it, that means stop running. Period. It should gracefully remove itself from memory and stop consuming CPU time.

### Actual behavior

The application quickly restarts itself in the background and continues consuming about 200M of RAM and using battery on what probably amounts to an idle loop.

This is even worse if there's a crash, since it gets stuck in a loop of crashing and restarting itself only to crash again five seconds later even without the browser open, which makes it very difficult to do anything to remedy the situation without adb.

### Device information

* Android device: 9, March 2020 security patchlevel (Razer Phone 2)
* Fenix version: The latest one off github

**Comment by chaoskagami** [comment]
Actually, this is really strange. I wiped the app and reinstalled it and this behavior doesn't happen now...?

The profile was basically fresh - I added uBlock Origin, Violentmonkey and Decentraleyes. I imported a Violentmonkey export zip from my desktop. That's it.

After doing the same thing, I'm unable to reproduce it.

**Comment by interfect** [comment]
I know the app contains a component called "the service", but I don't entirely know what it does or why it would be scheduling itself to run after you kill it.

The different behavior between an old and fresh install makes me suspect maybe it has something to do with service workers. Maybe the browser starts up to do something with them? If we had working web push it could be push notifications coming in, but we don't, so it can't be.

**Comment by interfect** [comment]
We can let this sit for a while, and close it if nobody can reproduce it.

**Comment by Qwerty-Space** [comment]
My app also keeps restarting in the background, seemingly at random.

**Comment by akliuxingyuan** [comment]
@ChowMein47 please share your finding here

**Comment by richie3011** [comment]
> @ChowMein47 please share your finding here

@akliuxingyuan I record the video to reproduce this issue. I upload this video on YouTube because I can't upload it here https://youtube.com/shorts/Vowc8Sb5S4o?si=6bNe6RsXNX9F4Dr3

**Comment by akliuxingyuan** [comment]
@ChowMein47 
https://github.com/fork-maintainers/iceraven-browser/blob/3e84868ba1c663be00d0368181f066004d8f6641/app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteAndQuit.kt#L52C1-L52C39
Press Quit button finally call `finishAndRemoveTask()`, which finishes all activities in this task and removes it from the recent tasks list. we are not changed anything here.
test with firefox official, it's same behavior, if you want close completely, try force close in System Settings App.

**Comment by akliuxingyuan** [comment]
if anyone can reproduce the restarting problem, reopen this issue

**Comment by richie3011** [comment]
@akliuxingyuan I already try to reproduce this on Firerox and Fennec F droid, there is no issue. This issue only present in Iceraven browser. I wish someone can reproduce this as well

**Comment by richie3011** [comment]
@akliuxingyuan sorry if i am bothering you. Do you have any idea to stop Iceraven running in background? Maybe you have a way to setting in `about:config` . I am using latest version 121.1.1 the bug still exist :(
