### ISSUE TITLE
Higher refresh rates on OnePlus devices

### ISSUE THREAD

**Issue by lapinsami** [fork-maintainers/iceraven-browser#218]
I believe OnePlus has a whitelist for apps that use SurfaceView or TextureView so they can run at 90 or 120 Hz. Firefox Beta, Firefox Nightly and Iceraven are not on the list. Only stable Firefox runs at higher refresh rates unless you use something like AutoHz.

Is there a way around this or is Iceraven forever stuck at 60 Hz?

https://bugzilla.mozilla.org/show_bug.cgi?id=1662380

**Comment by interfect** [comment]
We could make builds that fake the AppID of things on Oneplus's list, but if it's really just a list on their side, they have to put us on it.

There might be a "turn on 90hz" call we can make. How does AutoHz do it?

**Comment by lapinsami** [comment]
> How does AutoHz do it?

AutoHz switches the display's refresh rate depending on what app you have on the screen (I think). It needs `android.permission.WRITE_SECURE_SETTINGS` to do that, so you need a rooted device or adb to set it up.

> We could make builds that fake the AppID of things on Oneplus's list

It seems to be the only way, unless someone here knows someone who knows someone at OnePlus.

**Comment by lapinsami** [comment]
Using Firefox's appid `org.mozilla.firefox` seems to work. I edited the build.gradle file and built the .apk. The only downside is that I can't have both Firefox and Iceraven installed at the same time. Probably should have chosen a different appid.

**Comment by hbarsaiyan** [comment]
It is not an issue related to the browser. It's OnePlus who need to fix their shit. They use a whitelist for apps that can use higher refresh rates. So the only permanent solution is that oneplus adds iceraven to their whitelist.

**Comment by akliuxingyuan** [comment]
ColorOS seems to already support custom application refresh rates, not only whitelist.
