### ISSUE TITLE
[Bug]AUTOMATIC FONT SIZING option missing 

### ISSUE THREAD

**Issue by ale82to** [fork-maintainers/iceraven-browser#220]
in version 1.3 automatic font sizing in missing in setting even using font size to 100‰ general font size in pagers are way bigger any quick fix for this?

**Comment by interfect** [comment]
@ale82to Looks like you reported this upstream as https://github.com/mozilla-mobile/fenix/issues/15910

I think we could probably just revert https://github.com/mozilla-mobile/fenix/commit/881e3d6ccde19fc5c52e07ee097b703b41b3f950 to get the setting back, but I haven't dug in enough to figure out if that's actually a good idea.
