### ISSUE TITLE
[Bug] Default Private Browsing Explanation Links to Firefox Site

### ISSUE THREAD

**Issue by CharmCityCrab** [fork-maintainers/iceraven-browser#221]
## Steps to reproduce

Click on the private browsing icon and open a tab.

### Expected behavior

A purple screen with a brief explanation of private browsing in Iceraven will appear underneath the Iceraven name and logo, possibly but not necessarily including a link to further information about private browsing that is either generalized or which applies specifically to Iceraven.

### Actual behavior

All of the above displays as described with proper branding, with one exception.  

The link underneath the description entitled "Common Myths About Private Browsing" leads to a Mozilla operated webpage that specifically refers to the browser as Firefox.

My advice would be to just ditch the link and keep the rest as-is.  That seems like the easiest fix.  The description in the tab itself above the link seems sufficient and Iceraven doesn't really have a website to host an equivalent document to the link.

Another alternative would be to include more information below the initial paragraph in place of the link.

A third option would be to link to a generalized document or article with a similar topic that is not specific to any individual browser, perhaps from the EFF or some similar organization, rather than to the one that is specifically about Firefox.

I realize that in this case everything that applies to Firefox basically applies to Iceraven, but there will be users who don't know that, and it may create the impression in a few confused folks that Iceraven is the formal mobile version of Firefox.  Getting these references right is actually something that I would imagine is not only good for Iceraven, but also good for Firefox.  It's in the interests of both parties for everything to be clear branding wise.

* Fenix version: 

1.3.0

**Comment by interfect** [comment]
It looks like both the link's presence and where it takes you are under test, so if we touch them we'll have to touch the tests as well.

The clicking test is here: https://github.com/fork-maintainers/iceraven-browser/blob/c769d5a19e7c770535222e0d2a6cff5aff742c89/app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/PrivateBrowsingDescriptionViewHolderTest.kt#L32-L38

The actual element is here:

https://github.com/fork-maintainers/iceraven-browser/blob/c769d5a19e7c770535222e0d2a6cff5aff742c89/app/src/main/res/layout/private_browsing_description.xml#L29-L42
