### ISSUE TITLE
[Bug] Legacy icon still uses old programmer art

### ISSUE THREAD

**Issue by Poopooracoocoo** [fork-maintainers/iceraven-browser#223]
## Steps to reproduce
If you're on Android 8.0+, install a launcher like Nova and switch to legacy icons

### Expected behavior
I'd expect the new icon to be used but without the background

### Actual behavior
The old icon is used

### Device information

* Android device: ?
* Fenix version: ?

**Comment by abhijitvalluri** [comment]
That is proper legacy icon! 😄 Thanks for the catch. We need to fix the bug.
