### ISSUE TITLE
Easier way / help to figure out which APK to use

### ISSUE THREAD

**Issue by maxstarkenburg** [fork-maintainers/iceraven-browser#226]
First off, bless y'all for this fork, which returns several of the settings and UI (especially as related to tabs) I used to really love about Android FF that ... lord knows why they seemed intent on removing/disabling with Fenix. I just found this project today while looking for ways to get back some of the behavior that even Nightly seems to have removed (or deeply hidden).

### What is the user problem or growth opportunity you want to see solved?

I wasn't sure which of the 4 .apk files to download. And it wasn't easy/straightforward to find. I did poke around in my phone's settings info, but didn't find anything relevant. I was hoping/expecting there might be some helpful info in this regard in the README (presumably under the "Installation" heading). I eventually used a third-party app (Droid Hardware Info), since [this How-To Geek article](https://www.howtogeek.com/339665/how-to-find-your-android-devices-info-for-correct-apk-downloads/) recommended it, and I've historically found decently useful/trustworthy info on that site (whereas most of my other search results I found when Duckduckgoing "arm64 armeabi x86 x86_64" were either unhelpful or felt like seedy advertising).

### How do you know that this problem exists today? Why is this important?

I don't frequently download/install apps outside the Play Store (and indeed I looked for Iceraven there too, but now see that #71 exists). I assume the Play Store probably does something to know or figure out whether my phone is arm64, armeabi, x86, or x86_64, so that I don't have to think about it, because I certainly have no clue what processor/CPU/whatever my phone has. I would imagine some guidance might help others. Also, adding a little more text to the "Installation" section of the README might help the "Building" heading look less like a sub-section of "Installation", as I initially got scared that installing Iceraven might require something like trying to run ADB through a Linux VM or something! (Though of course other edits, like moving the hammer icon to the right of the text, and/or giving "Installation" its own icon, and/or re-titling "Building" to something else like "Or build from source code" or whatever would likely help avoid that ambiguity more.) 

### Who will benefit from it?

Other n00bies like me. Folks who aren't so determined as I was to get back their preferred browser functionality that they would spend all the time it took me to figure things out. Granted, once #71 is done, perhaps this whole ticket will be rather moot.

**Comment by interfect** [comment]
OK, I've written some new text for the README that should address this.
