### ISSUE TITLE
Add-on Req: Don't Track Me Google

### ISSUE THREAD

**Issue by pidus** [fork-maintainers/iceraven-browser#227]
AMO: https://addons.mozilla.org/en-US/firefox/addon/dont-track-me-google1

It's the only one I found to work properly on Android.

**Comment by interfect** [comment]
OK, this is now on the list.

**Comment by pidus** [comment]
> OK, this is now on the list.

Tried searching. Can't find it in list of available add-ons. Will it take some time?
