### ISSUE TITLE
Block Web Fonts

### ISSUE THREAD

**Issue by pidus** [fork-maintainers/iceraven-browser#229]
### What is the user problem or growth opportunity you want to see solved?
User wants to disable web fonts. 
### How do you know that this problem exists today? Why is this important?
There's no GUI option to disable web fonts. 
### Who will benefit from it?
Anyone who don't want to load web fonts. 

The backend of this feature exists. Go to: http://kb.mozillazine.org/About:config_entries search for: `browser. display. use_document_fonts` In Fennec, there's a toggle for this. But not present in Fenix. Consider enabling this. Presently, it can be enable through `about:config`. But, a GUI option would be more user friendly.

**Comment by interfect** [comment]
This is a good idea, but we already have it tracked as #51, so I am going to close this copy.
