### ISSUE TITLE
Recruiting Maintainers

### ISSUE THREAD

**Issue by interfect** [fork-maintainers/iceraven-browser#23]
I was recently away for a few days and nobody liked it.

Who wants to volunteer to triage issues, merge PRs, pull in upstream changes, tag and build releases, and generally work on the project? If you solemnly swear not to hack everybody's phones, show a willingness to follow the code of conduct/participation guidelines, and want to help, I can add you to a Github organization that can own the repo, so you can do all those things.

If you want to sign up, please comment below.

**Comment by Dakkaron** [comment]
I am a developer and just managed to get this setup a d built. I cannot promise to merge pull requests daily, but for the time being, I'd like to lend a hand.
Keeping up with a huge project like Firefox is a boatload of work, so don't expect daily updates. But if we can manage a weekly build, that wouldn't be half bad.

**Comment by interfect** [comment]
OK, @Dakkaron, I think you will be on the list.

@abhijitvalluri, you seem to be a top contributor. Do you want to be promoted and/or volunteered?

**Comment by abhijitvalluri** [comment]
Hey, @interfect, sure I suppose you can volunteer me to be a maintainer! :) I will try to help monitor any PRs or pull in upstream code.

**Comment by interfect** [comment]
OK, I've set up an organization, added y'all and moved the repo over to it. That ought to give you access when you accept the invites.

**Comment by abhijitvalluri** [comment]
I think you also need to add us to this repo as collaborators or something so that we can review and merge PRs, close issues/add tags to issues, pull upstream and merge to fork, etc. Without that this repo is read only for me and I still need your approval for various things.
