### ISSUE TITLE
Stop following Mozilla's master branch and start following their soon-to-exist releases/v83.0.0 branch instead

### ISSUE THREAD

**Issue by interfect** [fork-maintainers/iceraven-browser#230]
One of the problems I am encountering trying to get the F-Droid build to work for #26 is that our `fork` branch depends on a bunch of not-really-tagged versions of Mozilla projects like Android Components:

https://github.com/fork-maintainers/iceraven-browser/blob/c769d5a19e7c770535222e0d2a6cff5aff742c89/buildSrc/src/main/java/AndroidComponents.kt#L5-L6

There is no `63.0.20201010143128` tag of Android Components that you can go check out and build. That version is published on Maven, so it can be fetched as part of a normal Iceraven build, but I think it corresponds to "whatever Mozilla's build bot was looking at on the master branch at on October 10, 2020 at 2:31 PM Buildbot Standard Time". For F-Droid builds we need to be able to specify the exact source versions of all our dependencies and transitive dependencies that we're compatible with, and these dated versions won't work.

Compare that to what's present on Mozilla's `releases/v82.0.0` branch:

https://github.com/mozilla-mobile/fenix/blob/releases/v82.0.0/buildSrc/src/main/java/AndroidComponents.kt#L5-L6

That points to `60.0.5`, which is a real tagged version that I can plug into an F-Droid build YAML.

According to [Mozilla's release calendar](https://wiki.mozilla.org/Release_Management/Calendar), Firefox 82 releases tomorrow, October 20. I anticipate that shortly after that, a `releases/v83.0.0` branch will diverge from Mozilla's master branch, and on that branch all the dated versions of upstream dependencies will soon (certainly before the Firefox 83 release on November 17) be replaced with real versions, while Firefox for Android 83 goes through the beta process.

I think we should track that v83.0.0 branch, so that we can depend on versions of the dependencies that are easier to procure in an F-Droid build. We'd also stop getting so many new bugs introduced by Mozilla, and instead start getting only their uplifted bugfixes.

Now, moving from v83.0.0 (or its patch descendant) to **v84.0.0** when the time comes might require some fancy Git surgery, as those uplifted bugfixes are cherry-picked commits from the main branch that will have duplicate copies in the `v84.0.0` branch. We might end up coming back to when we merged in the start of v83, doing a rebase to grab all our commits and drop all of Mozilla's commits, and then merging the result of that with the start of v84. Or we might just end up accumulating some duplicate commits for everything that got uplifted. But I believe that the cost in Git fiddliness will be worth the improved feasibility of maintaining an F-Droid build.

@abhijitvalluri What do you think of this plan?

**Comment by interfect** [comment]
I synced us up with v83.0.0.

**Comment by abhijitvalluri** [comment]
Yay! Great job, thank you for the effort! I'll try this out.
