### ISSUE TITLE
Addons request

### ISSUE THREAD

**Issue by ivysrono** [fork-maintainers/iceraven-browser#235]
I write some addons for myself: https://github.com/ivysrono/iWebExtension

https://addons.mozilla.org/android/addon/anti-anti-leech/
https://addons.mozilla.org/android/addon/pure-sololearn/
https://addons.mozilla.org/android/addon/replace-uris/
https://addons.mozilla.org/android/addon/upgrademixedcontentbyblacklist/

Please add them.

**Comment by interfect** [comment]
OK, these are on the list now.

**Comment by ivysrono** [comment]
@interfect I can't get the last one? https://addons.mozilla.org/android/addon/upgrademixedcontentbyblacklist/

**Comment by interfect** [comment]
The list in the app only updates when the cache expires (every couple days or so, I think). You can also clear the app data to force an update, but that clears the app data.
