### ISSUE TITLE
[Bug] youtube.com cannot select video quality

### ISSUE THREAD

**Issue by xPhoenisX** [fork-maintainers/iceraven-browser#237]
## Steps to reproduce
Go to YouTube.com and select a video to play then click on the cogwheel to select video quality
### Expected behavior
should be able to select video quality
### Actual behavior
the webpage reloads
### Device information

* Android device: Android 10
* Fenix version: 1.3.0

**Comment by aquaspy** [comment]
I can change quality here with no problems. Maybe try to unninstall some extension?

**Comment by ghost** [comment]
I was facing this issue but then I removed all extensions that were supposed to enhance youtube functionality and now it works
