### ISSUE TITLE
Bottom Toolbar hides comment menu on YouTube

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#238]
Version 1.3.0
Android AOSP 10

**What is the Problem you are facing ?**
Bottom Toolbar is very useful feature but it hides the comment subsection in YouTube mobile site and it does not hide on scrolling

**How it should work ?**
Bottom Toolbar should not cover the lower most content of webpage

**Comment by ghost** [comment]
This Link contain the video of Bug I am facing 
https://mega.nz/file/f35zDYZL#Of2QUCg05b0vLeex7kYrXaSgXQP2tPKwd4wVdXoFOtc

**Comment by festum** [comment]
It also hides Google search input
