### ISSUE TITLE
Pull in Mozilla's fix for white flashes in dark mode

### ISSUE THREAD

**Issue by ale82to** [fork-maintainers/iceraven-browser#239]
https://www.reddit.com/r/firefox/comments/jlpomc/the_latest_firefox_nightly_finally_fixes_the/

**Comment by Sparklytical** [comment]
Oh yes this commit is needed asap. I really hate those white flashes

**Comment by PtrckDns** [comment]
It is almost a month now. Are the maintainers taking a break?

**Comment by interfect** [comment]
I've been a bit busy, and @abhijitvalluri hasn't been around either.

My current task is getting #234 in, so unless this fix from nightly gets uplifted into Mozilla's v83 branch, we're unlikely to get it until we start tracking Mozilla's v84. But if it can be broken out as a separate PR to this repo, we might be able to merge it earlier.

**Comment by abhijitvalluri** [comment]
Hi @interfect. Thanks for continuing to work on this. My personal life has become very busy recently so I couldn't spend time on this. I had so many tasks to do that I couldn't manage the time to work on this. But I've been passively checking the updates you have been doing here! 🙂 Hope I can help again when I get free time.

**Comment by interfect** [comment]
Hey @abhijitvalluri, good to hear you are OK. If/when you get some time, I think the thing we need you for most is fixing the tests, which I went and broke by merging from Mozilla. (I was bad; I figured we needed the merge more than the passing tests, and running the build worked fine for me.)

I'm tracking it in #246; they started hanging on CI and complaining they couldn't fetch artifacts on my machine, and I'm a bit lost as to how to debug such weird Maven problems.

**Comment by abhijitvalluri** [comment]
Hmm, I wonder how much I can figure it out myself. I haven't done such kind of troubleshooting before. I'm still busy with personal work and put this on the back burner, so I will need a few days at least before I can look at it.

**Comment by aquaspy** [comment]
Go in:

About iceraven
click in the logo 6 times

go back

now, below about iceraven, go in secret settings and enable "Wait until first paint to show page content"

that is it guys

**Comment by ale82to** [comment]
that's not the same closing a tab for example still makes a brief white flash.in fenix nighlty white flashes are totally gone

**Comment by aquaspy** [comment]
I was just trying to help.
