### ISSUE TITLE
Request Extension: I2P Proxy for Android and Other 

### ISSUE THREAD

**Issue by eyedeekay** [fork-maintainers/iceraven-browser#243]
There are currently extremely limited ways to easily and securely configure a Firefox browser for use with the I2P anonymous network on Android[Reddit link citing this issue](https://old.reddit.com/r/i2p/comments/jh8wkc/android_help_needed_please/). I2P is an anonymous peer-to-peer network that is in some ways comparable to Tor, but which targets different audiences and has different strengths.

It is possible to ease the configuration of a Firefox browser for I2P on Android using a browser extension, the source code of which is available here: http://git.idk.i2p/idk/I2P-Configuration-For-Chromium and the addons.mozilla.org page is available here: https://addons.mozilla.org/en-US/android/addon/i2p-proxy/. Although this extension was originally for Chromium only, it now also works with Android. I have tested this WebExtension in Fenix using web-ext and have confirmed it to be operate as expected.

        web-ext run -t firefox-android --adb-device NE1GAM7780819544 --firefox-apk org.mozilla.firefox_beta

I was not able to test it in IceRaven directly because I was unable to get the it attached to the debugger. If it works as in Fenix, installing this extension will configure IceRaven to use I2P and route all traffic to the I2P HTTP Proxy, which the user will need to have installed from another source(GPlay, F-Droid, etc.).

It would help our users very much if you would consider adding this extension to your default collection. Thanks for your time.

**Comment by interfect** [comment]
OK, I put it on the list. If it works in Mozilla Fenix Firefox under the debugger I suspect it will work for us too.
