### ISSUE TITLE
Add-on request: Old Reddit Redirect

### ISSUE THREAD

**Issue by Nate-Hawk** [fork-maintainers/iceraven-browser#247]
I know similar results can be achieved with Tampermonkey or Redirector, but I'd really like it if this add-on were available as a standalone. It just works better than a script in a more general use add-on.

**Comment by interfect** [comment]
As far as I can tell, this add-on is already in the collection: https://addons.mozilla.org/en-US/firefox/collections/16201230/What-I-want-on-Fenix/?page=2&collection_sort=-added
