### ISSUE TITLE
[Bug]Please fix the wrong detection for autofill program integrated with Android build-in autofill module

### ISSUE THREAD

**Issue by noah-dong-de** [fork-maintainers/iceraven-browser#248]
## Steps to reproduce
When I firstly open an url like github.com, autofill program prompt will be shown under username or password field, then click it to open the program suck as enpass password manager .However, when I select one item to fill it in, it will make it bind with browser name "iceraven" instead of the domain name. And that puzzled me for the wrong result.
### expected behavior
The first autofill procedure bind the password to domain name.
### Device information

* Android device: pixel 4a Android 11

**Comment by neekless** [comment]
This needs to be fixed by enpass itself. Enpass needs to detect iceraven and read the domain from iceraven's urlbar.

For example, this is how bitwarden does it https://github.com/bitwarden/mobile/commit/8f533bc5764a38b25ad5df318ebbabcf338e22d2

**Comment by interfect** [comment]
Yes, I suspect that this has to be fixed on the Enpass side, by adding the Iceraven app ID to a list somewhere.
