### ISSUE TITLE
Availability on Google Play Store and F-Droid

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#250]
### What is the user problem or growth opportunity you want to see solved?
More users will be able to download app and trust the project 

### How do you know that this problem exists today? Why is this important?
Google makes it difficult to install random app from web due to security reasons 

### Who will benefit from it?
Less Tech Friendly users

**Comment by interfect** [comment]
This is something I would like but is also a duplicate of #16 and #71.
