### ISSUE TITLE
Add a print page feature

### ISSUE THREAD

**Issue by L31FY** [fork-maintainers/iceraven-browser#254]
## Steps to reproduce
When wanting to print a page, locate the print option in the menu or share function somewhere

### Expected behavior
Locate the print option and do so

### Actual behavior
Unable to find a print option anywhere

### Device information

* Android device: Samsung Galaxy S9, stock ROM
* Fenix version: Iceraven 1.4.0

**Comment by interfect** [comment]
I don't think Mozilla Firefox has a print feature. We could add one, but someone would have to write it.

**Comment by L31FY** [comment]
It definitely _used to_ have print and so did Fennec because I have a couple of devices frozen on the old version before the "bad" broke-everything update happened. I wonder where it went? Seems super wild and counterproductive for them to remove an extremely basic useful function like that. Guess Mozilla thought people don't print anymore.

**Comment by ghost** [comment]
Using printing add-on is enough I guess 🙄

**Comment by interfect** [comment]
They reimplemented a bunch of the core stuff so they could have a Gecko-based WebView equivalent, and probably never did printing in the engine I guess? I don't *think* it's likely to be something we can just turn on again in the UI, but we could go digging for it.

January 9, 2021 10:35 PM, "Leif" <notifications@github.com (mailto:notifications@github.com?to=%22Leif%22%20<notifications@github.com>)> wrote:
	It definitely used to have print and so did Fennec because I have a couple of devices frozen on the old version before the bad update happened. I wonder where it went? Seems super wild and counterproductive for them to remove an extremely basic useful function like that. Guess Mozilla thought people don't print anymore.

**Comment by Davy49** [comment]
I wasn't aware that that we even had a printing add-on we could utilize with iceraven.

**Comment by akliuxingyuan** [comment]
Fenix have a print2pdf in share menu on toolbar
