### ISSUE TITLE
[Bug]All the extensions and web will crash when you try to login reddit

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#255]
## Steps to reproduce
1.install ublock
2.install useragent switcher
3.install tampermonkey
4.visit reddit.com
5.login your accounts
### Expected behavior
Login your account
### Actual behavior
All the extensions and web crashed unless you force stop iceraven.
![Screenshot_2020-12-12-10-39-15-429_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/32984303/101970605-50829d00-3c66-11eb-929d-8369f3b747d8.png)

### Device information

* Android device: Oneplus 6
* Fenix version: iceraven 1.4.0

**Comment by edo0** [comment]
What android version are you using? 
Here with LineageOS 16 (Android 9) and Iceraven 1.4 everything seems to work smoothly

**Comment by ghost** [comment]
> What android version are you using?
> Here with LineageOS 16 (Android 9) and Iceraven 1.4 everything seems to work smoothly

Well,I am using Android 9 (Hydrogen 9.0.8)🤔.

**Comment by L31FY** [comment]
Not having that on my device either.

**Comment by ghost** [comment]
closed
