### ISSUE TITLE
SponsorBlock vanished from the add-on list in the app despite being in the collection

### ISSUE THREAD

**Issue by Dev-i-l** [fork-maintainers/iceraven-browser#259]
sponsorblock extension request

**Comment by interfect** [comment]
Sponsorblock has been in the collection, and I even had it installed at one point. But I went to look for it and couldn't find it in the list in the app for some reason. I am not sure why.

I have removed and re-added it. Maybe it will show up when the app refreshes the list next?

**Comment by Dev-i-l** [comment]
issue still exists in v1.5

**Comment by gosndka** [comment]
Was anyone able to solve this issue? I am facing the same issue of not being able to add sponsor block to the browser
