### ISSUE TITLE
APK does not install successfully; APK install flow reports "App not installed" instead of a success message.

### ISSUE THREAD

**Issue by dear8auer** [fork-maintainers/iceraven-browser#260]
![Screenshot_2020-12-20-21-13-52-703_com android chrome](https://user-images.githubusercontent.com/59098303/102716805-592f3f00-4308-11eb-8ace-bc39867de8f1.jpg)
I have downloaded arm64-v8a which is expected to support in my device. But after downloading and enabling/allowing installation from unknown source,It's showing app not installed

**Comment by interfect** [comment]
That's weird.

Does the 32-bit ARM version work? I think arm64 devices support both.

Can you try downloading it a different way? Maybe download it on a computer and `adb install app.apk`?

**Comment by airminer** [comment]
I've run into the same problem. It seems to be caused by having firefox for android installed. After I uninstalled firefox (I had the old Fennec-based version installed, for addon support), I could successfully install Iceraven.

Are you guys are using the same package name as the official firefox release (`org.mozilla.firefox`)? If so, it would probably be the cause of the conflicts.

**Comment by interfect** [comment]
We definitely aren't supposed to be, but I suppose it's possible. I was running 1.4.0 for a while alongside Firefox with no trouble. I am planning to do a new release soon and I will inspect the APK to make sure.

January 3, 2021 2:47 PM, "Bence Szépkúti" <notifications@github.com (mailto:notifications@github.com?to=%22Bence%20Sz%C3%A9pk%C3%BAti%22%20<notifications@github.com>)> wrote:
	I've run into the same problem. It seems to be caused by having firefox for android installed. After I uninstalled firefox, I could successfully install Iceraven. Are you guys are using the same java package name as the official firefox release (org.mozilla.firefox)?

**Comment by dear8auer** [comment]
@interfect firefox is not responsible for this. I downloaded from chrome and tried to install .My default browser is chrome and I don't have firefox installed.
