### ISSUE TITLE
[Bug] Bitwarden autofill not working

### ISSUE THREAD

**Issue by SinTan1729** [fork-maintainers/iceraven-browser#266]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
Click on "Autofill with Bitwarden" and select the entry.

### Expected behavior
Login details should be filled.

### Actual behavior
Nothing is filled.

### Device information

* Android device: Redmi K20 (Android 10)
* Fenix version: iceraven-1.5.0 (Build #2015786075)

**Comment by Eevoo** [comment]
Hey there @SinTan1729, couple questions I suspect the maintainer will need.

1. Which Bitwarden? Android app or IceRaven extension?
2. Is it broken on all websites, or only certain ones?
3. Can you provide a particular site known not to work so the maintainer can test fixes?

**Comment by SinTan1729** [comment]
It's the Android app (ver. 2.7.2).
It's broken on all websites I visited. facebook.com and twitter.com would be two examples.

**Comment by interfect** [comment]
@SinTan1729 Are you using a Bitwarden that includes https://github.com/bitwarden/mobile/commit/8f533bc5764a38b25ad5df318ebbabcf338e22d2?

That commit *should* be in 2.7.2.

Maybe repoen https://github.com/bitwarden/mobile/issues/1105 ?

See also: #210 which is the last time Bitwarden didn't work.

**Comment by SinTan1729** [comment]
> @SinTan1729 Are you using a Bitwarden that includes https://github.com/bitwarden/mobile/commit/8f533bc5764a38b25ad5df318ebbabcf338e22d2?
> 
> That commit *should* be in 2.7.2.
> 
I'm using the latest version, so I believe that includes that commit.
> Maybe repoen https://github.com/bitwarden/mobile/issues/1105 ?
> 
> See also: #210 which is the last time Bitwarden didn't work.

bitwarden/mobile#1105 is different from my error. The url is properly matched and correct options are shown. But after selecting an entry, nothing is put inside the boxes.

**Comment by SinTan1729** [comment]
I'm amazed that this still isn't fixed.

**Comment by interfect** [comment]
I think it's because nobody has dug deeper into the issue to actually diagnose what is going wrong. Have you looked at the various Android logs to see if anything is suspicious? Does Bitwarden *think* it has successfully entered text?

Unfortunately I don't use Bitwarden and since the bug doesn't affect me I can't really devote any time to the spelunking that would be necessary to figure out what's going wrong here. But if you or someone else can come up with a theory and a potential change I can certainly take it.

**Comment by SinTan1729** [comment]
I'm not really experienced in these things. I tried looking at the logs using matlog, but nothing is coming up. Can you point me to the right direction so that I can try to figure something out?

**Comment by interfect** [comment]
I don't really know all that much more. I think I usually look at logs with the adb logcat command.

**Comment by akliuxingyuan** [comment]
It's actually working
