### ISSUE TITLE
Custom Add-on collection

### ISSUE THREAD

**Issue by h0cheung** [fork-maintainers/iceraven-browser#268]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Support Custom Add-on collection.

### How do you know that this problem exists today? Why is this important?

We should have the right to choice addons ourselves. And It has been already supported in official Firefox Nightly for a long time.

### Who will benefit from it?

Those who use some special addons.

**Comment by ghost** [comment]
You can also set your own add-on collection in Iceraven though: settings - customize

**Comment by h0cheung** [comment]
> You can also set your own add-on collection in Iceraven though: settings - customize

I only tried the same way as Firefox Nightly. So thanks for your reminding me.
