### ISSUE TITLE
🐞 [Bug] Downloaded APK's not showing Open with 'App Manager' option

### ISSUE THREAD

**Issue by Rikj000** [fork-maintainers/iceraven-browser#276]
## Steps to reproduce
1) Install Ice Raven
2) Enable storage permission & ability to install apps from unknown sources
3) Download any APK through Ice Raven and attempt to install it

### Expected behavior
Option to select 'always open with app manager' for APK files and install it through there

### Actual behavior
Open with 'App Manager' option is missing rendering me unable to install the APK, also when I open the downloaded APK's with my file browser I won't get the option to install the APK.

### Device information
* Android device: Nintendo Switch LineageOS 15.1 and LineageOS 17.1
* Fenix version: Ice Raven v1.6.0 ARM64-v8a

**Comment by L31FY** [comment]
I see this in Nightly also so it may be an upstream thing

**Comment by interfect** [comment]
I'm not able to reproduce this; I just downloaded an APK from apkpure and, from the "Open" button in Iceraven, I was prompted to open it with "Package Installer".

The fact that it also doesn't prompt to open with the installer after it has been saved to disk and is opened from the file manager suggests to me that there might be something wrong with the APK itself. Do you have a link to a non-working APK?

**Comment by Rikj000** [comment]
I just re-tried downloading the latest NewPipe APK from GitHub using IceRaven 1.6.0 and was able to install this APK file! :)
So I'm guessing it's safe to close the issue now.

**Comment by L31FY** [comment]
> I'm not able to reproduce this; I just downloaded an APK from apkpure and, from the "Open" button in Iceraven, I was prompted to open it with "Package Installer".
> 
> The fact that it also doesn't prompt to open with the installer after it has been saved to disk and is opened from the file manager suggests to me that there might be something wrong with the APK itself. Do you have a link to a non-working APK?

It was happening to anything I downloaded until I updated versions. The actual APK was fine and would install completely fine if I opened them from the file manager on the device and would get the correct prompt. Something was just temporarily broken it seems.

**Comment by interfect** [comment]
Glad to hear it's working now!
