### ISSUE TITLE
Enable a couple of pull to refresh/refresh button add-ons

### ISSUE THREAD

**Issue by abhijitvalluri** [fork-maintainers/iceraven-browser#28]
### What is the user problem or growth opportunity you want to see solved?

Sadly, Mozilla Firefox still does not allow for reloading the webpage using the widely used approach of pulling down from the top to refresh the page, as you can do in Chrome and elsewhere on Android. There are a few add-ons available for Firefox Android that worked with previous versions (Fennec, v68) that solve this problem.

So, can you please enable these add-ons? 
* [Refresh in URL bar for Android](https://addons.mozilla.org/en-GB/firefox/addon/refresh-in-url-bar-for-android/) add-on
* [Pull to Refresh](https://addons.mozilla.org/en-GB/firefox/addon/firefox-pull-to-refresh/) add-on

### How do you know that this problem exists today? Why is this important?

Well, you can use the browser and figure out that this feature is missing in the vanilla version of the browser.

### Who will benefit from it?

Most users should benefit from the added simplicity of refreshing the page by pulling or using the button in the bar (provided it works!)

**Comment by interfect** [comment]
OK, these are on the list now.
