### ISSUE TITLE
Can you please add the external Video Played Add-On?

### ISSUE THREAD

**Issue by motareks** [fork-maintainers/iceraven-browser#280]
Hi, I don't know if you are still developing this but can you please add this add on:

https://addons.mozilla.org/de/android/addon/external-video-player/

Since it is removed I don't use firefox anymore...
Would be great :)

**Comment by interfect** [comment]
That add-on is already in [the collection on addons.mozilla.org](https://addons.mozilla.org/en-US/android/collections/16201230/What-I-want-on-Fenix/) that controls what add-ons the browser thinks it should be able to install. It should show up for installation, but I can reproduce that it doesn't.

We have more problems with add-ons that just don't show up here: #259 #185

**Comment by A3148475824** [comment]
插件要这干什么不来个内置播放器吗？

**Comment by A3148475824** [comment]
不可以

**Comment by krystian3w** [comment]
Other idea #684
