### ISSUE TITLE
[Bug] Android PDF.js does not work in iceraven 1.6.0 (Fenix 85), iceraven need to be updated to Fenix 86.

### ISSUE THREAD

**Issue by cbwee** [fork-maintainers/iceraven-browser#287]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

Android PDF.js does not work in iceraven 1.6.0 (Fenix 85), updating to Fenix 86 fixes this issue.

## Steps to reproduce
1. Install iceraven 1.5.0 and Android PDF.js Add-on, open any PDF file online, it will work.
2. Update it to iceraven 1.6.0, and when I try to open the same PDF file, it won't load.
3. Install Fennec F-droid version 86, and test the same add-on in it, the PDF file loads successfully.

### Expected behavior
Android PDF.js should work as it did previously.

### Actual behavior
Android PDF.js does not load PDF files in Fenix 85 (iceraven 1.6.0), this issue is fixed in Fenix 86, but iceraven is not updated to Fenix 86.

### Device information

* Android device: POCO M3 (M2010J19CG)
* Fenix version: 85, iceraven 1.6.0

**Comment by interfect** [comment]
This is fixed in #293 which pulls in the Mozilla Firefox v86 changes.

**Comment by interfect** [comment]
This is fixed in the 1.7.1 release.
