### ISSUE TITLE
[Bug] Download With prompt doesn't appear in a custom tab with "Open links in Apps" & "External Download Manager" both set

### ISSUE THREAD

**Issue by Canvas02** [fork-maintainers/iceraven-browser#290]
## Steps to reproduce
 
* Have "Open links in Apps" & "External Download Manager" on (in settings)
1. Open a filehosting(tested in uploadrar.com) site in a custom tab
2. Generate download link
3. Click download button
 ### Expected behavior
 
 Opens Iceraven's "Download with" prompt
 ### Actual behavior

 Opens Android's "Open With" prompt
then when closed and clicked again it opens Iceraven's "Download With" prompt
 ### Device information
 
* Android device: Samsung A21s 64Gb (SM-A217F/DS)(Android 10, One Ui Core 2.5)
* iceraven-1.6.0 (Build #2015791811)
* tested on "uploadrar.com" in custom tab
* Video: 

https://user-images.githubusercontent.com/73031433/109473390-e666e080-7a7b-11eb-9d46-d3bd845fb2d1.mp4

**Comment by interfect** [comment]
Hm. That's weird.

Does the same thing happen in Mozilla Firefox? The "External Download Manager" setting started out as something Iceraven had to turn on, but now Mozilla Firefox has it enabled in release builds.

If so, maybe Mozilla will fix it for us.

**Comment by Canvas02** [comment]
I will see if it is in FF

**Comment by Canvas02** [comment]
it is in FF

**Comment by Canvas02** [comment]
When disabling the "Open link in app" setting the issue is fixed
