### ISSUE TITLE
[BUG] Universal Bypass not working

### ISSUE THREAD

**Issue by prono69** [fork-maintainers/iceraven-browser#291]
Universal bypass is not working in latest Iceraven browser. After bypassing it should go to the link but it's showing this. ![Here](https://i.imgur.com/UoutQgk.jpg)

I tried with different browsers . It's working fine there.

**Device Information** 
Redmi Note 4 (Mido)
Android 10

_Sent from my Redmi Note 4 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by interfect** [comment]
I think #293 might fix this. I noticed I started getting similar "jar:file://" URLs from extensions trying to take over tabs, but with #293 those extensions are back to displaying the "moz-extension://" URLs they are supposed to show.

**Comment by cbwee** [comment]
As I mentioned in #287 , updating to Fenix 86 will fix this issue, because when I used the Android PDF.js add-on, I also got the same error that starts with "jar:file///data/user/0/".

**Comment by interfect** [comment]
OK, this should work in release 1.7.1 which I just put up.

**Comment by prono69** [comment]
Thanks :grinning:
