### ISSUE TITLE
Add-on request: Text Reflow WE

### ISSUE THREAD

**Issue by alexolog** [fork-maintainers/iceraven-browser#297]
I find [Text Reflow WE](https://addons.mozilla.org/en-US/android/addon/text-reflow-we/) to be indispensible on small screen devices, please add it.

**Comment by alexolog** [comment]
7 months should be ample time for something as simple as adding an extension.

**Comment by interfect** [comment]
I've added this to the list. Sorry it takes so long; I don't actually handle requests usually.

**Comment by alexolog** [comment]
> Sorry it takes so long; I don't actually handle requests usually.

Is there someone who does?

**Comment by interfect** [comment]
Not really. I can delegate parts of the Github repo to people, but I don't
think I can delegate control of the extension list on AMO to anyone, using
their system.

I could try and write some code to let the browser use multiple lists, if
someone wants to maintain another main list.
