### ISSUE TITLE
add view source

### ISSUE THREAD

**Issue by mohibo** [fork-maintainers/iceraven-browser#309]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

**Comment by KememChan** [comment]
just use eruda loader with violentmonkey dude

**Comment by maxstarkenburg** [comment]
I came across this issue after reading [this article about viewing source on mobile](https://css-tricks.com/view-source-on-mobile/) where several of the comments noted that prefixing the URL with `view-source:` will work (as it does on desktop FF). However, when I tried that on Iceraven, I got a "Cannot Complete Request" message instead. However, when I check Android FF regular and nightly, it seemed to work on those (so I was surprised it wouldn't work here, unless it's somehow an extension inadvertently interfering or something).

![Screenshot_20220515-222249](https://user-images.githubusercontent.com/3514521/168510210-691957ac-8ea2-4e26-90c5-7da3ecf6991f.png)

**Comment by akliuxingyuan** [comment]
> I came across this issue after reading [this article about viewing source on mobile](https://css-tricks.com/view-source-on-mobile/) where several of the comments noted that prefixing the URL with `view-source:` will work (as it does on desktop FF). However, when I tried that on Iceraven, I got a "Cannot Complete Request" message instead. However, when I check Android FF regular and nightly, it seemed to work on those (so I was surprised it wouldn't work here, unless it's somehow an extension inadvertently interfering or something).
> 
It works actually, at least with v1.21.2

**Comment by maxstarkenburg** [comment]
Indeed, it does now. Thanks for the heads-up, @akliuxingyuan!
