### ISSUE TITLE
Be able to install/sideload "Bypass Paywalls" and other XPI extensions and add-ons not hosted on AMO

### ISSUE THREAD

**Issue by borealis999** [fork-maintainers/iceraven-browser#31]
The extension Bypass Paywalls (can be found here: https://github.com/iamadamdev/bypass-paywalls-chrome) is useful for getting around paywalls for news sites. However, it is not on the  Firefox Addons Store, so I was wondering if it could be still be supported for Iceweasel.

**Comment by interfect** [comment]
Getting it in is going to require someone actually writing the UI to load an extension from XPI (or else standing up a fake addons.mozilla.org to host it and pointing the browser at it).

I'd like to have it, but I don't think I can do it myself.

**Comment by michael1900** [comment]
How can install this Paywall .xpi on this browser? Thanks, please help
