### ISSUE TITLE
Clarification Re: 1.8 Release

### ISSUE THREAD

**Issue by CharmCityCrab** [fork-maintainers/iceraven-browser#312]
@interfect 

I noticed that Iceraven 1.8 appeared a few days ago on the releases page, but does not include typical release formats like .apk

Just for the sake of clarification, is 1.8 intended as an official release where the standard release formats were just accidentally omitted, or is it an unofficial update for internal use only that is being tested before being released to the wider community in the standard formats?

**Comment by interfect** [comment]
It's supposed to be a normal release. If there's no APKs, something has gone wrong with the
builder, and I will have to take a look at how to fix it.

**Comment by interfect** [comment]
OK, I have no idea why it's decided to skip the 1.8 release action, and there's no button to unskip it. But I just tagged a 1.9 that it's building now, so we can all just use that instead: https://github.com/fork-maintainers/iceraven-browser/runs/2358590950?check_suite_focus=true

Maybe the problem is I tagged 1.8 from the web UI, so it doesn't get the same tag pushing event?

**Comment by edo0** [comment]
Is the same issue presenting itself with release 1.11, @interfect ?

**Comment by interfect** [comment]
Maybe? That one I made on the command line and pushed up, but it also managed to not get a release workflow kicked off.

I've made 1.11.1 through the Github release wizard; maybe it won't be confused by the release existing and will attack the files to it?

**Comment by edo0** [comment]
Hopefully 🤞

**Comment by interfect** [comment]
Nope, it fails if the release is there. Maybe I should edit the workflow so it just expects the release to be pre-created...

**Comment by edo0** [comment]
I wish I could help, but I am afraid I am myself quite clueless of how github actions operate in this regard

**Comment by edo0** [comment]
Very happy to see you managed to figure it out!
