### ISSUE TITLE
Not asking for which app causing the website to stop responding to touches [Popup asking missing]

### ISSUE THREAD

**Issue by Thewisem** [fork-maintainers/iceraven-browser#314]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Open Iceraven
2. Search this link https://www.muslimpro.com/en/prayer-times
3.  Wait for some time

### Expected behavior
Ask whether I want it on their app or on firefox

### Actual behavior
Doesn't ask making the website unscrollable

### Device information

* Device vendor / model and Android version: Samsung Galaxy Tab A SM P555 Version 7.1.1 Nougat
* Firefox for Android version: 1.10.0
*

**Comment by akliuxingyuan** [comment]
Well, I guess it's the website issue, it works fine in latest version anyway
