### ISSUE TITLE
[Add-on Request] Audio Downloader Prime addon required

### ISSUE THREAD

**Issue by Beatz106** [fork-maintainers/iceraven-browser#315]
It is needed to download music, especially content that is "tied" to streaming services like Spotify. Tested its operation in another browser but in Spotify's 30-second mode. It was impossible to test whether the content was downloadable due to typical compatibility issues with their player.

**Comment by krystian3w** [comment]
Other idea #684 if addon is available in Moz://a store as legit addon.
