### ISSUE TITLE
[Bug]Crashing Randomly 

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#32]
## Steps to reproduce
Install Iceweasel Fork 6 
It will start crashing randomly and can't be fixed by force stopping or clearing cache
I have to clear data of iceweasel from settings to stop it from crashing each time when I try to open the app

### Device information

* Android device: AOSP 10 with microG instead of Google Play Services
* Fenix version: Fork 6 
Logs
(https://github.com/interfect/fenix/files/5144927/fenixfork6.zip)

**Comment by ale82to** [comment]
it happens if u set it as default browser, today fenix nightly fixed that bug

**Comment by interfect** [comment]
I'll pull in from upstream and release a new build. Hopefully @ale82to is right.

**Comment by interfect** [comment]
OK, I've put out https://github.com/interfect/fenix/releases/tag/fork-7. I set it as my default browser and didn't observe any crashes in the little while I used it. I'm going to declare this solved, since there's not enough specifics in the bug report to contradict me. Please let me know if it still doesn't work.

**Comment by cleanerspam** [comment]
Browser Crashed once more but started working again when I restarted it

**Comment by ghost** [comment]
One issue is resolved that it stops starting after crashing 
But the problem is it is still crashing randomly
[logcat.txt](https://github.com/interfect/fenix/files/5146461/logcat.txt)
@interfect

**Comment by interfect** [comment]
The remaining crash (which maybe has to do with microG?) is tracked in #107 now.
