### ISSUE TITLE
support 120hz refresh rate

### ISSUE THREAD

**Issue by ziping46** [fork-maintainers/iceraven-browser#325]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

**Comment by interfect** [comment]
Any idea what makes one app support 120 Hz refresh rate while another does not? I would think the refresh rate would be determined by the OS and the app would draw when the OS tells it to.

Also, does Mozilla Firefox support this, or would we have to develop something for this ourselves?

**Comment by akliuxingyuan** [comment]
It's controlled by your ROM, change refresh rate in System setting, some ROMs support `custom application refresh rate`, some ROMs only support high refresh rate app which in whitelist
