### ISSUE TITLE
Adguard as DNS resolver using DNS over HTTPS

### ISSUE THREAD

**Issue by billy2k19** [fork-maintainers/iceraven-browser#326]
I recently got DNS-over-HTTPS with ad blocking working in the about:config of the IceRaven browser.  It would be great as a new option (or even the default setting!) in Privacy options with a fancy custom GUI menu.

The setup is fairly straightforward in about:config

Set network.trr.mode to 2

Set network.trr.custom_uri and network.trr.uri

Use

https://dns.adguard.com/dns-query

string for “Default” or

https://dns-family.adguard.com/dns-query

for “Family protection”.

References:

Setting adguard as DNS over HTTPS In Firefox. (self.Adguard)
https://www.reddit.com/r/Adguard/comments/ecj15p/setting_adguard_as_dns_over_https_in_firefox/

Running a DNS-over-HTTPS endpoint on FreebSD (DoH)
https://wordpress.metro.cx/2019/07/10/running-a-dns-over-https-endpoint-on-freebsd-doh/

**Comment by akliuxingyuan** [comment]
It needs to patch geckview to export APIs that can modify pref

**Comment by akliuxingyuan** [comment]
unified to #301
