### ISSUE TITLE
Close opened tabs when the app is ended

### ISSUE THREAD

**Issue by tareefdev** [fork-maintainers/iceraven-browser#331]
Close opened tabs when the app is ended or open a blank tab when relaunching the app again. Implementing one of those features will give some users a clean workspace to start with. It's really annoying me when I open Iceraven to see my latest tab, so I need to open a new tab to start searching.

**Comment by Yalns** [comment]
是的，我需要这个功能。

**Comment by vehosah** [comment]
> 
> 
> 是的，我需要这个功能。

can you pls speak english instead of chinese?

**Comment by akliuxingyuan** [comment]
`Settings>Homepage>Opening Screen` choose Homepage option
