### ISSUE TITLE
Ability to manually add extensions

### ISSUE THREAD

**Issue by sugguy** [fork-maintainers/iceraven-browser#339]
I suggest a way to manually add .xpi files to the browser

**Comment by freebrowser1** [comment]
I completely support that suggestion !

**Comment by LeeBinder** [comment]
So do I 👍

**Comment by bobpaul** [comment]
It should require some extra steps (like changing one or more things in `about:config`, but I like this suggestion. I don't think it's a good idea for all Firefox forks to enforce mozilla's add-on store (and thus mozilla's moderation, etc) as the only means of installing add-ons.

**Comment by akliuxingyuan** [comment]
completed in #702
