### ISSUE TITLE
Addon-on request

### ISSUE THREAD

**Issue by unixfox** [fork-maintainers/iceraven-browser#34]
Hello,

Is it possible to add these add-ons to the list:
 - https://addons.mozilla.org/en-US/firefox/addon/absolutedouble-trace/
- https://addons.mozilla.org/en-US/firefox/addon/old-reddit-redirect/

Thank you.

**Comment by interfect** [comment]
They're on the list now!

Keep in mind you may need to clear the app data to force it to update, or wait for the cached list to expire.
