### ISSUE TITLE
[Extensions request] "Unhook - Remove YouTube Recommended Videos"

### ISSUE THREAD

**Issue by cpuuntery** [fork-maintainers/iceraven-browser#345]
Compatible with mobile YouTube, [m.youtube.com](m.youtube.com), through Firefox for Android

[Unhook - Remove YouTube Recommended Videos
](https://addons.mozilla.org/en-US/firefox/addon/youtube-recommended-videos/)

**Comment by ToTheMoon1234** [comment]
Yes, this extension works on Fennec too. No reason why it shouldnt be added to iceraven

**Comment by interfect** [comment]
I added this; a lot of people seem to have wanted it.
