### ISSUE TITLE
[Bug] Vp9 is not enabled by default. Even IF device support hardware decoding

### ISSUE THREAD

**Issue by cpuuntery** [fork-maintainers/iceraven-browser#346]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
install iceraven
### Expected behavior
Vp9 is enabled by default. IF device support hardware decoding
### Actual behavior
Vp9 is disabled by default. You need to go to [about:config](about:config) and enable it by yourself
[![vp9-firefox.png](https://i.postimg.cc/2jP3LykG/vp9-firefox.png)](https://postimg.cc/7bnqpxTJ)
### Device information

* Device vendor / model and Android version: 
android 11 pixel 4a
* Firefox for Android version: ? (go to Settings -> About Firefox)
Latest version. At the time of writing this issue

**Comment by interfect** [comment]
Does Mozilla Firefox enable vp9 hardware decoding by default? Some of these about:config settings live in android-components and I'm not sure we can ship different defaults without forking that too.
