### ISSUE TITLE
Greasemonkey is supported but does not work

### ISSUE THREAD

**Issue by freebrowser1** [fork-maintainers/iceraven-browser#355]
## Steps to reproduce
Install Greasemonkey add-on from the add-ons menu.
Then click on Addons => Greasemonkey and then on "New user script". Nothing happens.

### Expected behavior
A popup should appear with this contents:
````// ==UserScript==
// @name     Unnamed Script 529193
// @version  1
// @grant    none
// ==/UserScript==
````

where the user can type or paste a script.

### Actual behavior
Nothing happens.

### Device information

* Device vendor / model and Android version: ?  Oneplus 6 , Oxygen OS 10.5
* Firefox for Android version: ? (go to Settings -> About Firefox)  89.1.1 (latest Iceraven).

**Comment by krystian3w** [comment]
You can try add manually to tampermokey or violentmokey by own private collection as better alternative platform for user scripts.
