### ISSUE TITLE
Print feature request

### ISSUE THREAD

**Issue by Subbarao6338** [fork-maintainers/iceraven-browser#360]
Please print to PDF feature

**Comment by ghost** [comment]
Ya I also want this feature.

**Comment by ghost** [comment]
In the meantime, there's a workaround:

1. Install [Print by Bill Farmer](https://f-droid.org/packages/org.billthefarmer.print) on F-Droid

2. Go to any site, and tap the Share icon; select Print by Bill Farmer afterward

3. Once you're in the Print app, tap the print icon at the top right, and now you can print your desired website as PDF

**Comment by akliuxingyuan** [comment]
same as https://github.com/fork-maintainers/iceraven-browser/issues/176
apps like [Print by Bill Farmer](https://f-droid.org/packages/org.billthefarmer.print) mentioned above it's another option
