### ISSUE TITLE
Renaming master to main branch for Fenix and Android-Components

### ISSUE THREAD

**Issue by st3fan** [fork-maintainers/iceraven-browser#363]
Hi folks,

Just a heads up that we are in the process of renaming our `master` branches to `main`. We are not sure what the impact is on forks. We'll be using the GitHub recommended method, and I _think_ that includes an automatic redirect.

The work can be tracked in these two tickets

 - https://github.com/mozilla-mobile/android-components/issues/10137
 - https://github.com/mozilla-mobile/fenix/issues/11427

We're starting with Android-Components. It is currently in the prepare phase. I'll make sure leave a clear message in the above two tickets about timing. We'll plan a _Switch Day_.

**Comment by st3fan** [comment]
We will already switch Android-components over tomorrow 10am EST. 

Fenix will happen at a later date.

**Comment by interfect** [comment]
Thanks! I've been merging tags in instead of any real branch, but this is good to know.
