### ISSUE TITLE
Can you add LibreJS to the allowed add-ons? 

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#37]
This is my first time doing anything like this on Github, I don't like opening issues often because I feel bad, but any chance LibreJS could be added to the allowed addons? I use it to block non-free javascript. If not it's totally fine haha this browser is awesome sorry thanks ok bye

**Comment by interfect** [comment]
OK, "GNU LibreJS" is now in. No idea if it will work.

You might need to clear the app data to get it to redownload the list before it expires.
