### ISSUE TITLE
Miui mobile phone users can't log in to Firefox account[Bug]

### ISSUE THREAD

**Issue by qq234654231** [fork-maintainers/iceraven-browser#375]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Device information

* Device vendor / model and Android version: ?
* Firefox for Android version: ? (go to Settings -> About Firefox)

**Comment by qq234654231** [comment]
Miui mobile phone users can't log in to Firefox account

**Comment by Sami32** [comment]
Work fine for me:
![Screenshot_2021-09-10-13-07-02-041_com android settings](https://user-images.githubusercontent.com/18471069/132845549-f2817c56-9c0a-4332-98ef-0718b2237450.jpg)
