### ISSUE TITLE
Similar Sites/Web Addon Request

### ISSUE THREAD

**Issue by Hari-Pi** [fork-maintainers/iceraven-browser#376]
I'd like the addon similar sites/web to be added to the collection of add-ons on ice craven

![337209-64](https://user-images.githubusercontent.com/71986052/129428501-69fb2360-83ad-4cb5-8e0a-9d5adb616eff.png)
[Here's the Similar Sites addon link](https://addons.mozilla.org/en-US/firefox/addon/similarsites/) 

![10548-64](https://user-images.githubusercontent.com/71986052/129429033-71f7217f-7668-4187-93b8-6a038a58b017.png)
[Here's the Similar Web addon](https://addons.mozilla.org/en-US/firefox/addon/similarweb-sites-recommendatio/)

**Comment by interfect** [comment]
People might be mad about this one since it looks like ti sends all your browsing history off to the developers and that's kind of the point of it. But in it goes!
