### ISSUE TITLE
Lovely Forks addon request for Iceraven browser

### ISSUE THREAD

**Issue by Hari-Pi** [fork-maintainers/iceraven-browser#377]
I'd like the maintainers of this project to add a addon namely the Lovely Forks to the list of available add-ons in Iceraven browser

![625488-64](https://user-images.githubusercontent.com/71986052/129451900-aaf9fbe3-646c-4af5-b3b4-579bc35070c7.png)

[Here's the official add-on Link](https://addons.mozilla.org/en-US/firefox/addon/lovely-forks/)

**Comment by interfect** [comment]
I've added this.
