### ISSUE TITLE
Support "FoxyProxy Standard" extension

### ISSUE THREAD

**Issue by xmha97** [fork-maintainers/iceraven-browser#38]
Hello,
Please support "FoxyProxy Standard" extension:
https://addons.mozilla.org/en-US/firefox/addon/foxyproxy-standard/
Thanks.

**Comment by interfect** [comment]
OK, "FoxyProxy Standard" is now on the list.

I can't say it's "supported", because it might need more build-out of the WebExtension APIs or changes to the add-on to actually work, but I'm going to close this anyway.
