### ISSUE TITLE
AMOLED Theme

### ISSUE THREAD

**Issue by emmatebibyte** [fork-maintainers/iceraven-browser#380]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
the current dark theme looks atrocious on AMOLED screens

### How do you know that this problem exists today? Why is this important?
I use the app

### Who will benefit from it?
AMOLED screen users

**Comment by akliuxingyuan** [comment]
duplicated #40
