### ISSUE TITLE
CR-Unblocker

### ISSUE THREAD

**Issue by PiyushBaria** [fork-maintainers/iceraven-browser#383]
https://addons.mozilla.org/en-US/firefox/addon/crunchy-unblocker/

Changes your session on crunchyroll.com to a US one when the site is visited from somewhere else and unlocks many more anime!

The CR-Unblocker will get an US Session ID and sets it as your current Session ID cookie. Like this Crunchyroll will think you are located in the US and therefore you should have access to all anime you couldn't watch.

**Comment by krystian3w** [comment]
Other idea #684
