### ISSUE TITLE
Copy Link Text

### ISSUE THREAD

**Issue by OilSubjectLoss7** [fork-maintainers/iceraven-browser#384]
Every browsers has this.

**Comment by akliuxingyuan** [comment]
Long press the link, there is an option to copy the link text in the pop-up window

**Comment by Vandino86** [comment]
> Long press the link, there is an option to copy the link text in the pop-up window

In 2.18.3, I don't have this option. In the press-and-hold menu, there's options to open a link in a new tab (non-Private or Pirvate), copy the link itself, download the link, and share the link, but no option to copy the link _text_.

For example in the first sentence of [this article](https://en.m.wikipedia.org/wiki/Commodore_64), you can press and hold the words "home computer" in the same sentence to bring up the aforementioned press-and-hold menu. From there, you can copy the link itself ("https://en.m.wikipedia.org/wiki/Home_computer"), but there's no option to copy the link _text_ ("home computer").

I believe this should be re-opened or at least marked as a duplicate of [#152](https://github.com/fork-maintainers/iceraven-browser/issues/152) and/or [#362](https://github.com/fork-maintainers/iceraven-browser/issues/362).
