### ISSUE TITLE
select all button?(a couple more requests inside)

### ISSUE THREAD

**Issue by OilSubjectLoss7** [fork-maintainers/iceraven-browser#385]
On tab and bookmark selection, any kind of context where you can select stuff. (Not the text selection)

Also add Share|Copy tabs urls option with optional checkmark to toggle title+url or url. 

And most importantly. Way to import and export bookmarks compatible with any browser.

**Comment by akliuxingyuan** [comment]
tab/bookmark selection and share function already there
