### ISSUE TITLE
[Add-on Request] Switchy Omega

### ISSUE THREAD

**Issue by linsui** [fork-maintainers/iceraven-browser#39]
https://addons.mozilla.org/en-US/firefox/addon/switchyomega/

Thanks!

**Comment by ghost** [comment]
It has not been updated since last 2 years 
I doubt that developer has left the project and without updating evn if it is added to Recommended Add-on Repo it won't support the new Fenix

**Comment by linsui** [comment]
The developer has not left but is too busy to maintain it. See https://github.com/FelisCatus/SwitchyOmega/issues/2007. I tried to find an alternative but looks like it's still the most powerful one and works perfectly on fennec.

**Comment by interfect** [comment]
OK, I put it on the list.

**Comment by linsui** [comment]
Thanks!
