### ISSUE TITLE
Suggestion for addons: Nonioblocker / Deletenonio

### ISSUE THREAD

**Issue by Clr89** [fork-maintainers/iceraven-browser#394]
Is there any possibility of adding two addons that remove "Nonio" in portuguese sites? Nonio is not a paywall, but it's an annoying popup that forces you to register on the site to read the page. 

My suggestion is: 
https://addons.mozilla.org/en-US/firefox/addon/deletenonio/
or

https://addons.mozilla.org/en-US/firefox/addon/nonioblocker/

I know that the 2nd works in Firefox Nightly.

Thank you

**Comment by interfect** [comment]
I've added both of these.
