### ISSUE TITLE
Some Addons for the IceRaven Collection that work in Fennec F-Droid

### ISSUE THREAD

**Issue by MintMain21** [fork-maintainers/iceraven-browser#396]
I've been trying to curate my own collection of Add-Ons that work in Daylight for a while now, but it's hard to keep a decent variety when Nightly and Fennec limit you to 50 items at once. IceRaven doesn't have that problem, and takes advantage of it to have as many Add-Ons available at once as possible. After re-installing IceRaven the other day, I discovered both Add-Ons I hadn't tried before (Instab, Scroll To Top, Video Resumer) and Add-Ons that I gave up on following that actually work in Daylight as of version 92 (SponsorBlock, Read Aloud, Weather Extension). It's so exciting to know these Add-Ons work, and I've added them all to my personal Collection. 

One good turn deserves another, so here are some extensions in my personal collection that I noticed are absent from IceRaven (but I know will work in Firefox Daylight):

Impulse Blocker

RSS-Bridge Helper

Link Gopher

Save Screenshot

Smart HTTPS

Fox Clocks

UnHook

Shut Up

Tap Translate

View Page Source

All of these work in Fennec, and therefore should work in IceRaven too.

**Comment by ToTheMoon1234** [comment]
+1

**Comment by interfect** [comment]
I've gone and added all of these.
