### ISSUE TITLE
Extension request

### ISSUE THREAD

**Issue by alexolog** [fork-maintainers/iceraven-browser#397]
Please add the following extension:

Bypass Paywalls Clean (c)
https://addons.mozilla.org/en-US/firefox/addon/bypass-paywalls-clean-custom

Please note that it is different from the "Bypass Paywalls Clean" (https://addons.mozilla.org/en-US/firefox/addon/bypass-paywalls-clean) extension already in the collection, as it enables custom sites on Android.

**Comment by interfect** [comment]
I've added this to the list.

**Comment by michael1900** [comment]
Where is this addon? I can't find searching in the list. Please help

https://gitlab.com/magnolia1234/bypass-paywalls-firefox-clean

**Comment by alexolog** [comment]
Mozilla removed it from the store
