### ISSUE TITLE
Telemetry can't be disabled

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#4]
## Steps to reproduce
Disable all three options in Data Collection header in Settings
Use any Firewall/Web request logging app to see it's still sending data to mozilla at incoming.telemetry.mozilla.org

### Expected behavior
Stop sharing Telemetric Data

### Actual behavior
It does not stops sending Telemetric data

### Device information

* Android device: AOSP v10
* Fenix version:  v80.0.0-beta.6

**Comment by interfect** [comment]
Ooh, that's a pretty bad bug. Does this affect Mozilla's upstream as well? Or is it only this fork?

Is the telemetry data you turned off being sent back? Or is it just sending empty messages, or messages that don't have any of the data you turned off, but do have something else?

I've wanted to rip out all the telemetry anyway, seeing as Mozilla probably doesn't want it and I have nothing useful to do with it. If anyone wants to make a PR I would be very happy to take it. Otherwise I can dig around and see if I can find some of it.

@cleanerspam You don't happen to have the URLs it's phoning home to, do you? Maybe I can grep for them and work out where in the code all this is coming from.

**Comment by ghost** [comment]
This bug was intentionally made by Mozilla and is present in Fenix official app also
Unfortunately android network logging apps are no so advanced  I can only see that connection is being made to 
`incoming.telemetry.mozilla.org`

Yes please rip out all tracking by mozilla no one wants that

On other note Fennec F droid does not have this issue

**Comment by ghost** [comment]
This is the issue opened in offical source 
https://github.com/mozilla-mobile/fenix/issues/13077

**Comment by mdboom** [comment]
Try changing [this line](https://github.com/interfect/fenix/blob/fork/app/build.gradle#L276)

**Comment by ghost** [comment]
I closed the upstream issue as due to me using my own builds right now this no longer affects me and I don't care enough to look into it more closely. In my own build I changed the line that mdboom mentioned above, as well as setting the telemetry prefs off by default in here https://github.com/interfect/fenix/blob/fork/app/src/main/java/org/mozilla/fenix/utils/Settings.kt#L281. So far I've noticed no connection to incoming.telemetry.mozilla.org. If it's indeed the deletion ping, it makes sense to me that setting the relevant prefs off by default makes it so the ping is not sent at all (after all, there'd be nothing to delete), though I really don't know if that's indeed how it works.

Until someone does the real work allowing one to build Fenix without any of the telemetry SDKs included at all, if you want to be entirely sure there are no outbound connections it's also possible to use a locally built Glean and change the [telemetry endpoint](https://github.com/mozilla/glean/blob/main/glean-core/android/src/main/java/mozilla/telemetry/glean/config/Configuration.kt#L82) to something bogus.

**Comment by ghost** [comment]
Thanks @M83tUt3 
Maybe this will https://github.com/interfect/fenix/issues/25 remove all telemetry  stuff in Iceweasel

**Comment by st3fan** [comment]
@cleanerspam 

> Unfortunately android network logging apps are no so advanced I can only see that connection is being made to
incoming.telemetry.mozilla.org

Fenix does not use the Android network stack, it uses _Necko_, which is our own HTTP/TLS implementation.

If you want to see network connections made through Necko, use the Developer Tools on your Firefox Desktop to connect to Fenix. This will let you see all "internal" connections like Glean, FavIcon fetching, Firefox Accounts, etc.

Note that third-party tools like Leanplum and Adjust do use the Android network stack. To see those, you will need to build a special version of Fenix with some changes to override Android policies. This is a good document that shows how to do that: [How to patch Android app to sniff its HTTPS traffic with self-signed certificate](https://gist.github.com/unoexperto/80694ccaed6dadc304ad5b8196cbbd2c)

**Comment by st3fan** [comment]
@cleanerspam Regarding the following:

> This bug was intentionally made by Mozilla and is present in Fenix official app also

I _think_ what you saw is the following: when you disable telemetry, we actually *delete* your data on the Mozilla servers. This is a new feature to comply with a specific California privacy law. But we rolled it out globally and works in every region/country.

To delete this data, we send a final ping to Mozilla, the "Deletion Ping". This is the last bit of data we send and it instructs the servers to drop all your data.

So if you saw a connection to `incoming.telemetry.mozilla.org` after flipping those checkboxes then it was _most likely_ this Deletion ping.

**Comment by st3fan** [comment]
Ccc @interfect you may find the above interesting and helpful to make sure your Fork does not chat with any services.
