### ISSUE TITLE
Disable Marketing notifications?

### ISSUE THREAD

**Issue by nyanpasu64** [fork-maintainers/iceraven-browser#401]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

Firefox has added "marketing" notifications to their Android app, to eg. set Firefox as the default browser, which has also made its way to Iceraven (latest from ffupdater). I find that philosophically objectionable (basically spam or adware) and expect Iceraven's devs to agree, and also think that if I have both browsers installed, both Firefox and Iceraven producing marketing notifications is twice as much spam as one browser. So I think all marketing notifications should be removed (either the notifications themselves removed, a check added to avoid sending all notifications marked as marketing, or the category muted by default).

### How do you know that this problem exists today? Why is this important?

I think marketing notifications are annoying and a sign of corruption in Mozilla's culture away from building programs to empower users, towards advertising and PR.

### Who will benefit from it?

Users who dislike spam notifications.

**Comment by CharmCityCrab** [comment]
Can you can confirm that the only unexpected notification you're seeing sent from Iceraven is to set it as your default browser?  Or are there other things?

If the notification is to set it as your default browser, and you decline or swipe it away, does it keep reappearing periodically? Or is it an "ask once" type situation?  If it keeps reappearing, how often?

Is anyone who does have Iceraven set as their default browser seeing anything?  I do and haven't, but my experience may not be universal.

I'm just trying to nail down exactly what's going on more percisely.  Hopefully that will be a step towards a potential resolution.

**Comment by CharmCityCrab** [comment]
I found this issue from the upstream Firefox for Android GitHub that claims this notification is only sent once:

https://github.com/mozilla-mobile/fenix/issues/20429

They say that when it was first implemented in Firefox, swiping it away was not considered a dismissal and that it may have appeared more than once for users who did that, but that it now only has to be rejected by a user once (and swiping it away counts) and it should stay away.

It appears to be separate from Firefox  marketing notifications in general, which are not present in Iceraven.

**Comment by interfect** [comment]
This would be great to rip out. Any lead on where in the codebase these are coming from?

**Comment by interfect** [comment]
Looks like it's `app/src/main/java/org/mozilla/fenix/onboarding/DefaultBrowserNotificationWorker.kt`.

**Comment by bel57** [comment]
Hello, installed the browser recently. Just got that spam notification a few minutes ago.
Is there a particular reason this is still a thing? I thought the commit would remove that.
Thanks
