### ISSUE TITLE
Add-on Request: Fast Forward

### ISSUE THREAD

**Issue by holysnipz** [fork-maintainers/iceraven-browser#403]
A successor to Universal Bypass, since [it was abandoned](https://github.com/Sainan/Universal-Bypass/issues/1951)
Might be useful for someone who wants to switch from UB but doesn't want to make their own collection

https://addons.mozilla.org/en-US/firefox/addon/fastforwardteam/

**Comment by interfect** [comment]
This is in now; there were several duplicates for it.
