### ISSUE TITLE
Bring back gfx.webrenderer.force-disable config

### ISSUE THREAD

**Issue by mrxyzl** [fork-maintainers/iceraven-browser#405]
Current implementation on webrenderer from Mozilla on android is not smooth at all on exynos.
Since version 1.13 the config gfx.webrenderer.force-disable disappear and the page load is very slow and laggy.

**Comment by interfect** [comment]
Unfortunately I don't think this is part of `iceraven-browser` or even `android-components` where we get the Android version of the browser engine, but is coming all the way from the Gecko engine shared with desktop Mozilla Firefox, which is where most `about:config` settings are defined. I (no longer?) see `gfx.webrenderer.force-disable` on my desktop browser.

Unfortunately I don't think we can bring this back without swapping out Mozilla Gecko for a different rendering engine.

Does `gfx.webrender.enabled` help at all if you set it to false?

**Comment by mrxyzl** [comment]
> Unfortunately I don't think this is part of `iceraven-browser` or even `android-components` where we get the Android version of the browser engine, but is coming all the way from the Gecko engine shared with desktop Mozilla Firefox, which is where most `about:config` settings are defined. I (no longer?) see `gfx.webrenderer.force-disable` on my desktop browser.
> 
> Unfortunately I don't think we can bring this back without swapping out Mozilla Gecko for a different rendering engine.
> 
> Does `gfx.webrender.enabled` help at all if you set it to false?

Thanks  for replying.  Yes unfortunately  it seem this is arbitrary decision by firefox to force use of web rendering which is still very buggy on android.  They said webrender still disable for some system.
