### ISSUE TITLE
Extension request: Обход блокировок Рунета 

### ISSUE THREAD

**Issue by D3ZOXY** [fork-maintainers/iceraven-browser#408]
https://addons.mozilla.org/ru/firefox/addon/%D0%BE%D0%B1%D1%85%D0%BE%D0%B4-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BE%D0%BA-%D1%80%D1%83%D0%BD%D0%B5%D1%82%D0%B0/

**Comment by krystian3w** [comment]
Other idea #684
