### ISSUE TITLE
[REQUEST] Add these addons to the collection, please

### ISSUE THREAD

**Issue by 1778707** [fork-maintainers/iceraven-browser#409]
Primary: 
https://addons.mozilla.org/en-US/firefox/addon/blocktube/
https://addons.mozilla.org/mn/firefox/addon/youtube-anti-translate/
https://addons.mozilla.org/en-US/firefox/addon/hls-stream-detector/ (VideoHelper doesn't work anymore)

Optional: 
https://addons.mozilla.org/en-US/firefox/addon/reddit-wherever/
https://addons.mozilla.org/en-US/firefox/addon/youtube-thumbnail-rating-bar/

THANK YOU!

**Comment by krystian3w** [comment]
Other idea #684
