### ISSUE TITLE
Add-on request

### ISSUE THREAD

**Issue by sgtbyrd** [fork-maintainers/iceraven-browser#413]
Hello, I'd like to request the following add-ons for the iceraven collection:

1. Visited Link Enabler     &nbsp;&nbsp;   https://addons.mozilla.org/addon/visited-link-enabler
2. Text Reflow WE            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   https://addons.mozilla.org/addon/text-reflow-we
3. Reload All Tabs            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   https://addons.mozilla.org/addon/reload-all-tabs

Thank you for your time and consideration.

**Comment by interfect** [comment]
I've added these. I doubt that Reload All Tabs is going to work, but maybe it will.
