### ISSUE TITLE
Enabling DNS over HTTPS

### ISSUE THREAD

**Issue by ChiefMikeK** [fork-maintainers/iceraven-browser#416]
## User Story
- As a user, I want … maintain my privacy

## Dependencies
- List `about:config` changes. 
- - set **network.trr.mode** to **2**  
- - set **network.trr.uri** to your preferred dns-query URL address. 
- - Optionally set Android **system-wifi** from default google `8.8.8.8/8.4.4.8` to clouldflre-dns `1.1.1.1/1.0.0.1`

### Acceptance Criteria
- Reference [mozilla wiki](https://wiki.mozilla.org/Trusted_Recursive_Resolver ). 
- Testing visit  https://1.1.1.1/help

**Comment by akliuxingyuan** [comment]
unified to #301

**Comment by HaleTom** [comment]
You want network.trr.mode = 3 to force NextDNS:

https://www.phind.com/search?cache=s6qbti2qqk7wn870d815iodq

(The two references agree withe the AI summary)
