### ISSUE TITLE
Extension request and a feature request

### ISSUE THREAD

**Issue by dukenuke2021** [fork-maintainers/iceraven-browser#419]
Hi. 
I've been using this extension on Firefox, called SwiftDial:
https://addons.mozilla.org/en-US/firefox/addon/swiftdial/

Yesterday I came across the browser support page of this extension and it seems to suggest to somewhat support Firefox Fenix (with some tips):
https://nscript.ru/en/swiftdial/browsers/

I'd like to suggest it for the default addon collection for IceRaven (currently my favorite browser on android).

Also it would be great if there was a way to replace the default homepage of IceRaven if it's possible...

**Comment by krystian3w** [comment]
Other idea #684

**Comment by akliuxingyuan** [comment]
firefox android currently not support custom new tab or homrpage
