### ISSUE TITLE
I hope the browser has built-in download management

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#42]
### What is the user problem or growth opportunity you want to see solved?
I hope the browser has built-in download management
Because there is no built-in download management
### How do you know that this problem exists today? Why is this important?
 I have no way to know which files have been downloaded using the browser
### Who will benefit from it?
All the people who always download files.

**Comment by interfect** [comment]
I think we just have to turn this on in our release builds.

https://github.com/interfect/fenix/blob/5140df01a5344021ddcd8e1d08eacdc74df623c8/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt#L49-L52

**Comment by interfect** [comment]
OK, this ought to be in the next build.
