### ISSUE TITLE
Extensions Request

### ISSUE THREAD

**Issue by vjrmy** [fork-maintainers/iceraven-browser#422]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

Hello, I'd like to request the following add-ons for the iceraven collection:

1.  FastForward https://addons.mozilla.org/en-US/firefox/addon/fastforwardteam/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=collection
Because Universal Bypass is unmaintained and FastForward is a continuation of this project.

2. Privacy Pass https://addons.mozilla.org/en-US/firefox/addon/privacy-pass/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=collection
 Privacy Pass allows a user to bypass CAPTCHAs like Cloudflare captcha page and provides a better visitor experience for Cloudflare-protected websites

3. Buster: Captcha Solver for Humans https://addons.mozilla.org/en-US/firefox/addon/buster-captcha-solver/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=collection
 Buster is a Firefox extension which helps you to solve difficult captchas by completing reCAPTCHA audio challenges using speech recognition. So we can rapidly solve captchas

Thank You

**Comment by krystian3w** [comment]
Other idea #684
