### ISSUE TITLE
1: It is recommended that installed components be displayed at the top or bottom of the menu. 2: Can remember the last selected desktop mode or mobile mode. 3: The video playback loading function is enhanced. The current version often stops loading after playing for a period of time.

### ISSUE THREAD

**Issue by ashlevhj** [fork-maintainers/iceraven-browser#426]
Iceraven Browser iceraven-1.13.0 
1: It is recommended to put the add-on folder into the settings, and then display the installed components at the top or bottom of the menu, so that it is more convenient to use the plug-in. 2: if you want to add a function of default desktop mode, the current function can only be valid on the current page. After creating a new tab, you must click desktop mode again, so sometimes it is easy to make the error of switching to desktop mode, For example, when watching a video, the mobile phone mode will stop loading after watching it for a period of time. Unless it is switched to desktop mode or played on MX player with "external video player", it will not stop loading. There are many scripts that can only run in desktop mode, so you need to make a default or remember the last selected mode, After that, create a new page or click the page Jump to continue the previous mode. 3: The playback and loading speed of mobile mode video is enhanced. When viewing web video with the browser, it often stops loading after playing for a few minutes, even if the automatic playback function is turned on. This phenomenon will not occur when viewing that video on the computer.

**Comment by interfect** [comment]
I'm going to close this because this is about 4 different issues and I think a few of them are duplicates or not really likely to be due to Iceraven's changes.

If any of these are still problems/suggestions, please open *each* of them as separate issues.
