### ISSUE TITLE
[webcontent]inoreader.com

### ISSUE THREAD

**Issue by xfdyd** [fork-maintainers/iceraven-browser#435]
inoreader.com上面，左划，页面会隐藏到左边。浏览订阅时，页面下方的工具条可以被向上拖动，这都是不正常的，会无法使用。

### Device information

* Android device: 7
* Fenix version: 1.15

**Comment by xiaopangju** [comment]
请使用英语报告问题，谢谢。

please report this in English.

**Comment by akliuxingyuan** [comment]
move to #480
