### ISSUE TITLE
[Add-on request]  Add these add-on

### ISSUE THREAD

**Issue by 0xTyagi** [fork-maintainers/iceraven-browser#44]
1.  https://addons.mozilla.org/en-US/android/addon/android-pdf-js/

2. https://addons.mozilla.org/en-US/android/addon/httpz/

3. https://addons.mozilla.org/en-US/android/addon/resultscroller

4. https://addons.mozilla.org/en-US/android/addon/nitter-redirect/

**Comment by interfect** [comment]
OK, these are in.
