### ISSUE TITLE
libredirect

### ISSUE THREAD

**Issue by ilya-fedin** [fork-maintainers/iceraven-browser#441]
Would be really nice to have https://addons.mozilla.org/ru/firefox/addon/libredirect/

**Comment by gigglylo** [comment]
It's a more maintained fork of 'privacy redirect' which is already supported in the browser. Hope it'll be available soon

**Comment by marek22k** [comment]
Duplicates: https://github.com/fork-maintainers/iceraven-browser/issues/555, https://github.com/fork-maintainers/iceraven-browser/issues/505, https://github.com/fork-maintainers/iceraven-browser/issues/471

**Comment by krystian3w** [comment]
Other idea #684

**Comment by marek22k** [comment]
I have now created my own addon collection so that I can add addons myself.
