### ISSUE TITLE
Video DownloadHelper Extension can't be installed

### ISSUE THREAD

**Issue by MuhammadBayiz** [fork-maintainers/iceraven-browser#443]
Hi team, I've an issue with the extension support I'm on Android 12 iceraven 1.15 and every time I try to install Video DownloadHelper Extension it says "Failed to install Video DownloadHelper".

**Comment by Miraclegabriel** [comment]
Me too, still no one is talking about it. I think I will switch back to chrome. I can't even sync my book mark to this browser
