### ISSUE TITLE
[Bug]: Allow for inserted urls to open in current tab

### ISSUE THREAD

**Issue by malopez00** [fork-maintainers/iceraven-browser#447]
### Steps to reproduce

1. Have a tab open
2. Write any url in the url bar
3. Press Enter

### Expected behaviour

The desired url should open in the same tab

### Actual behaviour

A new tab with the desired url opens

### Device name

Oneplus 8T

### Android version

Android 11

### Firefox release type

Firefox

### Firefox version

96.0.15

### Additional information

The configuration option that regulates this behavior (about:config  **browser.urlbar.openintab** ) which is available in the desktop version of firefox is not accesible in Iceraven

**Comment by bauripalash** [comment]
You mean, like while using the tab, and entering the url on that specific tab?

**Comment by malopez00** [comment]
Yes, I mean, if for example, I currently have 14 open tabs, and i write a new url in the current tab's urlbar, I still want 14 open tabs, not 15. The desired website should substitute the current website in the current tab. If I wanted a new tab i would click the new tab button and then write the new url. Thanks

**Comment by bauripalash** [comment]
Somehow, it's working okay on my Iceraven. I am using the latest version. I'm unable to reproduce this bug.

**Comment by malopez00** [comment]
Oh, I am also using the last version and have this issue, Would it be possible to allow access to the about:config browser.urlbar.openintab setting?

**Comment by akliuxingyuan** [comment]
can't reproduce, feel free to reopen if you still have the issue
