### ISSUE TITLE
Moe Niang Encyclopedia picture shows a problem.

### ISSUE THREAD

**Issue by gugulu18** [fork-maintainers/iceraven-browser#449]
Dear developer, Hello, there is a problem with the picture display of Moe Niang Encyclopedia.
![Screenshot_20220228_213557_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/100363053/155993006-215f37cd-6f64-4baa-9896-2b685725b38b.jpg)
I hope you can fix it, version 1.15, thank you.
URL:https://mzh.moegirl.org.cn/Bing%E5%A8%98

**Comment by akliuxingyuan** [comment]
I think it's your network issue
