### ISSUE TITLE
[Feature request] AMOLED black dark theme variant

### ISSUE THREAD

**Issue by e-xception** [fork-maintainers/iceraven-browser#450]
### What is the user problem or growth opportunity you want to see solved?
Lack of a AMOLED black theme as it isn't currently offered by any other privacy-respecting android browser. 

### How do you know that this problem exists today? Why is this important?
The firefox fenix dark theme is a dark blue-ish purple. The only other way to have an AMOLED black privacy-respecting browser is by using firefox before fenix on android which allowed themes, but that comes with security vulnerabilities. 

### Who will benefit from it?
Me and other black theme enjoyers <3

**Comment by EXCIDIVM** [comment]
For what its worth, I support the idea of an AMOLED true black theme. The only open source browser currently supporthing this is Kiwi Browser.

**Comment by akliuxingyuan** [comment]
duplicated #40
