### ISSUE TITLE
Add privacy extensions in the near future

### ISSUE THREAD

**Issue by DMITROSE** [fork-maintainers/iceraven-browser#452]
Please add certain extensions to download from the shared repository and to install in the browser, in order to increase privacy:

1. Censor Tracker
https://addons.mozilla.org/en-US/firefox/addon/censor-tracker/
2. Consent Blocker
https://addons.mozilla.org/en-US/firefox/addon/google-consent/
3. CyDec Security Anti-Fp
https://addons.mozilla.org/en-US/firefox/addon/cydec-security-antifingerprint/
4. FastForward
https://addons.mozilla.org/en-US/firefox/addon/fastforwardteam/
5. Fingerprint Spoofing
https://addons.mozilla.org/en-US/firefox/addon/fingerprint-spoofing/
6. JShelter
https://addons.mozilla.org/en-US/firefox/addon/javascript-restrictor/
7. Trocker
https://addons.mozilla.org/en-US/firefox/addon/trockerapp/
8. Emsisoft Browser Security
https://addons.mozilla.org/en-US/firefox/addon/emsisoft-browser-security/
9. Random User-Agent
https://addons.mozilla.org/en-US/firefox/addon/random_user_agent/

Sincerely, the user of your ICERAVEN browser.

**Comment by emmatebibyte** [comment]
I would definitely love to see jshelter added.
