### ISSUE TITLE
[Bug]: downloaded to 99% and failed.

### ISSUE THREAD

**Issue by HumanMus1c** [fork-maintainers/iceraven-browser#454]
### Steps to reproduce

link:
https://software-download.microsoft.com/download/db/444969d5-f34g-4e03-ac9d-1f9786c69161/19044.1288.211006-0501.21h2_release_svc_refresh_CLIENT_LTSC_EVAL_x64FRE_zh-cn.iso

download will automatically start.  use data or wifi download both will fail at 99%.

### Expected behaviour

i hope it's downloading normally.

### Actual behaviour

failed.

### Device name

Huawei Mate30 pro 5g

### Android version

Android10

### Firefox release type

Firefox

### Firefox version

iceraven-1.15.0 (Build #2015860563), 28893ceab AC: 96.0.15, 0178a6fde9 GV: 96.0.3-20220126154723 AS: 86.2.2

**Comment by akliuxingyuan** [comment]
For big file downloading, I suggest using professional download manager like adm, 1dm+. which supports mulitithread downloading and stop/resume downloading.
