### ISSUE TITLE
Add support for desktop extension install button

### ISSUE THREAD

**Issue by DaRandomCube** [fork-maintainers/iceraven-browser#460]
Add support for desktop extensions like kiwi browser

**Comment by Bardock88** [comment]
Iceraven already supports Desktop extensions, not all, but a good portion of great extensions. For it is a fork of Firefox DayLight (Fenix). Now, if you want to use extensions of your choice, you need to create a Firefox account and select the extensions that will help you in your everyday life.

**Comment by sobaee** [comment]
> Iceraven already supports Desktop extensions, not all, but a good portion of great extensions. For it is a fork of Firefox DayLight (Fenix). Now, if you want to use extensions of your choice, you need to create a Firefox account and select the extensions that will help you in your everyday life.

Hello

Account created and now I am not able to add any desktop extension!
"Add to firefox" is grey in color and even if I am in destop mod it downloads the extension then you can't open them locally

**Comment by interfect** [comment]
If you want to add custom extensions, you need to make an account *and* make a collection, *and* fill in your collection's information under "Customize" in the settings.

I'd love for the same install button as works on Desktop Firefox to work on Iceraven, but I have no idea what Mozilla does to make ti work on Desktop Firefox, or what they cut to break it on Android Firefox, or what we would have to reattach or what holes we would have to punch to make it work in Iceraven.

**Comment by sobaee** [comment]
> If you want to add custom extensions, you need to make an account _and_ make a collection, _and_ fill in your collection's information under "Customize" in the settings.
> 
> I'd love for the same install button as works on Desktop Firefox to work on Iceraven, but I have no idea what Mozilla does to make ti work on Desktop Firefox, or what they cut to break it on Android Firefox, or what we would have to reattach or what holes we would have to punch to make it work in Iceraven.

Great
I appreciate your answer

I figured out this

Thank you for your great browser

THE ONE AND ONLY BROWSER SHOULD ALL USE.

**Comment by Snuupy** [comment]
Hi, bypass paywalls has been removed from the Mozilla addon repo and it is not possible to install local extensions on iceraven.

**Comment by akliuxingyuan** [comment]
you can sideload addon after Iceraven v2.13.2
