### ISSUE TITLE
[Bug]: It is not possible to use custom list of add-ons

### ISSUE THREAD

**Issue by Bardock88** [fork-maintainers/iceraven-browser#462]
### Steps to reproduce

1. Open Iceraven
2. Go in Settings
3. Go to Customize and Slide in Custom Complement List
4. Enter the collection number and subsequently the name of the collection
5. Exit Customize
6. Click on Back ←
7. Click ︙ e go to extensions and see if there was changes to the list of extensions

### Expected behaviour

Should work without problems Changing custom list. Because the previous version: Iceraven 1.14.0 worked correctly.

### Actual behaviour

Is not running the custom list swap function

### Device name

Asus ZB602KL

### Android version

Android 8.1

### Release type

Iceraven based in Firefox Stable

### Firefox version

96.3.0 (Iceraven 1.15.0)

### Device logs

None

### Additional information

https://user-images.githubusercontent.com/102046116/159401453-d50bb5ec-a1de-4c85-a6d3-28abdcaddf1e.mp4

**Comment by bauripalash** [comment]
Same as #440

**Comment by interfect** [comment]
This is indeed a duplicate.
