### ISSUE TITLE
Add-on request: Consent-O-Matic

### ISSUE THREAD

**Issue by RAPXT** [fork-maintainers/iceraven-browser#464]
https://addons.mozilla.org/de/firefox/addon/consent-o-matic/

It is designed to answer cookie consent banner how you're defined it at initial setup. It should allow to automatically block or accept all cookies without you having to interact with the consent banner.

Thank you! :)

**Comment by MaximilianEmel** [comment]
I'd love to have this added as well.

**Comment by interfect** [comment]
I've added this to the list.
