### ISSUE TITLE
[Bug] Fenix team decided to drop Android Kit-Kat (4.4.4, API level 19)

### ISSUE THREAD

**Issue by KOLANICH** [fork-maintainers/iceraven-browser#47]
## Steps to reproduce

Try to install on Kit-Kat

### Expected behavior

It should be installed and work.

### Actual behavior

It cannot be installed.

### Device information

* Android device: any 4.4.4

**Comment by interfect** [comment]
I'm not sure that we can follow Mozilla as closely as I want to and maintain Kit-Kat support. We can take a PR that brings Kit-Kat support back, but as soon as Mozilla adds some new code that uses post-Kit-Kat features, we won't be able to merge without re-doing some of that work at that point, or bringing the API level back up again.

What is there in the app right now that relies on a higher API?

**Comment by KOLANICH** [comment]
At least [Android Components Library](https://github.com/mozilla-mobile/android-components) depends on Lollypop.

For more info downgrading `minSdkVersion` and running `lint` may be (or may not, I am not really an Android dev, just googled the solution) be helpful.
