### ISSUE TITLE
Add libredirect to Add-on collection

### ISSUE THREAD

**Issue by woojoo666** [fork-maintainers/iceraven-browser#471]
[LibRedirect](https://github.com/libredirect/libredirect) ([add-on link](https://addons.mozilla.org/en-US/firefox/addon/libredirect/)) is an alternative to [Privacy Redirect](https://github.com/SimonBrazell/privacy-redirect) and is more actively maintained. It also supports a lot more alternative front-ends, like Piped (for Youtube), Proxitok (for TikTok), Rimgo (for Imgur), and Scribe (for Medium). It also has a button for quickly switching instances

**Comment by Bardock88** [comment]
> [LibRedirect](https://github.com/libredirect/libredirect) ([add-on link](https://addons.mozilla.org/en-US/firefox/addon/libredirect/)) is an alternative to [Privacy Redirect](https://github.com/SimonBrazell/privacy-redirect) and is more actively maintained. It also supports a lot more alternative front-ends, like Piped (for Youtube), Proxitok (for TikTok), Rimgo (for Imgur), and Scribe (for Medium). It also has a button for quickly switching instances

I understand that not only you, me, [Interfect](https://github.com/interfect) and other people want more extensions, which work on this fork of FF Fenix, to be added to the custom list, but in order not to increase the list of "issues", as there is already a topic just for this subject => [link to "issue"](https://github.com/fork-maintainers/iceraven-browser/issues/63)) is for discussing which extensions work, need be added or need to be removed from the custom list, take a look at it, you'll enjoy the discussion of ideas 👍.

**Comment by woojoo666** [comment]
gotcha, ok I'll close this then and copy my comment over
