### ISSUE TITLE
Chameleon extension issue

### ISSUE THREAD

**Issue by mmtech2012** [fork-maintainers/iceraven-browser#473]
As you can see 
![Screenshot_20220508-002309_Iceraven](https://user-images.githubusercontent.com/33870623/167269880-ddcaeca4-0db0-4740-b4bf-9bf48e342d7d.png)

some settings need additional permission but when hit "grant permission" head me to about extension page 
![Screenshot_20220508-002316_Iceraven](https://user-images.githubusercontent.com/33870623/167269899-38b3d434-7492-42c8-8c8b-3fb03bc10b22.png)

and tell something about install legacy version using github.
Since iceraven doesn't support install extension using file so it's impossible to doing so.
Thank you in advance.

**Comment by akliuxingyuan** [comment]
you can sideload addon after Iceraven v2.13.2
