### ISSUE TITLE
(Extension installation)(Request/Fix)

### ISSUE THREAD

**Issue by ELKecham** [fork-maintainers/iceraven-browser#476]
Please some extensions not installing anymore ... in past versions of firefox/and ice raven ive managed to install using downloaded archive from mozilla addons site .,.. and even if i create one collection and do it my self the extension dont install anymore (buster captcha for humans) for example ,.. and new extensions like (fastfoward) are missing from the download list .... so if there a way to download the xpi file from mozilla addons and manually install will be great ... cheers

**Comment by Bardock88** [comment]
> Please some extensions not installing anymore ... in past versions of firefox/and ice raven ive managed to install using downloaded archive from mozilla addons site .,.. and even if i create one collection and do it my self the extension dont install anymore (buster captcha for humans) for example ,.. and new extensions like (fastfoward) are missing from the download list .... so if there a way to download the xpi file from mozilla addons and manually install will be great ... cheers

There is already a topic about extensions failures, this one => https://github.com/fork-maintainers/iceraven-browser/issues/63 < next time you have something related to extensions, please use it, because it makes it easier for other contributors to help.
