### ISSUE TITLE
[Bug]Stylus in the add-on list lacks setting items.

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#48]
Stylus in the add-ons list can only be installed.
However, it cannot be used because there is no setting item.

**Comment by linsui** [comment]
There is no such item in Firefox desktop. You can open any website and access settings from Add-ons -> Stylus -> Option .

**Comment by interfect** [comment]
I'm going to close this as it sounds like the item isn't supposed to be there in the first place. Also, if it were, it would be a bug for Stylus (probably), or maybe for upstream Mozilla Fenix (in the context of a reproduction where you sideload the add-on into their debug build with the web extension development tools).
