### ISSUE TITLE
Autosort Bookmarks

### ISSUE THREAD

**Issue by drewdroid** [fork-maintainers/iceraven-browser#485]
It's impossible to sort my mobile bookmarks. Every time I add one, it goes to the very bottom of my list and then I have to scroll all the way down to find it.

I want to be able to sort them automatically, reverse chronologically with the new ones at the very top. There's a Firefox add-on that does this but it's not available for Ice Raven.

https://addons.mozilla.org/en-US/firefox/addon/auto-sort-bookmarks/

Strangely, old versions of Firefox mobile (68.10.1) sorted bookmarks this way automatically. So maybe there's an internal switch that was reversed.

**Comment by Hubfront** [comment]
I tried this addon on Firefox mobile Nightly months ago, but it was not working. I am using it on Desktop firefox for the same reason as drewdroid described above: to resort Firefox mobile bookmarks.

Update: Auto-sort-bookmarks still does not work with Firefox nightly, ver. 103

**Comment by akliuxingyuan** [comment]
move to #327
