### ISSUE TITLE
[Bug]: Can't scroll down in Reddit

### ISSUE THREAD

**Issue by ajsmsg78** [fork-maintainers/iceraven-browser#487]
### Steps to reproduce

Go to www.reddit.com 
Go to any thread
Scrolling down doesn't work
Scrolling down works if you set it to desktop mode

### Expected behaviour

Page should scroll down

### Actual behaviour

Scrolling down is non responsive

### Device name

Galaxy S22 Ultra, Pixel 6 Pro, Poco F3

### Android version

Android 12.1

### Firefox release type

Firefox

### Firefox version

IceRaven 1.16.1

**Comment by eladkarako** [comment]
not a solution, just a workaround for now:  
change the subdomain to `old.`  
(I.E. `www.reddit.com` to `old.reddit.com`, same url afterwards).
