### ISSUE TITLE
Please add an add-on"在线词典助手"or English name"online dictionary helper" to add-on store

### ISSUE THREAD

**Issue by Adam367** [fork-maintainers/iceraven-browser#488]
Please add an add-on"在线词典助手"or English name"online dictionary helper" to add-on store

**Comment by interfect** [comment]
I've put [this](https://addons.mozilla.org/en-US/firefox/addon/online-dictionary-helper) on the list.

**Comment by Adam367** [comment]
Very appreciated it, would you mind putting Windscribe(a VPN tool) on list ?
