### ISSUE TITLE
Please Consider A Printing Option

### ISSUE THREAD

**Issue by Davy49** [fork-maintainers/iceraven-browser#489]
Hi,
I realize that firefox for android doesn't offer a printing option of any kind, is it possible that a printing option might be added to iceraven sometime hopefully in the near future ?
Thanks

**Comment by interfect** [comment]
I have no idea how to do this. It might need hooks in GeckoView, and it would also need someone who knows about how printing works on Android to actually build out the print menu item and invoke whatever Android APIs are used to print stuff.

**Comment by CookieJarApps** [comment]
Currently, it's not really possible. My GeckoView based browser uses a bit of a hack and uses a build in add-on to get the web page source code, render it in a WebView and print that, but it's not a great solution. Mozilla are working on printing for GeckoView though - they recently added a feature to it to export pages as a PDF (which isn't exposed in Mozilla Android Components yet, but there is a pull request for it under review) which is a step closer, so it shouldn't be too long until it's possible.

**Comment by Davy49** [comment]
Thanks so much for all of the responses.
