### ISSUE TITLE
[Bug]: Not working 120Hz

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#490]
### Steps to reproduce

1. Open any site;
2. Enjoy the pain at 60Hz.

### Expected behaviour

Lags.

### Actual behaviour

Lags.

### Device name

realme GT Neo2

### Android version

Android 11 / 12

### Firefox release type

Firefox

### Firefox version

1.16.1

**Comment by interfect** [comment]
How does the Realme GT Neo2 decide whether to draw any given app at 60 hz or 120 hz? Is it one of those devices that just has a list of apps to run at high refresh rate?

**Comment by ghost** [comment]
> 

I have 2 phones on hand: realme GT Neo2 and POCO X4 GT, where the screen is 144Hz, and on it I do not experience problems with rendering sites. I think it's still a matter of realmeUI, but I think that on your part it is possible can be used.
