### ISSUE TITLE
Custom Addons and Unhook

### ISSUE THREAD

**Issue by ToTheMoon1234** [fork-maintainers/iceraven-browser#491]
* Unhook addon works perfectly in Firefox Nightly/Fennec but isn't available on iceraven. (#396)
* Using custom addon list to add Unhook(or any other extension) via settings->customize doesnt work, the extensions don't show up in the list.
* Please consider fixing custom add-on lists or/and adding Unhook (popular and useful addon for youtube)

**Comment by interfect** [comment]
This is [Unhook: Remove YouTube Recommended Videos Comments](https://addons.mozilla.org/en-US/firefox/addon/youtube-recommended-videos/), right?

I've added it to the list. It might take a while to show up due to local caching of the list.
