### ISSUE TITLE
Addon Request: Shinigami Eyes

### ISSUE THREAD

**Issue by erydactyl** [fork-maintainers/iceraven-browser#497]
Please can Shinigami Eyes be added to the addon repository. Here is their Github repository: [https://github.com/shinigami-eyes/shinigami-eyes](https://github.com/shinigami-eyes/shinigami-eyes)

**Comment by Candlemass** [comment]
Unnecessary.

How about growing a thicker skin instead of being an over sensitive Karen instead?

**Comment by krystian3w** [comment]
Other idea #684 follow version in store: https://addons.mozilla.org/en-US/firefox/addon/shinigami-eyes/
