### ISSUE TITLE
Expose website domains for android password managers

### ISSUE THREAD

**Issue by adityasubathu** [fork-maintainers/iceraven-browser#5]
Right now, using any android password manager shows the autofill domain as the app name for iceweasel. It would be better if the actual website name was used for autofill from external password managers

**Comment by interfect** [comment]
This would be a good idea. Do you have any idea what Mozilla's builds could be doing in this regard that mine aren't?

I was digging around in the docs for... I think it was Bitwarden? and I noticed that for at least that password manager, it's not so much a matter of claiming to be a browser and exposing the page URL as it is being on their app's list of actual (and trustable with passwords) browsers.

**Comment by adityasubathu** [comment]
So I did some digging on BitWarden (I use Bitwarden) and yes, the BW team needs to add this browser's URI to it's list of trusted browsers. Given that your browser is new and what the first release description is, I don't think it'll qualify for that. But maybe in the future, eh? Since you are using the latest (at least for now) codebase from mozilla, you shouldn't need to make any changes on your end to fix this issue, so I'll close it and open another one on the BitWarden bug tracker

**Comment by adityasubathu** [comment]
https://community.bitwarden.com/t/add-iceweasle-to-androids-trusted-browsers-list/13951
