### ISSUE TITLE
Warn before open an external app

### ISSUE THREAD

**Issue by liyafe1997** [fork-maintainers/iceraven-browser#500]
Some websites always try to open their app, even I dont want, I just want to browse it on the browser.

In the Private Mode, every time a website tries to open an app, the browser always asks for the user.

But in the normal mode, it should be some settings like this. I even tried about:config with something like "network.protocol-handler.warn-external" but nothing works. (But seems this kind of settings works at desktop version of firefox).

**Comment by citizenserious** [comment]
![0](https://user-images.githubusercontent.com/62773866/184885280-88089af8-6746-4d82-97a4-f83fe88faae8.jpg)

**Comment by liyafe1997** [comment]
> ![0](https://user-images.githubusercontent.com/62773866/184885280-88089af8-6746-4d82-97a4-f83fe88faae8.jpg)

This option has been turned off. Some website use javascript to automatically open their app without asking the user. This option can not prevent that kind of behaviors.

**Comment by citizenserious** [comment]
Sounds like a problem Mozilla has to fix to me. Maybe uMatrix or NoScript is an option for you.

**Comment by FSpark** [comment]
The problem is in [android-components](
https://github.com/mozilla-mobile/android-components) and it seems that Mozilla won't fix it. 

So I cracked this last year and it has been working fine.

https://fspark.me/archives/prevent-Firefox-Android-auto-open-APP-break-inaccessibility-of-risky-websites.html

**Comment by trimechee** [comment]
@FSpark i see in your site "There is no god. Wonderful new world!3", that's disappointing shocking, where will your soul go after death? all the delicious food you eat, your body, is it by hazard? what are you going to say when I say your website is the result of hazard ?!

**Comment by FSpark** [comment]
@trimechee  I'm so sorry, I really didn't mean to offend the religious beliefs of you theists.

### Source

From the theme song of the science ADV game Steins;Gate 0: [Fátima](https://steins-gate.fandom.com/wiki/F%C3%A1tima#English_)

Linking the context of the lyrics and the background of the game believes that you will be able to have a complete and profound understanding of this sentence.

### My intentions

* I have finally escaped strict internet censorship by setting up my blog server abroad.

 * As the philosopher Nietzsche famously said, ["God is dead"](https://en.wikipedia.org/wiki/God_is_dead), I believe that the saviour of mankind can only be himself.

* "Wonderful new world" is actually not wonderful. In fact, its deep reference is the dystopian novel [Brave New World](https://en.wikipedia.org/wiki/Brave_New_World), which depicts a society that loses its beliefs and entertains to death.

I admit that the phrase does seem abrupt away from these contexts, and if it does cause you intolerable distress, I would consider a more appropriate slogan.

**Comment by trimechee** [comment]
Thanks for your polite response :) I think it will be great to only modify the sentence to avoid offending, and if philosopher Nietzsche said, "God is dead", then "Nietzsche is dead" and buried underground and his body has been putrified and eaten by the glasses and God is not dead, and certain humanity, if she is too vain and society that loses its beliefs and its religious and moral values, society  risks sinking into decadence and depression and conflict, may God guide us to the straight path of unity and monotheism and protect us from misguidance, amen !

**Comment by trimechee** [comment]
Si if i well understand, in the novel Brave new world, the society becomes dystopian because of the loss and oblivion of ancestral religious moral values, that's seems interisting and therefore the novel is the antithesis of "Wonderful new world" because new world is not really wonderful world !

**Comment by akliuxingyuan** [comment]
<img width="30%" src=https://user-images.githubusercontent.com/53224655/232219184-78333a1c-27fd-41e3-a60c-048a8264e56d.png>

seems fixed in latest Fenix
