### ISSUE TITLE
Suggestion regarding trackers

### ISSUE THREAD

**Issue by Ygarr** [fork-maintainers/iceraven-browser#507]
The app show such tracker. Suggest to consider removing them
![temptodelsession-attachment-2022-09-11-073540](https://user-images.githubusercontent.com/14309871/189512859-b5239288-a3b9-4d6e-af04-d5e818bf3405.jpeg)

**Comment by akliuxingyuan** [comment]
please read project's [README.md](https://github.com/fork-maintainers/iceraven-browser#readme)
> In addition, we intend to try to cut down on telemetry and proprietary code to as great of an extent as possible as long as doing so does not compromise the user experience or make the fork too hard to maintain. Right now, we believe that no telemetry should be being sent to Mozilla anymore, but we cannot guarantee this; data may still be sent. Because of the way we have implemented this, the app may still appear to contain trackers when analyzed by tools that look for the presence of known tracking libraries. These detected trackers should actually be non-functional substitutes, many of which are sourced from here. If you catch the app actually sending data to Mozilla, Adjust, Leanplum, Firebase, or any other such service, please open an issue! Presumably any data that reaches Mozilla is governed by Mozilla's privacy policy, but as Iceraven Browser is, again not a Mozilla product, we can make no promises.
