### ISSUE TITLE
Is this project discontinued? 

### ISSUE THREAD

**Issue by blogmangit** [fork-maintainers/iceraven-browser#508]
Since 2 months there's no update has the project discontinued? because firefox has been updated long ago.

**Comment by CharmCityCrab** [comment]
Iceraven updates at a slower pace than Firefox does.

It's not ideal, but right now there is only one developer on the project ( @interfect ), and he works on it for free as a service to the community as he wants to or is able to.

He's expressed a willingness to have volunteers cut updates that merge the latest from upstream with the existing code and customizations on a more regular basis, but so far no one has stepped forward, so we get them when we get them.

I guess the most direct answer to your question is that, no, not having had an update in a while doesn't necessarily mean that the project has been discontinued.  We've gone longer before.  We've also gotten them in much less time before.  My gut says that we can probably expect one soon, but it's really up to the developer.

I still feel like this is by far the best browser available for Android and is worth the tradeoff of getting less frequent updates.  Maybe one day some people will volunteer to help @interfect out and we'll get them more frequently.

**Comment by interfect** [comment]
It's not discontinued. I'm using it right now,  and when I feel like the hackers are going to get me if I don't I make a new build.

If you want a new build sooner, I think you can make a PR for it? Although I've been rebasing now and just moving the `fork` branch, which Github PRs can't quite understand. But anyway, if you can generate a commit that you want released I can look at it and make it a release, or put you in `fork-maintainers` so you can make releases.

**Comment by towfikomar** [comment]
Dead ☠️

**Comment by interfect** [comment]
RIP This Project.

There *should* be a new release building now. I will check back to see if the release automation actually manages to publish it.

**Comment by CharmCityCrab** [comment]
> There _should_ be a new release building now. I will check back to see if the release automation actually manages to publish it.

Release automation didn't publish it, at least not on the main [releases](https://github.com/fork-maintainers/iceraven-browser/releases) page.

**Comment by interfect** [comment]
What seems to be dead is the release auromation's ability to get through
the Gradle build without the Gradle demon crashing for no apparent reason.

I will have to make sure I can do a clean build from a fresh checkout, and
either fix whatever is secretly breaking Github Actions or just publish my
APKs in a release.
