### ISSUE TITLE
Add disable web fonts download function

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#51]
### What is the user problem or growth opportunity you want to see solved?
I hope browser have disable web fonts download function like firefox 68 android
### How do you know that this problem exists today? Why is this important?
Because of the lack of this function, the loading speed of web pages in places with slow network speed is very slow,If the browser has that feature, it can speed up the loading speed of web pages in these areas
### Who will benefit from it?
All people in places with poor internet conditions.

**Comment by linsui** [comment]
uBlock Origin can do that.

**Comment by interfect** [comment]
This could be a useful setting to have.

**Comment by akliuxingyuan** [comment]
https://support.mozilla.org/en-US/questions/1178088
about:config change `gfx.downloadable_fonts.enabled` to false
