### ISSUE TITLE
[Addon request]: StarShell Wallet Beta

### ISSUE THREAD

**Issue by blake-regalia** [fork-maintainers/iceraven-browser#511]
Add-on: https://addons.mozilla.org/en-US/firefox/addon/starshell-wallet-beta/
Source: https://github.com/SolarRepublic/starshell-beta-releases
Website: https://starshell.net/

**Comment by krystian3w** [comment]
Other idea #684

**Comment by akliuxingyuan** [comment]
addon not existed
