### ISSUE TITLE
[Addon request]: NopeCHA: ReCAPTCHA & hCAPTCHA Solver

### ISSUE THREAD

**Issue by sbot50** [fork-maintainers/iceraven-browser#512]
### What is the user problem or growth opportunity you want to see solved?
I'm just too lazy to manually solve captcha's

### How do you know that this problem exists today? Why is this important?
I don't think these fields are supposed to be used for addon requests are they?

### Who will benefit from it?
Everyone

**Comment by krystian3w** [comment]
Other idea #684
