### ISSUE TITLE
[Feature request] Add Brave as a search engine option

### ISSUE THREAD

**Issue by fromtheeast710** [fork-maintainers/iceraven-browser#516]
I have been using Brave search as my default search engine for quite a while so I would like to have it in one of the search engines available by default. Adding it manually means IceWeasel won't display it's icon properly.

I hope you consider this as Brave is an excellent alternative to Google search.

Thank you.

**Comment by Jagazz** [comment]
Check this page out, it's all there. 
https://search.brave.com/default

**Comment by fromtheeast710** [comment]
@Jagazz Yes, I am aware of this. What I meant is that IceRaven should ship with Brave.

**Comment by fromtheeast710** [comment]
@Jagazz Yes, I am aware of this. What I meant is that IceRaven should ship with Brave.

**Comment by akliuxingyuan** [comment]
completed in https://github.com/fork-maintainers/iceraven-browser/commit/3a27fcd26b52740247764fc9b15641a83be4b495
