### ISSUE TITLE
Bookmark issue/Feature request 

### ISSUE THREAD

**Issue by SundaySnooker** [fork-maintainers/iceraven-browser#517]
Newly added bookmarks are added to bottom of the list instead of top like in most browsers and cannot change order of sorting by either date, name or last visited.

Syncing with Firefox desktop, manually sorting the bookmarks and syncing again fixes the list order but doing such task is an annoyance.

Adding better bookmark control would solve the issue.

Iceraven 1.17.0

**Comment by Hubfront** [comment]
This is indeed a bug, but one of fenix on which Iceraven is based.

**Comment by akliuxingyuan** [comment]
move to #327
