### ISSUE TITLE
Default App for Opening html files

### ISSUE THREAD

**Issue by mackeev** [fork-maintainers/iceraven-browser#52]
New FF is no longer suggested to open local html (and suchlike) files. Please make IW announce itself to the system.

**Comment by interfect** [comment]
That sounds like a regression form Fennec for sure.

**Comment by serj-kzv** [comment]
See workaround https://github.com/fork-maintainers/iceraven-browser/issues/281#issuecomment-1088010840

**Comment by akliuxingyuan** [comment]
move to #281
