### ISSUE TITLE
Add addon for icereaven 

### ISSUE THREAD

**Issue by Gibbir** [fork-maintainers/iceraven-browser#520]
I still don't care about cookies https://addons.mozilla.org/en-US/firefox/addon/istilldontcareaboutcookies/
https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies

**Comment by clementwzk** [comment]
this is the most important addon to add since I don't care about cookies was bought by Avast

**Comment by krystian3w** [comment]
Other idea #684
