### ISSUE TITLE
Android 13 Themed Icon

### ISSUE THREAD

**Issue by KibSquib48** [fork-maintainers/iceraven-browser#521]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Iceraven does not support Android 13's themed icon feature and it sticks out like a sore thumb on home screens using the feature

### How do you know that this problem exists today? Why is this important?
I have a home screen with themed icons enabled and almost all of them support it except for Iceraven and Discord (focusing on Iceraven here of course)
![image](https://user-images.githubusercontent.com/33189136/202871305-696a350a-9e55-435b-9f57-44203ce67353.png)

### Who will benefit from it?
People on Android 13 with home screen setups built around themed icons

**Comment by akliuxingyuan** [comment]
completed in https://github.com/fork-maintainers/iceraven-browser/commit/223685cf6df7ac5eb2f2cf49df802e8bb7a59576
