### ISSUE TITLE
Option for toggle ON or OFF "Auto added Shortcut"

### ISSUE THREAD

**Issue by gigachaand** [fork-maintainers/iceraven-browser#525]
![IMG_20221122_213903](https://user-images.githubusercontent.com/96541364/203366595-92be861f-f3d9-41d9-8291-e1283e98dc93.jpg)
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### Who will benefit from it?
Give us a Option where we can enable or disable Shortcut automatically adding to home screen.. currently there is a option for disabling shortcut from home screen but there is a problem on that option if we enable that option then those shortcuts that we manually added also gets hide..plz...fix this sir..🙏 and thank you..😘

**Comment by seniordevel** [comment]
Shortcuts should never be added to the hpmepage automatically (except sponsored is enabled). This is an extremely annoying behavior. It makes my homepage unusable after a short time.

**Comment by ghost** [comment]
感谢添加此功能，希望优化下下载，把下载界面添加
![Screenshot_20231125_204029](https://github.com/fork-maintainers/iceraven-browser/assets/151994842/e5085d10-2e84-4366-9057-8c7fd7e8e8f3)
