### ISSUE TITLE
add a home button like chrome

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#53]
### What is the user problem or growth opportunity you want to see solved?
I hope browser have a home button like chrome
### How do you know that this problem exists today? Why is this important?
It's convenient to back to home page if the browser have that.
### Who will benefit from it?
All the people need home button.

**Comment by interfect** [comment]
I think we also need a concept of a homepage for this. The browser doesn't have one right now. I do know Mozilla has plans like this in upstream, so we'll eventually have it when they do, but we could get it sooner.

**Comment by Daplugg23** [comment]
I think he's referring to this as the homepage. There is currently no way to get back to it without going through multiple clicks.

![Screenshot_20200904-074259_Iceweasel](https://user-images.githubusercontent.com/45342860/92240497-58ba8780-ee82-11ea-9e0e-d75581199f90.jpg)

**Comment by interfect** [comment]
It could go in the tab tray maybe?

See: https://github.com/fork-maintainers/iceraven-browser/issues/112#issue-701673320

**Comment by jesus2099** [comment]
I am not a fan of having another icon that would hide more of the address bar.

It would be better to have the top sites when clicking the address bar (#144), as the desired _homepage_ (I don't have any myself) would most certainly appear in the top sites.

**Comment by Madis0** [comment]
This already exists for a while in upstream Fennec, and is confirmed to exist on Iceraven 1.15.0.

**Comment by interfect** [comment]
Excellent! I'll close out this and the duplicates.
