### ISSUE TITLE
Fork is denoted as "produced by Mozilla" 

### ISSUE THREAD

**Issue by fm-sys** [fork-maintainers/iceraven-browser#535]
I doubt if iceraven is actually produced by Mozilla ;-) 

Maybe we should change that string to be on the save side legally... 

![Screenshot_20221215_154338_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/64581222/207890298-0549ec90-7e81-4f7c-b8c8-8df158ee5df3.jpg)

**Comment by interfect** [comment]
Yeah, that's definitely a lie.

Where is that coming from?

**Comment by fm-sys** [comment]
You find it under `Settings > About iceraven`

**Comment by interfect** [comment]
This seems to be fixed in 1.19.0, at least in English.

**Comment by fm-sys** [comment]
Yes, fixed 👍
