### ISSUE TITLE
Import/Export bookmarks without FF Sync

### ISSUE THREAD

**Issue by HyperCriSiS** [fork-maintainers/iceraven-browser#536]
Hi,

It would be nice to have the possibility to import bookmarks directly from an installed FF version without the sync feature, to make the move to this fork easier. 

Also it would help to be able to do HTML imports/exports.
Unfortunately Mozilla is not able since years to add this simple feature.

Thanks and best regards,
Hyper

**Comment by Miraclegabriel** [comment]
I need this feature so badly, I even sync from my laptop, still my bookmarks isn't displaying in bookmark tab

**Comment by akliuxingyuan** [comment]
move to #103
