### ISSUE TITLE
please update

### ISSUE THREAD

**Issue by mozzaru** [fork-maintainers/iceraven-browser#541]
some can't be touched, meaning there are points that the browser can't touch, my touchscreen is normal in other browsers it's normal, and are there any more updates? .please make it even smoother, thanks

Browser iceraven last

**Comment by akliuxingyuan** [comment]
> some can't be touched

what does it mean? does firefox do same behavior?

**Comment by mozzaru** [comment]
Yes in Firefox it's the same,
When moving the apk from recent apps there is a black blank, but it's faint, the same is true in the Firefox play store 

I use gesture navigation, but if I use buttons it might be normal, maybe

**Comment by akliuxingyuan** [comment]
I think you better report a bug on site [bugzilla](https://bugzilla.mozilla.org/describecomponents.cgi?product=Fenix) since firefox have same issue :)
don't forget provide OS infomation and a picture present the issue
I guess is your OS/launcher issue

**Comment by mozzaru** [comment]
That's it and that's how it is hehe
