### ISSUE TITLE
[Bug]: 无法更换壁纸

### ISSUE THREAD

**Issue by klcb2010** [fork-maintainers/iceraven-browser#546]
### Steps to reproduce

The wallpaper cannot be changed in versions 1.18 and above. After changing the wallpaper in 1.17, upgrading to 1.18 or 1.19 will be prompted, and the wallpaper will become the default

![Screenshot_2023-01-09-19-57-14-661_io github forkmaintainers iceraven](https://user-images.githubusercontent.com/32628414/211303333-f9247eed-d918-40bc-9d77-e8c7f2ebc769.jpg)

**Comment by akliuxingyuan** [comment]
same as https://github.com/fork-maintainers/iceraven-browser/issues/571
