### ISSUE TITLE
[Bug] tab tray: wrong side with bottom nav bar

### ISSUE THREAD

**Issue by B0pol** [fork-maintainers/iceraven-browser#55]
<img src="https://i.ibb.co/zFkVNCk/Screenshot-20200903-094043-Iceweasel.png" width="300">

**Comment by abhijitvalluri** [comment]
This is not a bug, it is a feature! The intention was to allow the new tab button (+) and the private tabs button, etc. be more easily accessible from the bottom of the screen. Presumably, if you chose the bottom position for the toolbar, you would prefer these to be more easily accessible. This feature was implemented in #49. 

Would you prefer the old layout instead of this?

**Comment by abhijitvalluri** [comment]
#65 addresses this issue!

**Comment by B0pol** [comment]
Nice. Thank you for #65, @abhijitvalluri

**Comment by adityasubathu** [comment]
Plus button isn't appearing when private mode is enabled

![Screenshot_20200904-145837](https://user-images.githubusercontent.com/16309657/92224363-54608f80-eebf-11ea-9780-14674adff832.jpg)
![Screenshot_20200904-145829](https://user-images.githubusercontent.com/16309657/92224372-59254380-eebf-11ea-925b-240c217d9aa3.jpg)
@abhijitvalluri

**Comment by abhijitvalluri** [comment]
I cannot reproduce the issue. Is it the Floating action button or the plus button in the tray that is not visible? For me, it is showing up correctly.

**Comment by adityasubathu** [comment]
> I cannot reproduce the issue. Is it the Floating action button or the plus button in the tray that is not visible? For me, it is showing up correctly.

First enable private mode with the dedicated button in the top right. Then try adding a new tab

**Comment by abhijitvalluri** [comment]
> First enable private mode with the dedicated button in the top right. Then try adding a new tab

Ah I see the problem. It is not invisible, but the color of the button is white! So in light theme it becomes invisible, but you can still click it on the right side. In dark theme this is not an issue as the button is always visible as a white + sign on a dark background! 

I will need to fix this.

**Comment by abhijitvalluri** [comment]
This should not yet be closed. @adityasubathu's bug reported above (https://github.com/fork-maintainers/iceweasel/issues/55#issuecomment-687036446) still needs to be fixed and it is fixed in #69. Although to be fair that is a separate issue and so a new issue should have been raised instead.
