### ISSUE TITLE
[Bug]: Please remove this Google Play rating option 

### ISSUE THREAD

**Issue by gigachaand** [fork-maintainers/iceraven-browser#554]
### Steps to reproduce

Go to Settings -> About

### Expected behaviour

![IMG_20230118_231426](https://user-images.githubusercontent.com/96541364/213256643-4b9c7c62-392f-43f0-b69e-4ed10beaea7c.jpg)

### Actual behaviour

😛

### Device name

Xiaomi Mi Max 2

### Android version

Android 7

### Firefox release type

Firefox

### Firefox version

108.2.0

### Device logs

😎

### Additional information

![IMG_20230118_231426](https://user-images.githubusercontent.com/96541364/213257407-f3452855-fb4e-4ec1-9a04-6502483e15bc.jpg)

**Comment by akliuxingyuan** [comment]
completed in https://github.com/fork-maintainers/iceraven-browser/releases/tag/iceraven-2.0.3
