### ISSUE TITLE
Add-on suggestion: LibRedirect

### ISSUE THREAD

**Issue by RoonMoonlight** [fork-maintainers/iceraven-browser#555]
Addon Link: https://addons.mozilla.org/en-US/firefox/addon/libredirect/

Redirects YouTube, Twitter, Instagram... requests to alternative privacy friendly frontends and backends.

**Comment by krystian3w** [comment]
https://github.com/fork-maintainers/iceraven-browser/issues/441 #505 #601 and Other idea #684
