### ISSUE TITLE
Tab tray: let people disable compact tabs

### ISSUE THREAD

**Issue by B0pol** [fork-maintainers/iceraven-browser#56]
### What is the user problem or growth opportunity you want to see solved?
I don't like compact tabs, and I didn't liked them in fennec too

> f you want your new-Android-style floating plus button back, demand a setting for it from @abhijitvalluri or someone else who knows how to do Android UI stuff.

Ping @abhijitvalluri
### How do you know that this problem exists today? Why is this important?
Because three days ago, the update made compact tab **mandatory**, it should be optional, or at least we can disable it.
### Who will benefit from it?
People who don't like compact tabs

**Comment by abhijitvalluri** [comment]
#65 addresses this issue!
