### ISSUE TITLE
Block ads with firefox focus

### ISSUE THREAD

**Issue by trimechee** [fork-maintainers/iceraven-browser#563]
Hello, thank you very much for this amazing wonderful browser 🥇 💯 

I have uggestion please, can Iceraven -browser could be based on firefox focus browser beacause i heard that focus browser block natively  ads and trackers ! Thank you !

https://www.mozilla.org/en-US/firefox/browsers/mobile/focus/

**Comment by akliuxingyuan** [comment]
no plan for that, you can try to develop it based on focus, if it's good to use, then we can publish as fork-maintainers organization project

**Comment by trimechee** [comment]
Ineresting, thank you :) Sadly, i am not developer, but i found another browser and may be some ot its features can be incorporated in our beloved Iceraven- browser : 

"This is a privacy oriented and deblobbed web browser based on Mozilla technology. It enables many features upstreamed by the [Tor Uplift project](https://wiki.mozilla.org/Security/Tor_Uplift) using preferences from the [arkenfox-user.js project](https://github.com/arkenfox/user.js). It is recommended to install 'uBlock Origin'.

https://gitlab.com/divested-mobile/mull-fenix

**Comment by akliuxingyuan** [comment]
Yes, Mull is also a Fenix based browser like Iceraven, it build with https://github.com/arkenfox/user.js for deeper privacy and security consideration.

If someone volunteers helping to setup for Fdroid build (talked in #26), I think we can import https://github.com/arkenfox/user.js too.

**Comment by trimechee** [comment]
@akliuxingyuan  Oups , it seems that Firefox Focus has changed and don't block ads anymore,  or maybe it not blocks ads since the begining, but block only trackers....

**Comment by CharmCityCrab** [comment]
Just as a potential alternative user.js to arkenfox to consider- betterfox:

https://github.com/yokoffing/Betterfox/blob/main/README.md

The basic concept of betterfox is that it makes changes to protect your privacy, but rates useability as bigger (apparent) concern than arkenfox, and so might be an in-between option between shipping user.js as-is and going all the way to arkenfox (Which enhances privacy, but also breaks some sites).

The other thing that's worth noting here is that the arkenfox page itself notes that "the arkenfox user.js is made specifically for desktop Firefox. Using it as-is in other Gecko-based browsers can be counterproductive, especially in the Tor Browser.".  

I'm aware that that Mull has been using it anyway for years, so maybe that is an overly cautious disclaimer on the arkenfox maintainer's site.

I am not advocating for or against any particular path.  I just wanted to mention some things to consider that I haven't seen brought up yet.

**Comment by trimechee** [comment]
Interesting ! @CharmCityCrab  Thank you so much for these important explanations and recommendations :)
