### ISSUE TITLE
[Feature] Respect the theme color when the page is loading

### ISSUE THREAD

**Issue by unixfox** [fork-maintainers/iceraven-browser#57]
### What is the user problem or growth opportunity you want to see solved?

When setting the theme to black, not all the interface is dark. For instance the background of the page when the page is loading is still white.

![Peek 2020-09-03 12-38](https://user-images.githubusercontent.com/4016501/92098974-9e277800-ede2-11ea-8684-cb91708aea11.gif)

### How do you know that this problem exists today? Why is this important?

It's quite important for not having a straight white screen each time a new page is loading when browsing the web in a dark environment.

Chrome on Android has already implemented this behaviour of having a black background when setting "Force dark mode for web contents" to enabled.

![Screenshot_20200903-124658_Bromite_1_1](https://user-images.githubusercontent.com/4016501/92099852-b0ee7c80-ede3-11ea-81f8-3407b53a09ca.png)

### Who will benefit from it?

The people that use their phone in a dark environment.

**Comment by interfect** [comment]
This would be nice, but probably requires some plumbing into android-components.

**Comment by ale82to** [comment]
there's an option in secret setting: wait ultil first paint or with root is possible to use both userchrome.css and usercontent.css.
