### ISSUE TITLE
无法更换主题

### ISSUE THREAD

**Issue by hanwuli** [fork-maintainers/iceraven-browser#571]
从1.70.0后就一直无法更换壁纸，现在都更新几个版本了，还是这样，能修一下吗？
Can you fix the issue that can't change the wallpaper happened after version 1.70..0 ?

**Comment by klcb2010** [comment]
提过一次  作者很慢  估计没时间修  以后看akliuxingyuan会不会解决这个问题

**Comment by hanwuli** [comment]
> 提过一次  作者很慢  估计没时间修  以后看akliuxingyuan会不会解决这个问题

这几个版本他没好好做，转到Firefox Nightly了，感觉还行。

**Comment by klcb2010** [comment]
> > 提过一次  作者很慢  估计没时间修  以后看akliuxingyuan会不会解决这个问题
> 
> 这几个版本他没好好做，转到Firefox Nightly了，感觉还行。

每夜版有不可预知的错误  我遇到过一次  怕了  壁纸这个问题 所有变种版都有 估计是拉取的时候引用了隐私脚本导致

**Comment by akliuxingyuan** [comment]
Mozilla hide the remote Wallpaper URL, can't fix currently :(
https://github.com/fork-maintainers/iceraven-browser/blob/859655c085d0ff2e6c356f895fd498f455710ad3/app/build.gradle#L438-L440

**Comment by hanwuli** [comment]
> Mozilla hide the remote Wallpaper URL, can't fix currently :(
> https://github.com/fork-maintainers/iceraven-browser/blob/859655c085d0ff2e6c356f895fd498f455710ad3/app/build.gradle#L438-L440

👌

**Comment by akliuxingyuan** [comment]
@klcb2010 @hanwuli
最新版中修复了 https://github.com/fork-maintainers/iceraven-browser/releases/tag/iceraven-2.2.0
fixed in latest release https://github.com/fork-maintainers/iceraven-browser/releases/tag/iceraven-2.2.0
