### ISSUE TITLE
The video download helper add-on keep failing to install[Bug]: 

### ISSUE THREAD

**Issue by Miraclegabriel** [fork-maintainers/iceraven-browser#577]
### Steps to reproduce

Go to add on tab
Locate video download helper add-on

### Expected behaviour

The addon should download successfully 

### Actual behaviour

Instead it shows fails to install addon

### Device name

samsung s21 ultra 

### Android version

android 13

### Firefox release type

Firefox Nightly

### Firefox version

1.21.2 iceraven

**Comment by akliuxingyuan** [comment]
If you look the add-on detail page on AMO, It says `Works with firefox 42.0 and later`, so it can't be install on  android platform, I believe that you can find some alternatives
