### ISSUE TITLE
video downloadhelper cannot be downloaded at version 1.7.1

### ISSUE THREAD

**Issue by sankhababu** [fork-maintainers/iceraven-browser#581]
video downloadhelper cannot be downloaded at version 1.7.1

_Originally posted by @mohibo in https://github.com/fork-maintainers/iceraven-browser/issues/63#issuecomment-815733896_
          
The problem remains still now.

**Comment by ILeMeNiiz** [comment]
The description mentions that some addons do not work. I think it is the same for me that the downloader generally does not work. The addons are not officially all supported so some work and some do not
