### ISSUE TITLE
nx-enhanced

### ISSUE THREAD

**Issue by michael1900** [fork-maintainers/iceraven-browser#583]
Can you add this addon in the list: https://addons.mozilla.org/it/firefox/addon/nx-enhanced/ ?

Thanks

But why it can't possible install direclty from addon page?

**Comment by krystian3w** [comment]
Mozilla block this, but unlocked for 100+ addons in Beta/Nightly: #684

**Comment by akliuxingyuan** [comment]
addon not existed
