### ISSUE TITLE
[Add-on Request] Shinigami Eyes

### ISSUE THREAD

**Issue by lexi-xo** [fork-maintainers/iceraven-browser#585]
please add the shinigami eyes add-on if possible. thanks! https://addons.mozilla.org/en-US/firefox/addon/shinigami-eyes/

**Comment by agent-guardian** [comment]
They also have a experimental android version.
https://shinigami-eyes.github.io/#install-on-mobile

**Comment by krystian3w** [comment]
Other idea #684
