### ISSUE TITLE
No save and autofill addresses 

### ISSUE THREAD

**Issue by funnycamel** [fork-maintainers/iceraven-browser#586]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

**Comment by funnycamel** [comment]
There is no save and autofill addresses option.

**Comment by akliuxingyuan** [comment]
It has, but address autofill has country restriction, track this https://bugzilla.mozilla.org/show_bug.cgi?id=1806190

**Comment by funnycamel** [comment]
How to use the address autofill in India?

**Comment by akliuxingyuan** [comment]
> How to use the address autofill in India?
> […](#)

check this? https://wiki.mozilla.org/Firefox/Features/Form_Autofill
