### ISSUE TITLE
Request addon: I still don't care about cookies

### ISSUE THREAD

**Issue by SmaugTD** [fork-maintainers/iceraven-browser#587]
[https://addons.mozilla.org/en-US/firefox/addon/istilldontcareaboutcookies/](https://addons.mozilla.org/en-US/firefox/addon/istilldontcareaboutcookies/) 

Community version of the "I don't care about cookies" addon that has a much larger website list, otherwise works exactly the same.

**Comment by krystian3w** [comment]
Other idea #684
