### ISSUE TITLE
Please enable 3rd party, or manual Addon Installation

### ISSUE THREAD

**Issue by RealFakeGitter** [fork-maintainers/iceraven-browser#591]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
Allow 3rd Party Addons to be manually installed, like on the desktop version

### How do you know that this problem exists today? Why is this important?
I tried to install an addon from Github i use on my desktop, in this case, it was 
https://github.com/iamadamdev/bypass-paywalls-firefox
But there are others as well. I've also ran into an issue where Firefox addons are available on the Mozilla store (for example Buster Captcha solver) but not in the addon repo on icecraven, requesting these addons takes both the developer and the users time, if they could manually install addons it would be far more efficient 

### Who will benefit from it?
Both users and Developers. 
Developers will no longer have to waste time reading open tickets and importing new addons, and can work on other more important tasks continuing to improve the amazing IceCraven browser, 
And users, Will be able to install and test All addons from the Mozilla store and any addons that are 3rd party too. If your worried about it causing issues you can have it as a option that one has to enable, and agree that they take responsibility for addons, and Icrcraven is not responsible for adverse effects or anything else to do with self installation

**Comment by HyperCriSiS** [comment]
Most issues could be closed then!

**Comment by mzso** [comment]
Is it not possible to install from AMO website either? I tried Desktop Everywhere, but it only downloaded the xpi without prompting to install like Fennec.

**Comment by RealFakeGitter** [comment]
> Is it not possible to install from AMO website either? I tried Desktop Everywhere, but it only downloaded the xpi without prompting to install like Fennec.

As far as I know, the only way to install add-ons currently is through the repo. You can certainly download the xpi but it won't install. Which is why I'm making this feature request.

**Comment by seniordevel** [comment]
I would prefer an "open file..." menu item.
As (former) add-on developer I would like to see an easy way to open xpi files for installation and testing purposes - as well as the the possibility to open prepared html files to test special cases.

Development should be made as easy as possible by a platform. Mozilla did the opposite. Please remove those obstacles.

**Comment by raulvasquez** [comment]
There is a way to install any addon, but it is difficult and convoluted. See here (no relation):
https://github.com/Rhys-T/fenix-arbitrary-addons

**Comment by HyperCriSiS** [comment]
> There is a way to install any addon, but it is difficult and convoluted. See here (no relation): [Rhys-T/fenix-arbitrary-addons](https://github.com/Rhys-T/fenix-arbitrary-addons)

I was using this with Firefox nightly, but it is not really a solution. It is a really annoying workaround.

Any chance this feature is added in the next version?

**Comment by HyperCriSiS** [comment]
https://blog.mozilla.org/addons/2023/08/10/prepare-your-firefox-desktop-extension-for-the-upcoming-android-release/

**Comment by ghost** [comment]
I wonder why this isn't a thing already. other firefox browsers seem to be on the same boat. why are addons such a hassle in android?

**Comment by mzso** [comment]
So currently iceraven is 118.1 based. I guess we only need to wait for the next update that's 119 based to get this.
Though I fully expect that mozilla made it such that most addons will be unavailable.

**Comment by mzso** [comment]
So this should be working now with the Fenix 119 basis, right? Did anyone try it?

By the way, is there anything good beside this in 119?

**Comment by krystian3w** [comment]
I agree #684.

**Comment by akliuxingyuan** [comment]
completed in #702
