### ISSUE TITLE
When I browse YouTube by Desktop site, the comment area can't be loaded correctly.[webcontent]

### ISSUE THREAD

**Issue by cyan-dodgers** [fork-maintainers/iceraven-browser#592]
![Screenshot_20230321_141939_io github forkmaintainers iceraven_edit_460388785197457](https://user-images.githubusercontent.com/128131238/226537098-211edce0-9a46-4e04-8362-9ccac6f19b10.jpg)
![Screenshot_20230321_142437_com yandex browser_edit_462147780533647](https://user-images.githubusercontent.com/128131238/226537113-645d3afa-21b8-4d38-b2cd-7364fd5562c0.jpg)
The first picture,I use iceraven.As you can see，the scroll bar has been draged to the bottom.The second picture,I use yandex browser.

**Comment by akliuxingyuan** [comment]
I think it's fixed, test youself
