### ISSUE TITLE
Add BeeLine Reader to Iceraven addons

### ISSUE THREAD

**Issue by dankeck** [fork-maintainers/iceraven-browser#593]
I've been using an add-on to Firefox on desktop called [BeeLine Reader](https://addons.mozilla.org/en-US/firefox/addon/beelinereader). The add-on attempts to add color to lines of text, helping the eye to move more efficiently from the end of one line to the beginning of the next line. 

Right now, the only way I can use this add-on in Android is via the [Kiwi](https://kiwibrowser.com/) browser, which supports Chrome add-ons. But I'd rather use Iceraven than a Chromium-based browser. 

Could this add-on be included in the [What I want on Fenix](https://addons.mozilla.org/en-US/firefox/collections/16201230/What-I-want-on-Fenix/) collection? (I understand it may not work in Iceraven.) 

URL of BeeLine Reader add-on: [https://addons.mozilla.org/en-US/firefox/addon/beelinereader](https://addons.mozilla.org/en-US/firefox/addon/beelinereader)

**Comment by KateYagi** [comment]
Because it's relevant, there's also waspline reader, a FOSS alternative that works similarly without a subscription: https://github.com/corollari/waspline-reader

**Comment by krystian3w** [comment]
Other idea https://github.com/fork-maintainers/iceraven-browser/issues/684
