### ISSUE TITLE
Update for Enable Unified Search

### ISSUE THREAD

**Issue by cline-tang** [fork-maintainers/iceraven-browser#595]
火狐每夜版在点击logo5次后在secret settings里面有个Enable Unified Search的选项，开启后就能直接在搜索框里切换搜索引擎，开发者可以跟进吗？

**Comment by cline-tang** [comment]
![IMG_20230404_220029](https://user-images.githubusercontent.com/69231013/229817993-b16192ac-a6ac-4fe6-9461-af5c17b542a9.jpg)

**Comment by cline-tang** [comment]
![IMG_20230404_220000](https://user-images.githubusercontent.com/69231013/229818507-6246a599-7de1-443e-9de8-0b0fce6574a4.jpg)

**Comment by akliuxingyuan** [comment]
还有一些缺陷，建议再等等 [bugzilla search result](https://bugzilla.mozilla.org/buglist.cgi?short_desc=Unified%20Search&query_format=advanced&classification=Client%20Software&classification=Developer%20Infrastructure&classification=Components&classification=Server%20Software&classification=Other&resolution=---&product=Fenix&order=Importance&short_desc_type=allwordssubstr)
