### ISSUE TITLE
[Suggestion] Homepage customisation

### ISSUE THREAD

**Issue by ChrisLiapakis** [fork-maintainers/iceraven-browser#597]
Can't find an option to not have sites pulled directly from history and shown as pinned on homepage while it was previously possible and very convenient.

**Comment by seniordevel** [comment]
> Can't find an option to not have sites pulled directly from history and shown as pinned on homepage while it was previously possible and very convenient.

Well, this has been addressed  here in several older topics. There are multiple duplicates amoung recently posted issues. 

No moderation here ?

**Comment by ChrisLiapakis** [comment]
Last issue on this was on last year's November as I'm seeing now, honestly sorry if that means I shouldn't have posted this in the first place. From anything I've seen though it is as far from addressed as it gets.
