### ISSUE TITLE
Allow Disabling Save To Collection prompts

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#6]
### What is the user problem or growth opportunity ?
For those who don't use Save to Collection button on tab switch er and hone page it is an university visual distraction and clutters the UI

### How do you know that this problem exists today? 
This problem came with new fenix big UI overhaul

### Who will benefit from it?
All those users who don't use this feature and dont want to be reminded again and hain about this feature

**Comment by interfect** [comment]
I could take a PR that adds a setting that turns this off. Although if we start adding settings to turn bits of the UI off, I'm going to be stuck trying to fix conflicts when upstream wants to change that part of the UI. So the less prone to producing conflicts a patch is, the better.
