### ISSUE TITLE
[Bug] Liberate patch not working(?)

### ISSUE THREAD

**Issue by TheEvilSkeleton** [fork-maintainers/iceraven-browser#60]
Related to https://github.com/interfect/fenix/commit/23ff09fba6054d18801fee97a93a6195cf570c72 and https://github.com/interfect/fenix/issues/25

## Steps to reproduce

Install [Warden](https://gitlab.com/AuroraOSS/AppWarden)

### Expected behavior

Warden isn't supposed to find LeanPlum, AdMob and Adjust when finding for trackers in the Iceweasel app

### Actual behavior

Warden finds the trackers mentioned above:

![Screenshot_20200903-113411_Warden](https://user-images.githubusercontent.com/50847364/92136575-b48dfd80-edfb-11ea-87a7-f422933a80be.png)

### Device information

* Android device: Lenovo P2
* Fenix version: [Spelling Liberation Edition](https://github.com/interfect/fenix/releases/tag/fork-9)

**Comment by bbigam** [comment]
I think that's just from the stub implementation of those - i.e. a dummy reference that doesn't do anything. The manifest doesn't seem to show any real content. But I'm not sure how to check this for sure.

The liberate patch is here for reference: https://gitlab.com/relan/fennecbuild/-/blob/master/fenix-liberate.patch
Note that they are stubbed out, not removed.

**Comment by TheEvilSkeleton** [comment]
> I think that's just from the stub implementation of those - i.e. a dummy reference that doesn't do anything. The manifest doesn't seem to show any real content. But I'm not sure how to check this for sure.
> 
> The liberate patch is here for reference: https://gitlab.com/relan/fennecbuild/-/blob/master/fenix-liberate.patch
Note that they are stubbed out, not removed.

Alright, though I don't think it actually worked: https://gitlab.com/fdroid/rfp/-/issues/1459#note_407508534

**Comment by bbigam** [comment]
That shows it using an unapproved Maven, but I don't see it showing
proprietary or tracking bits like Adjust, Leanplum, Firebase. Aren't those
different issues, or am I missing something?

--
Fr. Brandon Bigam
Pastor
Saint Martha Catholic Church, Prestonsburg, KY
Saint Luke Catholic Church, Salyersville, KY

**Comment by TheEvilSkeleton** [comment]
Correct. Firebase has been removed, so that's a good thing

**Comment by interfect** [comment]
I believe the patch is working.

I don't think it makes sense to remove the links to the Mozilla maven repo in the main source tree. I think what we want to do for F-Droid is patch them out at build time and build the relevant packages as part of the F-Droid build. For development we want to be able to fetch stuff like android-components from Maven, right?

**Comment by interfect** [comment]
By working I mean I think it removed the proprietary dependencies it was supposed to. I think it tried to break the Maven links and I didn't let it because I'm not really sure how to build without them yet. I or someone else needs to write up a build script that builds dependencies and this repo for F-Droid. I don't think we'll be able to have the repo just pick up auto-magically.
