### ISSUE TITLE
FastForward was removed?

### ISSUE THREAD

**Issue by Mishasama** [fork-maintainers/iceraven-browser#603]
In the latest version, I found that FastForward disappeared from the list of extensions. Is that why?

**Comment by seniordevel** [comment]
Ghacks reported that FastForward has been removed by Mozilla from their web store. 
Probably that is why it is missing in Iceraven's addon selection too.

https://www.ghacks.net/2023/03/24/fastforward-extension-has-been-silently-removed-from-mozillas-amo/

Ghacks says it is unclear why it was delisted.
Some years ago I owned and developed about a dozen addons at amo, meanwhile I removed all of them, either for personal reasons (development takes too much time) or for bad Firefox future perspectives.

**Comment by Mishasama** [comment]
> Ghacks reported that FastForward has been removed by Mozilla from their web store. Probably that is why it is missing in Iceraven's addon selection too.
> 
> https://www.ghacks.net/2023/03/24/fastforward-extension-has-been-silently-removed-from-mozillas-amo/
> 
> Ghacks says it is unclear why it was delisted. Some years ago I owned and developed about a dozen addons at amo, meanwhile I removed all of them, either for personal reasons (development takes too much time) or for bad Firefox future perspectives.

THX

**Comment by athulkrishna2015** [comment]
Add universal bypass then
