### ISSUE TITLE
Please make "bypass paywall magnolia" back on iceraven

### ISSUE THREAD

**Issue by AlmaDeMetal** [fork-maintainers/iceraven-browser#605]
HI! 
It wolld be nice to have "bypass paywall magnolia" back on iceraven. 

I live in a country where the  freedom of speech is absolutely limited and there no way to pay a suscription to a foreigner news paper with out fall in jail.  So I hope there is a way to have this addon back on iceraven.

Thanks you !!

**Comment by krystian3w** [comment]
If are allowed in Moz://a store then maybe by these: #684

**Comment by akliuxingyuan** [comment]
you can sideload it after Iceraven v2.13.2
