### ISSUE TITLE
Feature request: install addons from local file

### ISSUE THREAD

**Issue by benzBrake** [fork-maintainers/iceraven-browser#607]
Chinese users accessing the AMO to install ublock, adugard or other extensions will return  HTTP 451 Unavailable For Legal Reasons。

**Comment by seniordevel** [comment]
This is one more duplicate request.

Please use:

https://github.com/fork-maintainers/iceraven-browser/issues/591

As this is the most requested feature, for good reason, please bundle it there!

**Comment by seniordevel** [comment]
This is one more duplicate request.
Please use:

https://github.com/fork-maintainers/iceraven-browser/issues/591

As it is the most requested feature, please bundle it there!
