### ISSUE TITLE
White splash screen before loading pages[Bug]

### ISSUE THREAD

**Issue by Annam792** [fork-maintainers/iceraven-browser#61]
Even though dark reader and dark theme has been installed, there is a white bright screen before loading a page, which is an overkill to the eyesight.

Is there any way to fix it?

**Comment by jaytohe** [comment]
Settings >>> About Iceweasel >>> Tap 5 times on the Browser logo to enable Secret Settings.

Secret Settings>>> Toggle "Wait Until First Paint To Show Page Content"

It doesn't remove all white flash but it eliminates it in a lot of cases.

**Comment by Annam792** [comment]
> Settings >>> About Iceweasel >>> Tap 5 times on the Browser logo to enable Secret Settings.
> 
> Secret Settings>>> Toggle "Wait Until First Paint To Show Page Content"
> 
> It doesn't remove all white flash but it eliminates it in a lot of cases.

That fixed it for the most part. Thanks!

**Comment by mackeev** [comment]
You can make your experience with this even better by doing the following:
browser.display.background... change to #000000
browser.display.foreground... change to #aaaaaa (or whatever)

P.S. Need to admit it works better in pre-79.
