### ISSUE TITLE
Browser crashes everytime I try to login github

### ISSUE THREAD

**Issue by Sciroccogti** [fork-maintainers/iceraven-browser#611]
I have all the extensions uninstalled, but at the very moment when I open https://github.com/login , the page crashes.

There're two crash reports:
```java
6d86b76b-514a-440f-8dda-61c7b51bde1b
<native crash>
----
<native crash>
```

```java
1abe1dd0-42f0-4977-b7fd-111532cdeb15
kotlinx.serialization.SerializationException: Serializer for class 'GleanCrashAction' is not found.
----
kotlinx.serialization.SerializationException: Serializer for class 'GleanCrashAction' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
	at kotlinx.serialization.SerializersKt.serializer(Unknown Source:52)
	at mozilla.components.lib.crash.service.GleanCrashReporterService.recordCrashAction$lib_crash_release(GleanCrashReporterService.kt:57)
	at mozilla.components.lib.crash.service.GleanCrashReporterService.record(GleanCrashReporterService.kt:6)
	at mozilla.components.lib.crash.CrashReporter$submitCrashTelemetry$2.invokeSuspend(CrashReporter.kt:53)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:13)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:79)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e0f5a14, Dispatchers.IO]
```

- Iceraven 2.4.1
- Android 13
- MIUI 14.0.24
- Mi 13

**Comment by Sciroccogti** [comment]
It seems to be the same with #255

**Comment by seniordevel** [comment]
Could you please try again after a full android restart?

Also, please make sure to have deleted any browsing data in Iceraven's settings.

**Comment by Sciroccogti** [comment]
I cleared browsing data and rebooted Android, but it still crashes.

**Comment by ty114514** [comment]
Same Issues
Device: Redmi Note12Turbo(Poco f5)
Iceraven 2.4.1
Addons: Bitwarden, uBlock Origin, Violentmonkey

**Comment by seniordevel** [comment]
I have no problems logging in to github - but I am still with Android 10.

@Ty114514
Can you please post your Android version?
Would you try login again with all your addons disabled ?

**Comment by ty114514** [comment]
MIUI14.0.19 Android13
I disabled the plugins and rebooted, didn't work

**Comment by Sciroccogti** [comment]
I also tried turning off MIUI optimization, and it still crashes.

**Comment by Sciroccogti** [comment]
There seems to be a bug while building:
```Java
Caused by:
    com.***.tools.r8.internal.g: Type com.google.***.gms.common.GooglePlayServicesNotAvailableException is defined multiple times:
/home/runner/.gradle/caches/transforms-3/327acc1176631531de997b0e5d0d01b5/transformed/play-services-basement-17.0.0-runtime.jar:com/google/***/gms/common/GooglePlayServicesNotAvailableException.class, /home/runner/work/iceraven-browser/iceraven-browser/app/build/intermediates/javac/fenixForkRelease/classes/com/google/***/gms/common/GooglePlayServicesNotAvailableException.class
```

**Comment by akliuxingyuan** [comment]
It didn't fix it, you need turn on system GMS services

**Comment by Sciroccogti** [comment]
So emmm how can I tell whether it is cause by missing GMS ?
***
All right, it does work when I use iceraven under Gspace.

But other browsers, even the original firefox, work fine without GMS.

**Comment by akliuxingyuan** [comment]
I'm confusing too, not find the reason yet.

**Comment by seniordevel** [comment]
I have all Google services disabled, even system.
VPN logs are free from Google requests.

Login to Github still works fine for me and with Iceraven.

**Comment by Sciroccogti** [comment]
> I have all Google services disabled, even system. VPN logs are free from Google requests.
> 
> Login to Github still works fine for me and with Iceraven.

Which device are you using?

**Comment by seniordevel** [comment]
I am using a Gigaset GS4 device, currently with Android v. 11

**Comment by Sciroccogti** [comment]
Thanks.

I also don't believe that it has anything to do with Google, but with [Gspace](https://gspaceteam.com/), an App provide GMS, the issue wouldn't appear.

**Comment by seniordevel** [comment]
GMS, that IS Google, it is Google Mobile Services.

**Comment by Sciroccogti** [comment]
I know, just dont understand why login to GitHub needs GMS.



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/16/2023 03:12 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [fork-maintainers/iceraven-browser] Browser crashes everytime I try to login github (Issue #611) |

GMS, that IS Google, it is Google Mobile Services.

**Comment by seniordevel** [comment]
I understand, it works for you using GSpace with GMS. I just do not know why! 

As I said above, I have all Google services disabled or blocked, for sure including any GMS!

But I am still able to log in to Github, without any problems.

That is a clear contradiction to your experience. 
I am not sure what is going on.

"GooglePlayServicesNotAvailableException"

That is in essence what @akliuxingyuan mentioned as reason for your issue. 

But I am absolutely sure, I have google play services not only disabled but having blocked any related IP's too.

**Comment by seniordevel** [comment]
Looking at the crash report, this issue might be related to an open fenix bug:

[Serializer for class 'GleanCrashAction' is not found.](https://bugzilla.mozilla.org/show_bug.cgi?id=1830682)

**Comment by sunjanesy** [comment]
很多个版本之前，我就发现了该问题，起初人家不信，我也不知道如何解决，直到我有一次开了谷歌套件，所以能不能把依赖去掉
![Screenshot_2023-05-19-17-15-15-366_com coolapk market](https://github.com/fork-maintainers/iceraven-browser/assets/104602119/abea226c-1b18-4aff-8fc6-18d5e77238ef)

**Comment by ty114514** [comment]
I update to the latest version 2.6.1, try to login GitHub, now will not crash, I can login and write issues
seems like fixed? anyone can test it and reply here?

**Comment by Sciroccogti** [comment]
> I update to the latest version 2.6.1, try to login GitHub, now will not crash, I can login and write issues seems like fixed? anyone can test it and reply here?

Thanks for notification! It does work now.
