### ISSUE TITLE
AwesomeBar Bookmarks Suggestion Limit too small

### ISSUE THREAD

**Issue by VKen** [fork-maintainers/iceraven-browser#613]
Hi maintainers, thank you for iceraven! I missed fennec's features where everything was working fine for me.

One feature regression from fenix onward which I use is the url/bookmarks suggestions from the address bar AKA awesome bar.

There is a settings in https://github.com/akliuxingyuan/android-components/blob/eb9843c8151532b8af20dc6afd0484a62e873a9a/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProvider.kt#LL25C20-L25C46

Where the default `BOOKMARKS_SUGGESTION_LIMIT` is `20` only. It's not possible for me to filter better because I surf and bookmark sites and webpages that are not english, an typing non-ascii characters into the address bar to filter is a big hassle.

I have not figured out where else we could change this config , and have just tried to compile ice-raven using the latest release branch and attempted to install a local apk build unsuccessfully (Successful build, can't install apk on phone).

Previously fennec doesn't seem to have a limit which I hit. Assuming there's nowhere in `about:config` to change this value, current value is too low. Can we set the default value to something higher like 100?

Thank you very much!

**Comment by akliuxingyuan** [comment]
> It's not possible for me to filter better because I surf and bookmark sites and webpages that are not english, an typing non-ascii characters into the address bar to filter is a big hassle.

You should describe the useful keyword, which makes searching more effective.
The better method is to categorize bookmarks by folder, it will be more convenient to find it

After investigating related code, I find out if we turn on `Sponsored Suggestions`, this function will be called instead,
https://github.com/akliuxingyuan/android-components/blob/81883d4e4f0f81a00b67875a5f592480b898f3ce/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProvider.kt#L100
which results the limit will multiply `BOOKMARKS_RESULTS_TO_FILTER_SCALE_FACTOR`(value=10)
https://github.com/akliuxingyuan/android-components/blob/81883d4e4f0f81a00b67875a5f592480b898f3ce/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProvider.kt#L32

**Comment by akliuxingyuan** [comment]
fixed in [4b02488](https://github.com/fork-maintainers/iceraven-browser/commit/4b024889db25ccfa1dd2d76e32c02b0fe10bbb6f), now you have `BOOKMARKS_SUGGESTION_LIMIT * BOOKMARKS_RESULTS_TO_FILTER_SCALE_FACTOR = 200` bookmarks suggestions
