### ISSUE TITLE
Which version should I download for Android5?

### ISSUE THREAD

**Issue by liijjj** [fork-maintainers/iceraven-browser#615]

**Comment by seniordevel** [comment]
[As meantioned here, it should be this very old version, but I am not sure](https://www.apkmirror.com/apk/fork-maintainers/iceraven-browser/iceraven-browser-iceraven-1-18-4-release/iceraven-browser-iceraven-1-18-4-android-apk-download/) 

Please be aware that old software versions supposingly won't work correctly!
Update your Android for best results.

**Comment by akliuxingyuan** [comment]
project settings: `minSdkVersion: 21`, which means it should support Android5, but I can't guarantee.
