### ISSUE TITLE
Video playback issue

### ISSUE THREAD

**Issue by hanwuli** [fork-maintainers/iceraven-browser#616]
Why YouTube cannot be viewed horizontally on Android phones?

**Comment by seniordevel** [comment]
It is possible with Iceraven:

1. Enable auto-rotate in Android
2. Go to Youtube and start your video
3. Enter full-screen mode
4. rotate your phone horizontally
5. wait for 2 or 3 seconds
6. Done !

It might not work with some other apps, but with Iceraven.
