### ISSUE TITLE
Iceraven 2.6.1 crashes

### ISSUE THREAD

**Issue by davidj77** [fork-maintainers/iceraven-browser#621]
Hi, Iceraven 2.6.1 arm32 crashes after I open it, I've reinstated it but it crashes again and again when I try to open it, version 2.5.1 worked fine.
I'm testing it in a Samsung i2 with Android 5.1.1

**Comment by davidj77** [comment]
Last Firefox release works fine for me.
![Screenshot_2023-06-12-16-04-19](https://github.com/fork-maintainers/iceraven-browser/assets/71226185/8a01737b-44ea-41c1-97cd-11c024329c97)

**Comment by CharmCityCrab** [comment]
Worksforme.  

Logged out and back into GitHub with no issues.

I noticed the OP is using a device running Android 5 and checked to see if upstream is still supporting it or not.  The minimum requirement for Fenix 113.x is Android 5 or above.  Iceraven 2.6.1 is based on Fenix 114.1, which I couldn't find a system requirements page for on Mozilla's website.  So, I'm guessing Android 5 is *probably* still supported, though I couldn't completely confirm that.

Still, this could be an Android 5 specific bug.  Anyone else have an old Android 5 device they could use to see if they can replicate the OP's issue?

**Comment by akliuxingyuan** [comment]
please test with latest version, it should work as fenix
