### ISSUE TITLE
Enhancement: Option to export bookmarks to local storage

### ISSUE THREAD

**Issue by davidj77** [fork-maintainers/iceraven-browser#623]
It will be great if Iceraven bring us the option to export our bookmarks to local storage, useful when we update the browser and it keep crashing, so we can downgrade and import the bookmarks with no need to add them manually saving time.
Thanks in advance.

**Comment by HarriBuh** [comment]
Yes, please! This essential feature has been missing on any Firefox browser since it got released. The only currently available feature via synching requires the creation of an account, which is everything but "free"/ "open-source" aso.

**Comment by akliuxingyuan** [comment]
if you only want to rollback to older version to avoid crash, you can downgrade app via adb `adb install -r -d <path to apk>`, it works out of box usually.
on the meanwhile export bookmarks is great feature to have

**Comment by akliuxingyuan** [comment]
move to #103
