### ISSUE TITLE
Extension can not download if failed before

### ISSUE THREAD

**Issue by wolfdate25** [fork-maintainers/iceraven-browser#628]
Iceraven app can not install if the downloaded extension file is wrong. If the invaild extension file downloaded, iceraven need to try redownload the extension file.  I solve this problem deleting the app's cache. But It can improve to change related logic.

**Comment by akliuxingyuan** [comment]
It seems that we need a button to delete the cache file

**Comment by akliuxingyuan** [comment]
fixed in https://github.com/fork-maintainers/iceraven-browser/releases/tag/iceraven-2.10.4?
@wolfdate25 can you verify, not sure it suit you case
