### ISSUE TITLE
Captcha not showing at login.

### ISSUE THREAD

**Issue by radityajaya** [fork-maintainers/iceraven-browser#630]
Captcha does not appear when logging in to a bitwarden account.
![IMG_20230703_044513](https://github.com/fork-maintainers/iceraven-browser/assets/113519900/bc337a79-5277-4446-a705-a76b83a08fcd)

Device : Redmi 9C
Android : 10
MIUI 12.0.14

**Comment by akliuxingyuan** [comment]
if firefox official do the same, I think you better report bug on [bugzilla](https://bugzilla.mozilla.org/describecomponents.cgi?product=Fenix) since it will going into android components level which we don't want to affect

**Comment by radityajaya** [comment]
That problem is fixed in firefox nightly.
