### ISSUE TITLE
Do something with the opening screen that is mostly blank

### ISSUE THREAD

**Issue by CharmCityCrab** [fork-maintainers/iceraven-browser#64]
### What is the user problem or growth opportunity you want to see solved?

Right now, when one opens the browser, one gets a URL bar and other things typically next to it, then underneath it the word "Browser" and a private browser icon that presumably opens a private browsing tab, and beneath it all, a large blank space.  I assume there is also big blank space for people who have their URL bar at the bottom, just positioned differently (My URL bar is set to display at the top because that's where I like it).  I think it also came with a row of icons, which I quickly removed upon install.

I think the reason for this blank space is that this is where Firefox very unpopularly puts collections, or for those who don't have collections (Which I would guess is a large majority), essentially a non-removeable ad for collections. 

While the IceWeasel approach of a large blank space is vastly superior to collections and collections advertisements, it strikes me that the browser could still do even better.

Could we list bookmarks there instead?  That seems to be the preferred replacement for collections in general terms.  People complaining about upstream generally want bookmarks instead of collections and talk about being too many clicks away from their bookmarks.  Of course, for ease of use, bookmarks could remain in their existing location as well (There's no rule that says bookmarks can't be listed in two places, though the browser would have to take care that changes to bookmarks in one space migrate to the other and vice-versa.).

If there are technical hurdles to to writing something interactive like bookmarks into that space, what about replacing the blank portions of that screen with a static image of the browser's logo?  In addition to filling the space with something non-annoying, it could also serve to increase brand awareness, especially since there are apparently some technical hurdles with turning the word "Browser" on that page into the word "IceWeasel".  A big logo, potentially (Although not necessarily) including the name of the browser underneath as part of the logo, could be mitigation of sorts.

This doesn't bother me a whole lot, but I think in general leaving a large blank space like that may seem weird to some potential future users, as though the page were half finished.

**Comment by bbigam** [comment]
Note that various changes are coming from upstream to revamp and expand Top Sites, see the issues linked at this beta release: https://github.com/mozilla-mobile/fenix/releases/tag/v81.1.0-beta.2

Doesn't solve this issue but is relevant to it.

The banner has been fixed (and I'll update it again if we change our name) https://github.com/fork-maintainers/iceweasel/pull/85
