### ISSUE TITLE
2.8.1 makes SystemUI crash when start

### ISSUE THREAD

**Issue by liyafe1997** [fork-maintainers/iceraven-browser#642]
Previous versions all works fine. 

Today after I upgraded to 2.8.1, everytime the browser run from coldstart (force stoped, or use the "Exit" menu), the SystemUI will crash and be reloaded, then it will goes to the lockscreen (just like the normal behavior when you kill systemui, like killall com.android.systemui)

OS: MIUI 14.0.4 & Android 12
Phone: Redmi K30 Pro

System language is set to Chinese. And I use Niagara Launcher.
I am not sure where the problem comes from.

The attached video is the screen record shows the crash. 

https://github.com/fork-maintainers/iceraven-browser/assets/18359157/4dccb388-7ae7-4460-8e1f-eee99dbdc31d

**Comment by hanwuli** [comment]
Me too.

**Comment by liyafe1997** [comment]
As I tested on my another HUAWEI phone, HarmonyOS 3.0 (=EMUI12?) & Android12, this problem also happened.

**Comment by hanwuli** [comment]
Hope it can be fixed soon!

**Comment by Timofei302** [comment]
same problem

Device: Tecno POVA 4 Pro
OS: Android 12 (HiOS V12.0.0) no root
Iceraven version: 2.8.1

**Comment by akliuxingyuan** [comment]
Need logs for analysis, properly related to animated_splash_screen

**Comment by ghost** [comment]
2 days of system u.i. crashing, how long does it take to release a fix?

**Comment by liyafe1997** [comment]
I have posted the log of both Iceraven and SystemUI here:
https://github.com/fork-maintainers/iceraven-browser/issues/641#issuecomment-1668142555

**Comment by akliuxingyuan** [comment]
@liyafe1997 please test this CI version https://github.com/fork-maintainers/iceraven-browser/actions/runs/5797614812

**Comment by ghost** [comment]
> CI version https://github.com/fork-maintainers/iceraven-browser/actions/runs/5797614812

Working as expected. Thank you for the quick fix!

**Comment by RogeryRY** [comment]
Thank you for fix👍
