### ISSUE TITLE
"Open link in external app"

### ISSUE THREAD

**Issue by Leugnam** [fork-maintainers/iceraven-browser#649]
![IMG_20230816_125834](https://github.com/fork-maintainers/iceraven-browser/assets/142402363/52f20fd5-935a-4c4e-b1a4-cede99d731ee)
Hello, is it possible to have this option back again? 
It stopped showing since 2.7.0.

I have tried updating to the latest 2.8.3 and enabling: "advanced>open links in app>always" yet it doesn't show anymore. 
I'm currently using 2.6.1 since it has the option I want.

I might have missed change logs or something, I'm unaware :(

**Comment by Leugnam** [comment]
😢

**Comment by akliuxingyuan** [comment]
<img src="https://github.com/fork-maintainers/iceraven-browser/assets/53224655/4ebc6159-fa81-4ca8-bd81-5be24c34d7fb" width=50%/>

**Comment by Leugnam** [comment]
Mhh I got it working, thanks. 

Image below is phone settings>"default apps"
![_20240331_053722](https://github.com/fork-maintainers/iceraven-browser/assets/142402363/2e5dace6-e7c1-4bb3-a413-110c634c1a8b)
I then added links to the app I want them to be opened in and now with the latest version I have the option "open link in external app" along with the one in your screenshot (before touching phone settings only certain websites had that, not the one I needed) 
Thanks.
