### ISSUE TITLE
Feature, Extension request 

### ISSUE THREAD

**Issue by kaiminz** [fork-maintainers/iceraven-browser#655]
1，website homepage , and toolbar shortcut button (multiple choice from alternatives )  like new kiwi browser are all preferable.
2, bookmarkhub extension. Opensource, too.

[Bookmarkhub]- [Github](https://github.com/dudor/BookmarkHub)

**Comment by akliuxingyuan** [comment]
1. Firefox android client can't settings a website as homepage. and #675
2. You can install extension directly from https://addons.mozilla.org/
