### ISSUE TITLE
Use Android's system font as default font

### ISSUE THREAD

**Issue by ZooNooU** [fork-maintainers/iceraven-browser#667]
Hello!
is there a way to use the Android's system font instead of the browser's default one?
I don't like the way it looks, and I'm using a custom font on my system, and I wish for iceraven to follow the same font as my system (and literally every other app)

here's how web content is displayed in iceraven:
![Screenshot_20231003-215916_Iceraven](https://github.com/fork-maintainers/iceraven-browser/assets/103965987/4a3a94f4-f4c3-4f18-90fb-ba7d43e51edc)

and here's how web content is displayed in other browsers (which is what I want in iceraven):
![Screenshot_20231003-215850_Opera beta](https://github.com/fork-maintainers/iceraven-browser/assets/103965987/ee96e6a8-7bb9-48c4-a485-49276b5c2626)

the app itself is using my custom font, but web content is using another font that I don't like,,
please consider changing font to the system's default one, or at least an option to change it.
thanks! :DD

**Comment by akliuxingyuan** [comment]
dup of #540
