### ISSUE TITLE
Screen/canvas resolution not accurate

### ISSUE THREAD

**Issue by Magicrafter13** [fork-maintainers/iceraven-browser#668]
In portrait it reports 408x875, and in landscape 875x408.

For reference, my screen resolution is 1440p (21:9 ratio), and I'm getting screen information from here:
http://www.lagom.nl/lcd-test/display_settings.php

**Comment by akliuxingyuan** [comment]
http://dev.jeffersonscher.com/resolution.html
ref: https://support.mozilla.org/en-US/questions/981038
