### ISSUE TITLE
REQUEST : please add the extension "Reddit Column View"

### ISSUE THREAD

**Issue by Fytdyh** [fork-maintainers/iceraven-browser#669]
hello, i would like to ask if it would be possible to add the following extension "Reddit Column View" to the collection. here is the link for it
https://addons.mozilla.org/en-US/firefox/addon/reddit-column-view/?utm_content=addons-manager-reviews-link&utm_medium=firefox-browser&utm_source=firefox-browser

thank you for your time and patience

**Comment by krystian3w** [comment]
Other idea: #684
