### ISSUE TITLE
[QUESTION] Preinstalled extensions

### ISSUE THREAD

**Issue by CasperOnrun** [fork-maintainers/iceraven-browser#672]
Is any way to  built Iceraven with preinstalled extensions or force installation within a first run of some ones?

**Comment by akliuxingyuan** [comment]
Add-on Installation is interactive, not finding a way to skip the dialog prompt

**Comment by CasperOnrun** [comment]
Thanks for your reply. I have find out the way to skip prompt dialog. In my fork user still see bottom sheet with information that extension installing. And I plan to fix it next month. It requires customizing couple of Android components and linking them from custom repo or localy.

@akliuxingyuan
