### ISSUE TITLE
[Feature Request] Material you theming

### ISSUE THREAD

**Issue by Henry-Hiles** [fork-maintainers/iceraven-browser#677]
Please tell me if this is plain not possible, but support for theming with Android's material you would be absolutely incredible, thank you.

**Comment by seadx6-neo** [comment]
The lack of Material you theming is not responsibility  of the Ice raven team and sadly it is something not easy to add, this is a fork of Firefox, the team behind Firefox are the ones who are refusing to add material you theming and even something as simple as adding a toggle to disable the redundant home button despite the oh so many requests both in their community, GitHub and bugzilla to add either of them

Sorry if I sound like an unhappy or angry user but I am sadly one of the ignored users who asked to add the toggle to disable the home button, I love Firefox and its forks, but  sadly there are some wrinkles which prevent me from enjoying Firefox for Android, if they want to keep their current and own Firefox UI language I wish at least they took it straight from the desktop UI like the way tabs look

**Comment by Henry-Hiles** [comment]
I see, i was hoping this could be done with some code changes to firefox by iceraven, as an extra feature. Thanks anyways.
