### ISSUE TITLE
[Extension request] Redirect blocker and Popup Blocker

### ISSUE THREAD

**Issue by Arkuarius** [fork-maintainers/iceraven-browser#679]
Redirect blocker: https://addons.mozilla.org/en-US/android/addon/redirect-blocker/

Popup blocker: https://addons.mozilla.org/en-US/android/addon/popup-blocker/

**Comment by krystian3w** [comment]
https://github.com/fork-maintainers/iceraven-browser/issues/684 maybe possible use Moz://a idea:


Redirect blocker: https://addons.mozilla.org/firefox/addon/redirect-blocker/

Popup blocker: https://addons.mozilla.org/firefox/addon/popup-blocker/
