### ISSUE TITLE
URL display problem

### ISSUE THREAD

**Issue by franco27** [fork-maintainers/iceraven-browser#680]
Hello

the page refreshes in a loop (the page refreshes constantly)

http://www.disneyphile.fr/contact/

**Comment by franco27** [comment]
For the rest of the other pages of the site I did not notice any problem.

**Comment by akliuxingyuan** [comment]
I can't reproduce, though page takes long time to finish load, but no refresh behavior

**Comment by franco27** [comment]
In the current version, I no longer have this issue. This problem occurred with a previous version of your internet browser.
Thank
