### ISSUE TITLE
Binnen-I be gone - addon-request

### ISSUE THREAD

**Issue by DrDustwolf** [fork-maintainers/iceraven-browser#681]
"If you don't see an add-on you want, you can request it."
Hi Mr. Adam Novak please add the "Binnen-I be gone" add-on to your "What I want on Fenix" add-on collection. 
Thank you

Ressouces:

https://addons.mozilla.org/de/firefox/addon/binnen-i-be-gone/

https://addons.mozilla.org/de/firefox/collections/16201230/What-I-want-on-Fenix/

**Comment by krystian3w** [comment]
Other idea: https://github.com/fork-maintainers/iceraven-browser/issues/684
