### ISSUE TITLE
youtube: open in app

### ISSUE THREAD

**Issue by Soheil777** [fork-maintainers/iceraven-browser#689]
> Hi I love and use your browser just because Youtube first, i can turn off my screen and just listen to the video, it is extremely useful especially for news second because block adds now your app can not block ads on Youtube I even use adguards add-ones but don't work i dont know you must fix your browser or it is about adguard add-ones but pleaseeeeeee fix it

Switch from adgaurd to uBlockOrigin

hi again
i did and it fixed BUT recently in new version of iceraven when i try see video inn YouTube your browser suggested open in YouTube app
i told you i use this browser because YouTube 
yes i can say no or click on cancel but this pm is ridiculous And completely unnecessary
i hope you fix it new version like as old version was
also i will be grateful if i can just listen in YouTube to news and turn off my screen in mobile mod without extension

thank you so much

_Originally posted by @ChiefMikeK in https://github.com/fork-maintainers/iceraven-browser/issues/63#issuecomment-1777141935_

**Comment by akliuxingyuan** [comment]
> i did and it fixed BUT recently in new version of iceraven when i try see video inn YouTube your browser suggested open in YouTube app

not having issue with uBO installed

> also i will be grateful if i can just listen in YouTube to news and turn off my screen in mobile mod without extension

still works for me, I play a video and lock the screen, the music stopped, but there is a media control panel on lock screen, click the play button the music start playing again

**Comment by akliuxingyuan** [comment]
>  yes i can say no or click on cancel but this pm is ridiculous And completely unnecessary

you can just disable that in Settings `Settings > Open links in apps > Never`
