### ISSUE TITLE
D3leting history on quit also deletes icons of shortcuts

### ISSUE THREAD

**Issue by Mal752** [fork-maintainers/iceraven-browser#690]
Deleting the history on quit in the settings also deletes the icon cache of websites of shortcuts.

This is the same as in vanilla Firefox for Android.

From the settings, manually deleting Everything in history alone, preserves the said icon images in the shortcuts.

Usually whenever I quit Firefox, I choose what to delete and history is one of them. 

Thank you for any updates.

P.S. I uninstalled Firefox after finding about Iceraven, since I can have more than 8 shortcuts.
I really like the Speedial in Opera, but ad blocking there is lackluster and it doesn't support add-ons like Ublock Origin. So, for now, Iceraven is a compromise between Firefox and Opera.

**Comment by akliuxingyuan** [comment]
> From the settings, manually deleting Everything in history alone, preserves the said icon images in the shortcuts.

I test it with forkDebug build, deleting browsing data manually from settings does delete the icon cache
