### ISSUE TITLE
【download】Add built-in downloader and system downloader

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#695]
I don't think the download browser has a built-in downloader but only a system download, so I can't watch the download progress in the download interface of this browser. I hope to optimize it and optimize the UI interface. When downloading resources, the icon on the left should also be made to get it. I brought the UI of via browser.
![Screenshot_20231125_205526](https://github.com/fork-maintainers/iceraven-browser/assets/151994842/f52a566e-27fc-43b2-9550-60e1dc65f2c4)
![Screenshot_20231125_205432](https://github.com/fork-maintainers/iceraven-browser/assets/151994842/a9a1ae0a-9a23-45d9-b090-fc8e77573ff7)

**Comment by akliuxingyuan** [comment]
you can change settings to use external download manager, then when you download files, you can choose downloader you want.

> so I can't watch the download progress in the download interface of this browser.

you can see the download progress in system notification, and I think nobody would watch the progress bar until it finish, it's waste of time, you can do other thing then check it later

**Comment by ghost** [comment]
thank
