### ISSUE TITLE
Add scripts from greasyfork

### ISSUE THREAD

**Issue by trimechee** [fork-maintainers/iceraven-browser#712]
Hello, i find script and we hope our beloved Iceraven-browser can add scripts from greasyfork, thank you ! 

https://greasyfork.org/fr/scripts/478597-googlegpt

**Comment by akliuxingyuan** [comment]
Install userscript manager like Tampermonkey/Violentmonkey first, then you can install scripts from greasyfork.org

**Comment by trimechee** [comment]
Great ! Thank you so much for yout precious help @akliuxingyuan :)
