### ISSUE TITLE
Behaviour of google pages with changed useragent

### ISSUE THREAD

**Issue by C3tacea** [fork-maintainers/iceraven-browser#716]
When you change the useragent, through an add on or through about:config, all of the Google pages and a few others won't display correctly based on your usercss configurations, viewpoint, font or dpr or anything else that I tried. They automatically are very zoomed in. The weird thing is for some configuration pages about cookies sometimes they are shown correctly but getting back to the search results they are again very zoomed in. 

I did every configuration, same useragent, same viewpoint etc in chromium based browsers for Android or in Firefox for linux and there it works fine. 

Thanks a lot for your great browser.

**Comment by freebrowser1** [comment]
This has nothing to do with Iceraven, Firefox or any non-Google browser, but it are limitations imposed by Google to push users to use Chrome.

**Comment by akliuxingyuan** [comment]
please share your configuration, otherwise we won't be able to do anything
