### ISSUE TITLE
[feature request] Nordic theme in an iceraven browser

### ISSUE THREAD

**Issue by C3tacea** [fork-maintainers/iceraven-browser#718]
Maybe you could introduce a "Nordic theme"? It fits quiet nice to the icon and the idea of an "ice raven". Also there a probably quiet a few people who dislike the purple based UI. I have looked into the source code and in searching for themes, the dark theme has as main colors dark grey and purple, chosen from the photoncolors by Firefox. 
They could be quiet easily changed to the color codes from the Nordic theme website: https://www.nordtheme.com/.

**Comment by akliuxingyuan** [comment]
Currently firefox android does't support multi theme, so this is not gonna happen in short future.
