### ISSUE TITLE
[Add-on] http tracker

### ISSUE THREAD

**Issue by MilaMurry** [fork-maintainers/iceraven-browser#719]
I'd like to request an add-on called [http tracker](https://addons.mozilla.org/en-US/firefox/addon/http-tracker/). A very useful add-on to monitor response/request headers. Some other add-ons require values from the header, which a user doesn't have access to, so this add-on helps. Also, it is useful to debug errors on pages/videos/images that won't load.
Additionally, if you can make the add-on use a dark theme, which would be good.

**Comment by akliuxingyuan** [comment]
you can sideload add-on to test if it works as described in release v2.13.2
https://github.com/fork-maintainers/iceraven-browser/releases/tag/iceraven-2.13.2

**Comment by MilaMurry** [comment]
I've tried it months ago and it didn't work, that's way I requested it here.
Clicking the add-on is supposed to open it in a new tab but it does nothing.
