### ISSUE TITLE
[add-on request] Emoji to English

### ISSUE THREAD

**Issue by danildf** [fork-maintainers/iceraven-browser#721]
I'd like to request [Emoji to English](https://addons.mozilla.org/en-US/firefox/addon/emoji-to-english/) add-on. It's very handy when surfing websites that overuse emoji to an extent where it becomes challenging to read the actual content.

**Comment by lividhen** [comment]
Does it not work if you install it? Seems to work fine for me. 
![Screenshot_20240105_050535_Iceraven](https://github.com/fork-maintainers/iceraven-browser/assets/42221797/242a18e6-67be-4946-b56b-d79ae8d05d5b)

**Comment by danildf** [comment]
It never occurred to me you can install addons directly from mozilla store. Thank you very much for pointing that out. It works flawlessly.
