### ISSUE TITLE
EMPTY DOWNLOAD TAB

### ISSUE THREAD

**Issue by ALMIGHTY-VC** [fork-maintainers/iceraven-browser#724]
Firstly, i have enabled the turbo downloader extension and when i try to download apks amd mods from mediafire or any website my download tab is empty but a notification with progess shows as i have many notifications i prefer to see the download in tab is my extension affecting it idk but after the download finishes im able to see the file in download tab just not while it downloads

**Comment by akliuxingyuan** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1812992

**Comment by akliuxingyuan** [comment]
duplicated #551

**Comment by ALMIGHTY-VC** [comment]
> duplicated #551

well i was able to see downlaod task if i didnt equipped turbo downloader extension so i asked if u still feel my duplicated sorry.

**Comment by ALMIGHTY-VC** [comment]
And yup now switched to external download manager adm👌
