### ISSUE TITLE
[Bug] Menu doesn't scroll properly with a bottom toolbar in mini app/mini window mode

### ISSUE THREAD

**Issue by Arkuarius** [fork-maintainers/iceraven-browser#725]
https://streamable.com/v910m7

Here is a demonstration of the bug.

Picture this, you're in an app, and you want to access your password for the app, which is in the settings.

One of the issues with Firefox/Iceraven I've always had that with the toolbar at the bottom, and if you're using the browser in a mini-window, the menu won't scroll down properly. It's annoying.

Could you consider fixing this bug that happens only in mini window mode?

**Comment by akliuxingyuan** [comment]
There is no issue when the toolbar is on top, same as Fenix upstream, I'd suggest you report it on bugzilla

**Comment by Arkuarius** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1875818

Done

I don't expect them to respond too quick though, cause Mozilla is slow like that, but we'll see.

**Comment by Arkuarius** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1875818

Done

I don't expect them to respond too quick though, cause Mozilla is slow like that, but we'll see.

**Comment by akliuxingyuan** [comment]
> [bugzilla.mozilla.org/show_bug.cgi?id=1875818](https://bugzilla.mozilla.org/show_bug.cgi?id=1875818)

It seems that it has been fixed
