### ISSUE TITLE
How to disable "iceraven suggest" completely on Android? Using 2.14.2

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#726]
How to disable "iceraven suggest" completely? Using 2.14.2 (updated recently but still can't disable this).

I can't easily disable in Firefox nightly but can't in iceraven browser Android.

Using Xiaomi Redmi Note 10 with Android 12. But this issue is on other devices as I tested on others to see if it's one device specific issue or not.

![Screenshot_2024-01-10-14-19-47-411_io github forkmaintainers iceraven](https://github.com/fork-maintainers/iceraven-browser/assets/156216269/a2b21350-9d81-4159-b1c4-9265f8839c8d)
![Screenshot_2024-01-10-21-07-47-696_org mozilla fenix](https://github.com/fork-maintainers/iceraven-browser/assets/156216269/53f071e9-2122-402e-aed2-3bfb214f42a0)
![Screenshot_2024-01-10-21-09-48-893_io github forkmaintainers iceraven](https://github.com/fork-maintainers/iceraven-browser/assets/156216269/ad2d7490-e054-4191-b565-122abbb7e195)
![Screenshot_2024-01-10-21-12-02-804-edit_io github forkmaintainers iceraven](https://github.com/fork-maintainers/iceraven-browser/assets/156216269/61b62b0c-d1d3-40c9-aa0f-4d2b10e567fb)
![Screenshot_2024-01-10-21-13-01-938_io github forkmaintainers iceraven](https://github.com/fork-maintainers/iceraven-browser/assets/156216269/23a553e4-506b-4f4d-8d0b-2bc44f217b16)

**Comment by akliuxingyuan** [comment]
`Switch to tab` suggestion can't be disabled yet, I can consider adding this feature, it shouldn't be difficult.

**Comment by ghost** [comment]
> `Switch to tab` suggestion can't be disabled yet, I can consider adding this feature, it shouldn't be difficult.

If not disabled or not allowed to, this doesn't help since most bookmarks and commonly searched terms or links are at bottom and suggestions are random and unrelated. In terms of usefulness, you need to do something to improve browsing, like if possible, via flags.
