### ISSUE TITLE
Downloading an image.

### ISSUE THREAD

**Issue by master1274** [fork-maintainers/iceraven-browser#727]
In the current version of the browser, there is some kind of glitch when trying to bring up the menu by long pressing on an image. https://www.google.com/search?q=Portal+64&newwindow=1&client=firefox-b-m&sca_esv=597832100&tbm=isch&sxsrf=ACQVn0-coRLChj08URVt-ERyPE7lVopJvQ:1705075914099&source=lnms&sa=X&ved=0ahUKEwiVqLLhntiDAxWtAxAIHWLuD44Q_AUIBygC&biw=832&bih=409#imgrc=5PM0hz-mZQ6L3M

**Comment by akliuxingyuan** [comment]
I tested it and there is no problem

**Comment by MysticPalash** [comment]
It's still there, even in latest. I'm also unable to download images.

**Comment by akliuxingyuan** [comment]
> It's still there, even in latest. I'm also unable to download images.

useless comment without detail

**Comment by master1274** [comment]
At this point in time, I see that the problem has been fixed. I don’t know which assembly exactly. I don't track it in that much detail. But in the current today There is no problem with the build.
