### ISSUE TITLE
[android] feature request: tablet mode

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#731]
Alright, it was already talked about, but I cannot delete the message.

Firefox promissed user base that the tablet mode for tabs is being worked on, but four years passed and it became an forgotten thing.
What about adding ability to enable it?

**Comment by TimonTheMicro** [comment]
Firefox promissed user base that the tablet mode for tabs is being worked on, but four years passed and it became an forgotten thing.
What about adding ability to enable it?

**Comment by akliuxingyuan** [comment]
No, there is no such switch to turn on tablet mode, Mozilla need optimize it first.
