### ISSUE TITLE
主页怎么会出现 这个  定制主页 ？

### ISSUE THREAD

**Issue by klcb2010** [fork-maintainers/iceraven-browser#732]
![Screenshot_2024-01-22-20-23-06-858_io github forkmaintainers iceraven](https://github.com/fork-maintainers/iceraven-browser/assets/32628414/784ea59f-6591-40f8-9069-e09b148fb9ed)
  以前的版本都没有这样的情况

测试发现官方版本从今年release.2024.01.15.latest.arm64-v8a开始出现这个，这不是Iceraven的问题。

**Comment by akliuxingyuan** [comment]
fixed in https://github.com/fork-maintainers/iceraven-browser/commit/f6a29e42351aa9ce6a202c56f1bcb6c9a9e8acfc
