### ISSUE TITLE
[BUG] Always crashes System UI when using address bar bookmarks suggestions function 

### ISSUE THREAD

**Issue by huzat** [fork-maintainers/iceraven-browser#734]
Hello!

I am getting this bug for a while now.
(Maybe after the newest updtae.)
Version 2.15.1
Android 11
Turned off all add-ons.

When typing in address bar and it tries to search between history and bookmarks it crashes System UI. 
/I have to wait a few seconds but it always crashes example: searching for GitHub bookmarks./
Tested turning off other features in 
"Addressbar Iceraven suggest"
and when the bookmars was turned off it worked again.

**Comment by Magicrafter13** [comment]
It's been crashing in me more and more in the past couple months. Not any one particular action though. But often when I open it, and open a new tab and do a search and start browsing or scrolling, then it gets really choppy, before ultimately crashing the system (OneUI in my case [Samsung]). I wonder if this is related...

Edit: actually it does seem to specifically happen when I start by searching from the address bar

**Comment by akliuxingyuan** [comment]
May be similar to #212

**Comment by Magicrafter13** [comment]
This hasn't happened for me since very shortly after I first commented. I believe an update fixed this, as I seem to recall it went away directly following an update.

**Comment by huzat** [comment]
@Magicrafter13 is right one of the updates seems to fixed this bug. Thanks!
