### ISSUE TITLE
Support onetab extension

### ISSUE THREAD

**Issue by jloutsch** [fork-maintainers/iceraven-browser#735]
Hello, I was able to install the onetab extension in the browser, however it does nothing once I tap it. It SHOULD create a page full of links from all of my open tabs in order to reduce the tabs I have open. This is a huge battery drain on android would be an excellent addition to iceraven.

**Comment by akliuxingyuan** [comment]
It‘s not compatiable with firefox android, nothing iceraven can do here currently

**Comment by jcleng** [comment]
@akliuxingyuan how to develop an extension for iceraven, is there any wiki on it? use like [wxt](https://github.com/wxt-dev/wxt) framework
