### ISSUE TITLE
[Bug] Cannot download files from releases because problem with with github or iceraven itself

### ISSUE THREAD

**Issue by Nes2525** [fork-maintainers/iceraven-browser#736]
https://github.com/fork-maintainers/iceraven-browser/assets/144382577/0a79a41a-088c-48c7-9274-ab248f9bcd8f

It was working fine like a week ago.

Note: i currently use latest version, this is just an example.

**Comment by blindmodz** [comment]
Same here using MIUI 14 (Android 13), latest Iceraven version and Github Beta (1.147.0)

**Comment by nekocatso** [comment]
same in iqooneo8，android 11

**Comment by nekocatso** [comment]
also happen in Iceraven 2.15.2 github version 1.147.0

**Comment by Nes2525** [comment]
Update on the issue, if you disable opening links with github it will fix the issue.


Android Settings App > Apps > Github > Opening links > Disable

**Comment by akliuxingyuan** [comment]
Fixed by github
