### ISSUE TITLE
[Bug] "What's New" Points to Firefox 79.0's Info Page on Mozilla.org

### ISSUE THREAD

**Issue by CharmCityCrab** [fork-maintainers/iceraven-browser#74]
## Steps to reproduce

1. Launch browser with no tabs open to the screen that reads "Browser".
2. Click on the "Menu" (Three dot) button in the upper or lower right hand corner (Depending on individual user settings)
3. Click on "What's New?".

### Expected behavior

This should load a page with the release notes for the version of Iceweasel the user is currently using.  

I recommend a link to "https://github.com/fork-maintainers/iceweasel/releases" as the closest equivalent currently existing page.

That seems like the easiest fix until such a time as an even better solution may become available.

### Actual behavior

This button leads to "https://support.mozilla.org/en-US/kb/whats-new-firefox-android-79?as=u&utm_source=inproduct", which is a link to information about Firefox instead of IceWeasel.

I know this a housekeeping type item and not a sexy new potential feature, but I think it's good to get these things squared away as they can be important for user clarity, brand diffentiation, showing off new features, perception of being up to date, and in presenting a polished professional look.  It's the type of thing a reviewer for a tech website might notice if it's not right.

**Comment by interfect** [comment]
Yeah, we should definitely link that to our releases page instead.

**Comment by interfect** [comment]
I think this is all controlled from https://github.com/fork-maintainers/iceweasel/blob/1b3802164c8d2ca22dbead11ff449e44705b0c8b/app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt#L87-L91

The other methods in that class may also need replacing.
