### ISSUE TITLE
my phone's status bar in YouTube video

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#744]
when I try to watch YouTube videos in full screen. and then I find my phone's status bar in there. it will never disappear.
![IMG_20240309_180143](https://github.com/fork-maintainers/iceraven-browser/assets/30223562/9b5fe92f-b696-4925-a595-ac7eac02f571)

**Comment by akliuxingyuan** [comment]
I believe firefox-android have same behavior, if so please report to upstream
