### ISSUE TITLE
Download status 

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#746]
When I download a file, it doesn't display any status or percentage.
Android 8 v7, iceraven latest build

**Comment by akliuxingyuan** [comment]
download status is in notification, make sure you give the permission

**Comment by ghost** [comment]
@akliuxingyuan I have already granted permission, and I receive a notification after the file has finished downloading. It is not even an issue for small files, but for large files, I have no idea if the download is continuing, if it stopped, or what percentage it is at.

**Comment by akliuxingyuan** [comment]
<img src="https://github.com/fork-maintainers/iceraven-browser/assets/53224655/8843fcc7-d7a4-4c88-aaab-ac8645dd966c" width=50%/>

**Comment by ghost** [comment]
@akliuxingyuan My phone is the problem then. Since Ice's notification is enabled, I guess I will look into this further. Regards.
