### ISSUE TITLE
Feature Request : amoled friendly dark mode for Iceraven.

### ISSUE THREAD

**Issue by MehrabShawon** [fork-maintainers/iceraven-browser#749]
Waiting for an amoled friendly dark mode for a long time now. Amoled theme to make the homescreen & settings background pitch black would be cool. If it's not possible, a pitch black wallpaper for homescreen would also be nice.

Thanks for the work btw! Appreciate it.

**Comment by akliuxingyuan** [comment]
duplicated of #40
