### ISSUE TITLE
Exclude Play Store dependency

### ISSUE THREAD

**Issue by bbigam** [fork-maintainers/iceraven-browser#75]
Upstream added another proprietary dependency, for the Play Store: https://github.com/mozilla-mobile/fenix/commit/365d1019f6ee7c28a2824a80506d74977983544b

Fortunately the patches and scripts from Fenix F-Droid have already been updated to patch it out: https://gitlab.com/relan/fennecbuild

EDIT: here's the diff: https://gitlab.com/relan/fennecbuild/-/commit/d8a40373afa8c117dd4a10c445617c17fa309b0e

Any way, I'm suggesting that the Play Store be patched out with the other proprietary stuff. All credit to relan who both noticed the new dependency and quickly updated the patches to exclude it.

**Comment by interfect** [comment]
We should definitely do this. Do you want to apply that part of the patch and open a PR @bbigam?

**Comment by bbigam** [comment]
I'll try... I've never done a PR before so I have no idea if it'll work or not.
Here it is: https://github.com/fork-maintainers/iceweasel/pull/76

**Comment by interfect** [comment]
This looks like it should work.

Some of the version variables are probably going to conflict when Mozilla updates the versions of things they want. We can either keep deleting them, or add them back in unreferenced when that happens.

**Comment by interfect** [comment]
I merged #76; the play store dependency should be gone in the next release.
