### ISSUE TITLE
Application is not installed/updated

### ISSUE THREAD

**Issue by TenchMaviatorius2759** [fork-maintainers/iceraven-browser#750]
A file with armeabi-v7a architecture in [version 2.17.0](https://github.com/fork-maintainers/iceraven-browser/releases/tag/iceraven-2.17.0) gets the error "There was a problem parsing the package" when installing or updating.
Other architectures do not have this problem.

**Comment by master1274** [comment]
Package armeabi-v7a completely damaged during assembly.

**Comment by master1274** [comment]
It seems the developer is not interested in the problem at all?
![Screenshot_20240321-151849](https://github.com/fork-maintainers/iceraven-browser/assets/20639709/dc481c0a-fd14-46fc-af3b-30499a426547)

**Comment by KaKi87** [comment]
@akliuxingyuan ? Thanks

**Comment by kgursu** [comment]
Same for every armv7 users I think. Need a redeploy of the file, devs on duty please!...
