### ISSUE TITLE
I can't search in my history for more than 20 results

### ISSUE THREAD

**Issue by VVSRwastaken** [fork-maintainers/iceraven-browser#751]
I need to search for pages older than the first 20 results, is there any way I can export the whole history so I can check it manually on windows or somewhere else other than the app?

**Comment by akliuxingyuan** [comment]
after commit https://github.com/fork-maintainers/iceraven-browser/commit/4b024889db25ccfa1dd2d76e32c02b0fe10bbb6f, Iceraven should provides `maxNumberOfSuggestions * HISTORY_METADATA_RESULTS_TO_FILTER_SCALE_FACTOR=200` history suggestions
