### ISSUE TITLE
Iceraven for desktop. 

### ISSUE THREAD

**Issue by Zain3967** [fork-maintainers/iceraven-browser#756]
Please make this software available for windows. It's such a good browser for everyday work.

**Comment by krypciak** [comment]
Iceraven tries to be more like a desktop browser with it's `about:config` support and bigger add-on list.
All desktop browsers have that.
What different would it be from the regular Firefox?
I would recommend Firefox or a Firefox based browser.
Maintaining a browser fork is a ton of work, and I don't see the Iceraven maintainer maintaining another one.

**Comment by akliuxingyuan** [comment]
> Please make this software available for windows.

will not happen.

**Comment by SyCoREAPER** [comment]
@Zain3967 

Old thread I know but figured others msy find this useful as well. 

For desktop I suggest @Alex303130 's Mercury Browser. It tends to be a bit behind on builds but that seems to be for compatibility reasons. It's stupid fast and optimized. I can't even get Firefox with Betterfox to perform that well (which is your alternative). 

The other desktop forks I've seen or to put it plainly, questionable. Closed source and lots of questions marks.
