### ISSUE TITLE
Feature request: tab bar of nightly

### ISSUE THREAD

**Issue by RedMentos** [fork-maintainers/iceraven-browser#762]
The nightly version of firefox has a secred tab bar function that is forgotten about i guess. Please ad this option to iceraven. Its the only reason for me to have 2 browsers. In every other aspect iceraven is just great.

**Comment by akliuxingyuan** [comment]
I don't know what you refer?

**Comment by RedMentos** [comment]
![Screenshot_Firefox Nightly](https://github.com/user-attachments/assets/ce19190a-10df-4deb-ba56-ca2f9b51f4a8)
This feature. It can just be found on the Nightly app.

**Comment by RedMentos** [comment]
https://www.reddit.com/r/firefox/comments/1b2l2z3/firefox_nightly_for_android_adds_a_tab_strip_on/
Sorry the new version of firefox nightly dosnt seem to have it anymore. One of them of the last 4 months has atleast. I guess they dont wanna implement tabs an android... maby its not to hard for you to implement it bc it is got already implemented in one of the last versions. It really makes a big difference in my opinion.

**Comment by RedMentos** [comment]
https://github.com/mozilla-mobile/firefox-android/pull/5218#issuecomment-1966233109
Apparently, it's called the tab strip, and it's only visible on tablet DPI on the newer versions of nightly. I installed it a few months ago, and that version had it in the secret settings like I said and seen in the link. It works pretty well on my phone despite the bugs of Nightly. I really don't know why they didn't implement it already as standard. Surely you can bring an option to Iceraven so I can use my favorite browser daily.
