### ISSUE TITLE
Bottom bar (like on Firefox for iOS)

### ISSUE THREAD

**Issue by idontveapc** [fork-maintainers/iceraven-browser#765]
I dislik Firefox's (for android) interface, it's slow. Unlike chrome, you could navigate fast.

Just expanding the bottom bar and adding the icons (options) from the more menu to the bottom bar would make IceRaven (firefox) feel as fast to browse as you want. Don't know if Mozilla gives an opportunity to do that. I hope it's possible and would be added asap. And other feels the same.

Also, of course, search bar placement in not so important (it could be top or bottom).

**Comment by akliuxingyuan** [comment]
duplicated of #675
