### ISSUE TITLE
Add maintainers as collaborators to this project

### ISSUE THREAD

**Issue by abhijitvalluri** [fork-maintainers/iceraven-browser#77]
Hi @interfect, thanks for setting up the fork-maintainers org in github and adding us to it. But you still need to provide us access to the repo as collabortors, under the settings for the repo. Then we can review/approve/merge PRs, close issues, and pull the upstream and merge to fork and create releases.

Speaking of releases, quite a few PRs were merged since the last release and lot of upstream changes were merged as well. We should create a release soon.

**Comment by interfect** [comment]
Sorry, you should have proper access now. Apparently organization members default to just having read permissions on organization repos, which I didn't expect.

I'm going to see if I can build a release today.
