### ISSUE TITLE
a translation mistake

### ISSUE THREAD

**Issue by klcb2010** [fork-maintainers/iceraven-browser#772]
There is a translation mistake, the last item should be "email address" in _account_ settings to choose the items to sync.

![Screenshot_2024-05-06-14-53-54-007_io github forkmaintainers iceraven](https://github.com/fork-maintainers/iceraven-browser/assets/32628414/bf9c13e1-97bd-4aaf-b890-ef4f1468a114)

**Comment by akliuxingyuan** [comment]
Please report upstream, thanks. https://bugzilla.mozilla.org
