### ISSUE TITLE
[bug] audio player fails at n-tv.de

### ISSUE THREAD

**Issue by seniordevel** [fork-maintainers/iceraven-browser#774]
1. Open german news portal: n-tv.de
2. open a page with audio version available, e.g. https://www.n-tv.de/politik/Indizien-haeufen-sich-Russen-sammeln-sich-fuer-weiteren-Vorstoss-article24970281.html
3. Start audio player

Expected result:
The text is spoken, as it works in Vivaldi browser

Actual result with latest Iceraven:
Nothing happens, no audio and no progress shown.

**Comment by seniordevel** [comment]
I reopen this issue for the following reasons:

For a long time, much more than 12 months,  I've seen this problem, almost every week.

Some days ago, playback suddenly worked, thus I believed it was fixed by an -unrecognized- update.
But, no ... still not working, except this single success.

Thus I will re-open this issue.

Please note:
In another browser, VIVALDI, which is an OPERA fork, playback always, works fine, every day.

So I think there still is an issue with Iceraven.

**Comment by akliuxingyuan** [comment]
Emm, I just tested it with the latest version, and it works. I don't know what caused it to fail.

**Comment by seniordevel** [comment]
Well, just tested again, and it works,
thus I will close this issue.
