### ISSUE TITLE
there is no shortcut at main page on 2.19.1

### ISSUE THREAD

**Issue by hingbong** [fork-maintainers/iceraven-browser#776]
![Screenshot_20240610_185148_Iceraven](https://github.com/fork-maintainers/iceraven-browser/assets/26398240/e505b107-7e88-4878-9881-d27a2401e336)
After update, there is no shortcut.

**Comment by akliuxingyuan** [comment]
Please make sure you enabled shortcut option at `Settings > Homepage >  Shortcuts`

**Comment by hingbong** [comment]
![Screenshot_20240611_181735_Iceraven](https://github.com/fork-maintainers/iceraven-browser/assets/26398240/9487d6dc-fbb0-452d-89d4-2693fcd73559)
I've already enabled it.

**Comment by kjxxxx** [comment]
I have the same problem. Android 14, latest Iceraven, clean install. No shortcuts or most frequently visited pages. Of course, the appropriate options are enabled.

**Comment by hingbong** [comment]
I'm on Android 13 and tried a fresh install and the problem persists.

**Comment by kjxxxx** [comment]
Thank you! Everything is OK now.
