### ISSUE TITLE
 Full URL Feature Broken in Iceraven 2.20

### ISSUE THREAD

**Issue by CharmCityCrab** [fork-maintainers/iceraven-browser#778]
*Version:*

Iceraven 2.20

*Expected behavior:*

When an Iceraven user has toggled "STRIP HTTP/HTTPS/WWW" to "Off" under "Menu>Settings>Customize", it should show full URLs whenever the URL bar normally appears, never showing a URL without it being complete with protocol, etc..

This has been a user option since 2020, something Iceraven brought back in the first week or two after forking from Firefox, which abandoned the feature after v. 68 in 2020.

I have been on the road and can't promise IR v2.20 is the first version where the feature doesn't work, but it either happened on this version first or carried over from another recent version.

*Actual Behavior*

URLs have reverted to what I think is the default upstream behavior of only showing a full URL when the user touches the URL bar, and then only temporarily for that one interaction.

At all other times, a truncated URL is shown instead.

The user option still appears as a toggle, but now does nothing.  Turn it on or turn it off, one now has URLs stripped.

*Practical difference*

Desired behavior when strip URL is toggled to off would to display a website URL in the style of  "https://www.example.com/example.html".

Instead, websites display sites as "example.com/example.html" except when interacted with, which is only supposed to be the behavior when strip URLs is toggled to on (but is now both).

*Why it's important*

This option has helped fulfill Iceraven's stated attempt to provide more options and customizations to end users than other similar browsers, and to allow users to see more information more option about the websites they interact with.

I believe it is the only Fenix/Firefox fork that includes this feature on Android, which makes it an Iceraven distinctive and is a key reason why some of us use Iceraven over other options.

Additionally, it is worth noting that sometimes "https://www.example.com" and "https://example.com" are different webpages.  Usually that is a configuration error server side, but it does happen and if you can't see the "www" when it is there, the end user may not be sure which webpage they are getting.

**Comment by CharmCityCrab** [comment]
Still an issue in Iceraven 2.20.3

**Comment by CharmCityCrab** [comment]
Similar but not identical to https://github.com/fork-maintainers/iceraven-browser/issues/784

**Comment by VK3002** [comment]
Same on my device.
Ver: Iceraven-2.20.3

**Comment by akliuxingyuan** [comment]
fixed in f5f6bfb1d13916f62859e986c44a12960133be8d
