### ISSUE TITLE
AMOLED Theme

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#779]
Please, be the first one firefox fork with amoled theme, i really need amoled. I have grey 😡

**Comment by Totallynotmwa** [comment]
Yes Yes YESSSS

**Comment by bakinazik** [comment]
I'd like it to at least apply the "Material You" theme. I can't believe they used this shitty color as a dark theme. Classic stupid Mozilla move. It doesn't surprise at all..

**Comment by akliuxingyuan** [comment]
dup of #40
