### ISSUE TITLE
The URL gets trimmed despite deactivation via about:config

### ISSUE THREAD

**Issue by DrDustwolf** [fork-maintainers/iceraven-browser#784]
Actual behavior: Setting browser.urlbar.trimURLs to false in about:config is having no effect.
The URL still gets trimmed.

Expected behavior:
True (default): Trim "http://" prefix from url address displayed in location bar .
False: Don't trim url in location bar.

**Comment by CharmCityCrab** [comment]
Similar but not identical to https://github.com/fork-maintainers/iceraven-browser/issues/778

Possibly connected- i.e. the GUI option in the other issue may be flipping the about:config tag and if that doesn't function anymore...

**Comment by akliuxingyuan** [comment]
fixed in f5f6bfb1d13916f62859e986c44a12960133be8d
