### ISSUE TITLE
Copy button in app's searchbar when clicking on it

### ISSUE THREAD

**Issue by Kurrode** [fork-maintainers/iceraven-browser#786]
Rather than having the QR or microphone button show up when you click on the url of the current page, it'd be much more useful to have a copy or share button.

QR code scanner and microphone are gonna be used only in the start page anyway.

**Comment by kaafir786** [comment]
Well a workaround is share from menu and copy.

**Comment by akliuxingyuan** [comment]
long press the url, and click copy.
