### ISSUE TITLE
Pdf viewer do not work

### ISSUE THREAD

**Issue by kaafir786** [fork-maintainers/iceraven-browser#787]
Recently mozilla allowed using in app pdf viewer to view external pdf files.
Basically open pdf from file manager, Browser is an option to do so.
It works in fennec but not in iceraven

Problem is it take it as extension and try to install it and fails.

Saying browser to take it is pdf (not xpi) will make it work probably.

**Comment by kaafir786** [comment]
It still do not work.

https://github.com/user-attachments/assets/41edaeb0-bc7c-4681-92b5-73b01e604796

**Comment by Ahmey1400** [comment]
For now you can use this extension:
https://addons.mozilla.org/en-US/android/addon/doqment/

**Comment by Ahmey1400** [comment]
Pdf reader extensions dont work either
