### ISSUE TITLE
[Bug] Translate this Page Add-on 

### ISSUE THREAD

**Issue by Raul1198** [fork-maintainers/iceraven-browser#79]
## Steps to reproduce
1. Go to AddOn Manager
2. Install Translate this page AddOn
![Screenshot_20200908-001759349](https://user-images.githubusercontent.com/29801315/92412393-5b122f80-f169-11ea-806a-093f3e88fbfe.jpg)

### Expected behavior

When using the add-on the Add-On tab should show only one Translate this Page option

### Actual behavior
The add-on tap is showing two Translate Page Option

![Screenshot_20200908-001819157](https://user-images.githubusercontent.com/29801315/92412407-6a917880-f169-11ea-8d91-6ceb7016b3ac.jpg)

### Device information

* Android device: 10
* Fenix version: fork-9 (Build #2015761635)

**Comment by interfect** [comment]
This looks like a bug. Not sure how to fix it though. Have you reported it to the add-on devs? Maybe they're doing something weird.

**Comment by Raul1198** [comment]
> This looks like a bug. Not sure how to fix it though. Have you reported it to the add-on devs? Maybe they're doing something weird.

Will report to the dev 👌

**Comment by rsssxd** [comment]
Hey it's not a mistake, one to ask if the page will be translated, one to manually translate
