### ISSUE TITLE
Front Page Github Text is Still a Copy of the Mozilla-Mobile Project

### ISSUE THREAD

**Issue by CharmCityCrab** [fork-maintainers/iceraven-browser#8]
In order to better serve the project and make sure users and volunteers go to the place they intend to go to, it may make sense to revise the front page to reflect that this an Iceweasel version of Fenix and not Mozilla Firefox.

1.  The easiest stopgap solution would be to simply do a find/replace on the word "Firefox" and replace it with "Iceweasel" and to change all links to plain text.

2.  A next level approach would eliminate all chunks of text that don't apply to Iceweasel or that reference Mozilla in a way that is inapplicable to Iceweasel in addition to the above.  Maybe a paragraph or two about what you want to achieve with this project could optionally be added as well.

3. A third step and the most time consuming approach would be to do a total rewrite.

The nice thing here is that you could do, say, step 1 pretty quickly for now and it doesn't rule out doing step 2 or 3 later if you have the time and inclination.  It doesn't have to be done all at once, and it isn't all or nothing. :)

I think we'd all agree that the priority should be on the web browser and not the text of the GitHub homepage. :)

**Comment by Poopooracoocoo** [comment]
The README could be based on what interfect wrote here: https://github.com/interfect/fenix/releases/tag/fork-0

**Comment by CharmCityCrab** [comment]
> The README could be based on w:hat interfect wrote here: https://github.com/interfect/fenix/releases/tag/fork-0

It could.  My hope is that interfect is reconsidering some of that in light of the support he's getting and that any version that goes to the front page would be a bit different, with talk of being a long-term alternative to Firefox built on Fenix and getting frequent security updates and such, though. :)  Maybe I'm dreaming.

However, he was brave enough to get out there first.  This is a real opportunity for him and for us as users if he's up to it and willing to stretch beyond his day one vision.

There is definitely a market out that in the mobile Android space that Chrome and the Fenix version of Firefox, and stuff based on them, are not meeting.  People are craving something that lets them have more control and see more of what is going on with their browser and with the websites they visit.  Phone screens are bigger than ever, and powered by stronger CPUs and more RAM.  There's no reason we can't get more from our mobile browsers except that no one is actually doing it.  Iceweasel, in a relatively short span of time, has shown that more is possible, and it'd be really awesome if they fulfilled the promise they've demonstrated on a longer-term basis.  I'd love to see this get to the point where we can use it as our default browsers with confidence, available from Google Play and F-Droid, with security updates and so forth.

If that won't come from this project, hopefully there's someone willing to pick up the baton.

I've really been trying to persuade developers to come over here and do a few pull requests, and spreading the word to users.  I'm not a developer and I'm not involved with the project, but it's a project that, as a user, I'd really like to see reach it's full potential.

**Comment by Poopooracoocoo** [comment]
>My hope is that interfect is reconsidering some of that in light of the support he's getting and that any version that goes to the front page would be a bit different, with talk of being a long-term alternative to Firefox built on Fenix and getting frequent security updates and such, though. :) Maybe I'm dreaming.

uh that sounds like a bit of stretch lol. This is for the developer foremost. Us having this and the developer implementing suggestions and accepting PRs is a massive benefit. He has no obligation to us, just like some other browsers. It's a nice dream though. 

But yes, there's certainly a space for powerful mobile browsers! Bromite, Ungoogled Chromium, Iceweasel Fenix, Kiwi and to an extent, Brave, are bringing parity with desktop browsers.

Thanks for promoting this browser btw. I'd donate what I can! If the dev is reading this, please add a link! <333

**Comment by interfect** [comment]
I've pulled in #19's README changes and written a bit more myself, including some build and download instructions. I'm going to declare this fixed.
