### ISSUE TITLE
[Bug]: Webauthn doesn't work

### ISSUE THREAD

**Issue by CactusPie** [fork-maintainers/iceraven-browser#814]
### Steps to reproduce

1. Go to a webauthn demo website, for instance https://demo.yubico.com/webauthn-technical/registration
2. Click next 

### Expected behaviour

A popup should prompt you to use your passkey. It works in regular Firefox, but not for Iceraven . It of course affects regular sites as well, not just this demo site.

### Actual behaviour

An error appears

### Device name

Xiaomi Mi 9T Pro

### Android version

Android 13

### Iceraven version

2.24.0

**Comment by Felitendo** [comment]
same issue here

**Comment by bibi-b** [comment]
Same here.

**Comment by Felitendo** [comment]
I noticed it also doesn't work in Fenix

**Comment by akliuxingyuan** [comment]
dup of #451
