### ISSUE TITLE
[Feature Request]: DuckDuckGo Lite and HTML support

### ISSUE THREAD

**Issue by NikunjK8** [fork-maintainers/iceraven-browser#815]
### Feature Summary

Fennec browser supports Ddg html and lite version as alternative search engine (Original Firefox might does too but I'm no sure). It would be great if you can implement those in Iceraven as well.

### Feature Research

It would be very helpful for people like me who's living in poor countries with very limited and slow internet connection. We often need to search something important and sit around for search results to load.

### Target beneficiaries

People with terrible internet

**Comment by feelingwalnut** [comment]
Adding custom default search engines is already a feature?

https://lite.duckduckgo.com/lite?q=%s

**Comment by NikunjK8** [comment]
Didn't knew that, thanks
