### ISSUE TITLE
[Bug]: v2.26.0 on Android tablet displays all sites as desktop

### ISSUE THREAD

**Issue by MrWhipple** [fork-maintainers/iceraven-browser#834]
### Steps to reproduce

Installed Iceraven 2.26.0 as an upgrade to 2.25.3 on my Android tablet running Android 12.

### Expected behaviour

Previous versions of Iceraven displayed mobile versions of websites unless the "Desktop site" toggle was enabled.

### Actual behaviour

The current version of Iceraven displays the desktop version of all sites and cannot be overridden. Because of this, pages load and respond very slowly (especially YouTube).

### Device name

Lenovo Tab P11 Plus 

### Android version

Android 12

### Iceraven version

2.26.0

**Comment by gsxgmpkt9020** [comment]
You should disable this in 

settings-sites-"always request all sites as desktop" (it is default settings)

"Desktop site toggle"  cannot override the default setting, so you should change it in first

**Comment by MrWhipple** [comment]
> You should disable this in
> 
> settings-sites-"always request all sites as desktop" (it is default settings)
> 
> "Desktop site toggle" cannot override the default setting, so you should change it in first

_Wow,_ thank you so much! I toggled that (it's in _Settings_ > _Site settings_ ), and my problem is solved.

I don't remember turning that setting on. Was it enabled automatically in v.2.26.0?
