### ISSUE TITLE
[Extensions request] "Fingerprinting defenders"

### ISSUE THREAD

**Issue by aquaspy** [fork-maintainers/iceraven-browser#84]
https://addons.mozilla.org/en-US/firefox/addon/canvas-fingerprint-defender/?src=search

https://addons.mozilla.org/en-US/firefox/addon/webgl-fingerprint-defender/?src=search

https://addons.mozilla.org/en-US/firefox/addon/font-fingerprint-defender/?src=search

https://addons.mozilla.org/en-US/firefox/addon/font-fingerprint-defender/?src=search

They are very light, and report random values, which is very good for privacy in general.

They are all open source, and I think that they might work

Thanks for all the work and this fork :)

**Comment by jaytohe** [comment]
You can add them on your own. See how [here](https://github.com/interfect/fenix/pull/50#issuecomment-685187265).

**Comment by aquaspy** [comment]
Loved it! it's amazing! thank you so much
