### ISSUE TITLE
Collect license headers from liberate patch

### ISSUE THREAD

**Issue by interfect** [fork-maintainers/iceraven-browser#88]
[Relan added some license headers](https://gitlab.com/relan/fennecbuild/-/issues/4#note_408112040) for the files we grabbed via the liberate patch. Even though a lot of them aren't maybe really copyrightable, it would be nice to have the headers. We should grab them into the relevant files.

**Comment by bbigam** [comment]
This should do it: https://github.com/fork-maintainers/iceweasel/pull/91

**Comment by interfect** [comment]
This was fixed in #91.
