### ISSUE TITLE
Limit Who Can Close Issues

### ISSUE THREAD

**Issue by CharmCityCrab** [fork-maintainers/iceraven-browser#89]
### What is the user problem or growth opportunity you want to see solved?

I would like to limit the closure of issues on this tracker to maintainers and other known developers who contribute to the project and know how GitHub is supposed to work.  This could also potentially be expanded to select non-devs who the maintainers feel have a solid grasp of things.

### How do you know that this problem exists today? Why is this important?

The original poster on issue #86 closed his bug about strict tracking protection turning itself off because he personally was happy with the solution of using custom protection instead, which apparently does not suffer from the same bug (Incidentally, that bug should be reopened :) )

While it's great that the original poster found a workaround he's satisfied with, this is more of a bug tracker than a help forum.  The underlying bug is still there, and should be an open issue.

I'm experiencing it myself (As noted in the issue) and there is no indication that the original poster actually fixed the issue either, he just worked around it. It's still something that should be addressed in a future browser update if we can pin down what's causing it and how to fix it.

I don't blame the original poster for assuming no longer being personally bothered by a bug was sufficient for the issue to be closed.  The difference between a help forum where one would close an issue for that reason and filing a bug in the issues tracker on GitHub, which in such circumstances is serving as a bug tracker, can be subtle for novice and even some intermediate users.  On a help forum, one would close the issue. On a bug tracker, one wouldn't.

Obviously, it benefits the project to continue to encourage everyone who sees bugs to file bug reports regardless of their level of familiarity with those type of distinctions.  I don't blame the original poster, who was doing the right thing in opening the thread, for getting a little confused.  

We're likely to keep seeing stuff like this in the future from various new folks.  That's why I don't think people should be allowed to close their own issues unless they are a maintainer, a developer who's worked on the project, or someone trusted as reasonably well versed in GitHub ediquette and can trusted not to prematurely close things.

Maybe some sort of queue could be created where people can flag their own issues for closure, with people the project trusts to know when they should be closed stopping by to either actually close it or keep it open and remove the flag, but since I think the whole "help forum" vs. "bug tracker" thing is likely to recur as a point of confusion in terms of when a bug report should really be closed, I think it's best if we take it out of the hands of the original posters, because we're likely to see this again and again.

I don't know what the actual options GitHub offers are for limiting who can close bugs, but it seems like some sort of an adjustment to the settings might be in order.

Doing this should also cut down on redundant issues that have to be merged into older issues that are closed and then reopened later.  People who know to post to an existing issue if they are experiencing the same problem instead of starting a new issue will nevertheless start a new issue if the original one is prematurely closed and not visible to them as an open issue. 

### Who will benefit from it?

Users, developers, people who want to wipe out bugs, future browser code, browser stability, etc..

**Comment by interfect** [comment]
I don't think there's a way to stop the people who open issues from closing them again (I just checked the settings), and in general I think we need to allow it for the case where someone reports something that turns out not to really be a bug, or to be because they were doing something else wrong that they had forgotten about.

If you run into an issue that's closed but that you still have, I think the right thing to do is to open a new issue that references the old one.

If there's a bug that the OP won't stop closing, I *think* it can be locked to stop them doing that.
