### ISSUE TITLE
(REQUEST) List or privacy and utility addons

### ISSUE THREAD

**Issue by angriness-sleek** [fork-maintainers/iceraven-browser#95]
ETag Stoppa – Get this Extension for 🦊 Firefox (en-US) - https://addons.mozilla.org/en-US/firefox/addon/etag-stoppa/

Temporary Containers – Get this Extension for 🦊 Firefox (en-US) - https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/

Firefox Multi-Account Containers – Get this Extension for 🦊 Firefox (en-US) - https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

Privacy Settings – Get this Extension for 🦊 Firefox (en-US) - https://addons.mozilla.org/en-US/firefox/addon/privacy-settings/

Chameleon – Get this Extension for 🦊 Firefox Android (en-US) - https://addons.mozilla.org/en-US/android/addon/chameleon-ext/

behavioral-Keyboard-Privacy – Get this Extension for 🦊 Firefox Android (en-US) - https://addons.mozilla.org/en-US/android/addon/behavioral-keyboard-privacy/

Smart Referer – Get this Extension for 🦊 Firefox Android (en-US) - https://addons.mozilla.org/en-US/android/addon/smart-referer/

**Comment by jaytohe** [comment]
You can add add-ons on your own since 1 release ago. See how [here](https://github.com/interfect/fenix/pull/50#issuecomment-685187265).

**Comment by interfect** [comment]
I put all of these on the main list too.
